### PR TITLE
Java dependencies for sp2

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

A lot of java libs have changed in SLES 15 SP2.
Try to keep things building.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **internal**

- [x] **DONE**

## Test coverage
- No tests: **fix building**

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@juliogonzalez JFYI: there were a lot of changes in java packaging in 15 SP2. So we have to adapt a lot. Take care when you submit. There where changes in `:Other` as well

**Comment by mcalmer** [comment]
Current Problem: the repositories are still "older" and do not contain the latest changes.
But we cannot build anymore without the changes.

**Comment by juliogonzalez** [comment]
@mcalmer you are basically telling me to have a look at `:Other` while submitting, right? If so, no problem, I always have a look, and to `:Kit` as well.

What do we have pending at `:Other`? I see everything building there.

**Comment by mcalmer** [comment]
> @mcalmer you are basically telling me to have a look at `:Other` while submitting, right? If so, no problem, I always have a look, and to `:Kit` as well.

Yes, I had to make changes at various spec files. So Kit is not affected.

> What do we have pending at `:Other`? I see everything building there.

Sorry, I did not keep a list. But my script tell me:

* apache-xmlrpc3
* nutch-core
* struts
* velocity
* velocity-tools

**Comment by juliogonzalez** [comment]
But you are talking about installation problems, not building problems, right?

I got confused by:
> Try to keep things building.

At the PR description.

**Comment by mcalmer** [comment]
> But you are talking about installation problems, not building problems, right?

Last week it was not building. We saw unresolvable for spacewalk-java and other packages.
We detect with our script only FAILED builds, but UNRESOLVABLE just happens.

**Comment by cbosdo** [comment]
taskomatic is also missing the new `slf4j-log4j12` package

**Comment by mcalmer** [comment]
@cbosdo not sure if you have tested with the fixed package. The current package in D:G:M:H was rolled back since we fixed a submission problem. This PR is not yet merged. So the fixes which are included here are not yet in D:G:M:H.

**Comment by cbosdo** [comment]
> @cbosdo not sure if you have tested with the fixed package. The current package in D:G:M:H was rolled back since we fixed a submission problem. This PR is not yet merged. So the fixes which are included here are not yet in D:G:M:H.

Sure, but I'm testing with my branch of D:G:M:H and your PR applied on top of my changes ;)

**Comment by mcalmer** [comment]
Time to merge now and see where we are.

**Pull request merged**
