### PR TITLE
Remove scripts moved to the uyuni-releng-tools repository

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Remove files moved to https://github.com/uyuni-project/uyuni-releng-tools

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by deneb-alpha** [comment]
note: when merging this PR, also https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog-rules-for-packages-in-git will require an update.

Current text is:
~~~
Alternatively, you can use the helper script in rel-eng/bin/mkchlog to automate the file creation. 
~~~

**Comment by cbosdo** [comment]
Don't merge until the releng tools are packaged and we have it installed on the automation servers

**Comment by cbosdo** [comment]
Required Submit Requests:
* https://build.opensuse.org/request/show/1129846

**Comment by cbosdo** [comment]
> note: when merging this PR, also https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog-rules-for-packages-in-git will require an update.
> 
> Current text is:
> 
> ```
> Alternatively, you can use the helper script in rel-eng/bin/mkchlog to automate the file creation. If run without an argument, it creates a changes file with proper naming and opens a text editor for you to add your entries. Run mkchlog --help for usage information. For convenience, you may consider adding rel-eng/bin/ to your $PATH. You can run the tool from any subdirectory of any package.
> ```

I have a git commit for the wiki ready locally. Sadly there are not PRs for wikis.

**Pull request merged**
