### PR TITLE
Fix ClassCastException when deleting SaltEvents

### PR DESCRIPTION
**Pull request by chiaradiamarcelo**
## What does this PR change?

Fix ClassCastException when deleting SaltEvents

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: bug fixing

- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

## Links

Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/6915

- [x] **DONE**

## Changelogs

Copy the following sentence as a new comment if you don't need changelog entries:

> gitarro no changelog needed !!!

If the test `changelog_test`already run, then add another new comment with the following text:

> gitarro rerun changelog_test !!!

### CODE REVIEW

**Comment by chiaradiamarcelo** [comment]
gitarro no changelog needed !!!

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by juliogonzalez** [comment]
Bypassing `merge_enabled`, it seems provo instances are having problem with the network.

**Pull request merged**
