### PR TITLE
Revert commit 91ca92d1 for compatibility with old traditional clients

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

rhnlib's SSL code is only used by the traditional stack on client systems, but we need to keep the very old TLS-related python code for SLE 12 and probably also RHEL 7 clients using python 2.7.

## GUI diff

No difference.

- [X] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: we don't test SLE 12 or RHEL 7 clients

- [X] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/24880
Port(s): # **add downstream PR(s), if any**

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by rjmateus** [comment]
Is this only affecting the traditional stack? If that is the case why are we adding it back to uyuni? Should we just open the fix to Manager 4.3?

**Comment by cbosdo** [comment]
> Is this only affecting the traditional stack? If that is the case why are we adding it back to uyuni? Should we just open the fix to Manager 4.3?

Because it's in the client tools and those are sadly shared between 4.3 and 5.0

**Comment by rjmateus** [comment]
> Because it's in the client tools and those are sadly shared between 4.3 and 5.0
Good point, thank you

**Comment by m-czernek** [comment]
@cbosdo could you fix the failing checkstyle please? Ignore comment should be good enough IMO.

**Comment by cbosdo** [comment]
> @cbosdo could you fix the failing checkstyle please? Ignore comment should be good enough IMO.

comment added

**Comment by Bischoff** [comment]
Bad news, SLE 12 SP 5 cannot bootstrap on a 4.3 server with the 5.0.1 client tools shared with 4.3. Message is
```
  File "/usr/lib/python2.7/site-packages/rhn/SSL.py", line 101, in init_ssl
    self._ctx = SSL.SSLContext(SSL.PROTOCOL_TLS_CLIENT)
```

**Review by m-czernek — APPROVED** [review]
Whoops, forgot to add my +1 after the comment. So, since it's a revert, +1

**Comment by nodeg** [comment]
I did a rebase in the GitHub webUI. When this PR gets merged, please squash the commits due to that!

**Review by Bischoff — APPROVED** [review]
tested to work on 4.3 BV

**Comment by raulillo82** [comment]
The errors in sonarcloud tests come from the insecure protocol (weak encryption) related to old clients like centos 7 and sles 12. This is known and it's ok to ignore the errors.

**Pull request merged**
