### PR TITLE
Ruby checkstyle GitHub Action

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

- Add a new ruby CheckStyle GitHub Action
- Update rubocop.yml to **use Ruby 2.5**
  - As GitHub Actions don't have support for Ruby 2.1
  - It can **impact on local dev envs running rubocop**, but is **not affecting to our local testsuite execution**.
- Update the rubocop_todo list.
  - Ideally, we should go through all the todo list and fix the warnings.

#### After merge it
 - Disable https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ruby_rubocop-pipeline/
 - We can't have this github action in spacewalk, but we need to port the rubopcop files
  - So it means that the sumadocker running rubocop will need to use Ruby 2.5 instead of Ruby 2.1 (@mseidl )

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- No tests: CI Check

- [x] **DONE**

## Links

None

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by srbarrios** [comment]
Note: Don't take into account the old ruby_rubocop PR check failing in that PR, it's using the old checkstyle available only for Ruby 2.1

**Comment by srbarrios** [comment]
> What will happen when we create the branch Manager-4.1 (soon) and we have it at the internal repository? Will this break internal tests?

If we do the steps I described in "After merge it" section, we should be safe.
The only possibility here is that some local dev environments need to update their rubocop and ruby to something newer than Ruby 2.1.

**Comment by juliogonzalez** [comment]
> If we do the steps I described in "After merge it" section, we should be safe.

> We can't have this github action in spacewalk, but we need to port the rubopcop files
> So it means that the sumadocker running rubocop will need to use Ruby 2.6 instead of Ruby 2.1 (@mseidl )

ACK. Do NOT merge this until we have the confirmation that someone can take care of this before I we branch Manager-4.1, as I don't want to have broken stuff when we create the private branch.

For now SLE15SP1 has Ruby 2.5, so it could be very well what we need to update to SLE15SP2 before we can do anything. Is this change compatible with Ruby 2.5 or only Ruby 2.6?

**Comment by srbarrios** [comment]
Yep. Fine to use 2.5, it might change a bit the checkstyle used for the rubocop linked to that version.
Tomorrow I will change that PR to use Ruby 2.5

**Comment by srbarrios** [comment]
I changed to 2.5. It seems it will not need changes in the todo list for Rubocop. All fine.

**Comment by mseidl** [comment]
sumadocker3:~ # ruby -v
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux-gnu]

**Comment by srbarrios** [comment]
> sumadocker3:~ # ruby -v
> ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux-gnu]

Related to our CI:

@mseidl @juliogonzalez @mcalmer it seems that the rubocop version setup in our internal sumadockers is wrong, it doesn't much the version it uses to be for Ruby 2.5, which must be 0.84.
In fact, after upgrade the Rubocop, we can also upgrade the version of Ruby used for Gitarro.
 it seems rubocop.ruby2.5 is not part of our internal repo https://gitlab.suse.de/galaxy/infrastructure/-/blob/master/srv/salt/pr-automation/init.sls

Just as a temporary solution before we make the proper changes to this salt state, we create a new gem of gitarro (if needed) and we change everywhere in susemanager-ci to point to <tool>.ruby2.5 , I will use `gem install rubocop` before we run the command in CI, so it updates it to the proper version for Ruby 2.5

**Comment by juliogonzalez** [comment]
Yeah, please go ahead with a PR to take care of installing rubocop for ruby 2.5 (at the infra repository).

Once it's done, we'll be able to remove Ruby 2.1 from the sumadockers, and I will be able to remove the repository we have for that.

At last! :-D

**Pull request merged**
