### PR TITLE
Migrate `manager` and related

### PR DESCRIPTION
**Pull request by Etheryte**
## What does this PR change?

This PR combines the remaining migration PRs into one behemoth. This is a three-way rebase of:

 - https://github.com/uyuni-project/uyuni/pull/3745
 - https://github.com/uyuni-project/uyuni/pull/3746
 - https://github.com/uyuni-project/uyuni/pull/3764

This branch can be used to test and run tests on the full set of changes to check for any regressions between the branches.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Part of https://github.com/SUSE/spacewalk/issues/13741

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Etheryte** [comment]
@jordimassaguerpla This is the Typescript migration PR that I mentioned previously. Since this touches a lot of core components it would be great to just run this against all scopes, if that's possible please.

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla This is the Typescript migration PR that I mentioned previously. Since this touches a lot of core components it would be great to just run this against all scopes, if that's possible please. This has been rebased against master today so the test results will be readily comparable.

ci#291

**Comment by jordimassaguerpla** [comment]
Hi @Etheryte !
Unfortunately :cry: 13 tests failed while in master only 5 do, so this might indicate your PR is causing those extra 8 failures.
Could you please check the results of the tests?
Thanks

[0] ci#Manager/view/Uyuni/job/uyuni-master-dev-acceptance-tests-NUE/1572/
[1] ci#view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/293

**Comment by jordimassaguerpla** [comment]
Hi @Etheryte !

Unfortunately 2 end-to-end tests fail:


```

20:14:58  Failing Scenarios:
20:14:58  cucumber features/core/proxy_register_as_minion_with_script.feature:43 # Scenario: Copy the keys and configure the proxy
20:14:58  cucumber features/core/proxy_register_as_minion_with_script.feature:49 # Scenario: Check proxy system details
```

However, these 2 also fail for master branch, which may indicate your code is good.

Bad news is that we could not run the secondary tests, given the tests that fail are part of the core testing.

ci#/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/307/
ci#/view/Manager/view/Uyuni/job/uyuni-master-dev-acceptance-tests-NUE/1600/

**Comment by Etheryte** [comment]
@jordimassaguerpla Thanks a lot for taking the time to check this out, I appreciate it greatly. I think I've ironed out all the kinks so hopefully the results will also match master when those failures get fixed there. This branch is straight rebasable so I can give it another go once that's the case, thanks for your help. 👍

**Comment by Etheryte** [comment]
@jordimassaguerpla Given master is unlocked, I assume the test runner might be functional again now? If that's the case, would it please be possible to rerun this against the full suite. The branch is freshly rebased with master.

@cbbayburt If you have the time to review this at some point that would be great, since getting this wrapped up unlocks a lot of other PRs that are waiting on these changes.

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla Given master is unlocked, I assume the test runner might be functional again now? If that's the case, would it please be possible to rerun this against the full suite. The branch is freshly rebased with master.
> 
> @cbbayburt If you have the time to review this at some point please that would be great, since getting this wrapped up unlocks a lot of other PRs that are waiting on these changes.

sure! I am actually waiting for the ci to be available. Seems there is some maintenance going on , but I expect this to be fixed shortly and then we can run this one.

**Comment by jordimassaguerpla** [comment]
@Etheryte Acceptance tests are being run on your code. We have selected all the secondary tests, so expect results in 6-7 hours.

CI/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/350/

**Comment by jordimassaguerpla** [comment]
Hi @Etheryte !

Seems there is an issue when trying to build the spacewalk-web package with the code from your PR:

https://build.opensuse.org/package/live_build_log/systemsmanagement:Uyuni:Master:PR:3793/spacewalk-web/openSUSE_Leap_15.3/x86_64

Could you take a look?

thanks

**Review by cbbayburt — APPROVED** [review]
I ignored the automatically migrated parts, and the other additions look nice and clean :+1:

**Comment by Etheryte** [comment]
Due to the branch freeze approaching, I'm going to go ahead and merge this. The test runner seems to be having issues right now sadly, this way there will be a few spare days to find and address issues if any should arise. This PR is pretty difficult to drag along with master updates and I wouldn't want to do this for one more branch freeze.

**Pull request merged**
