### PR TITLE
Replace mock

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

Replace python-mock with built-in unittest.mock

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by agraul — APPROVED** [review]
I had a quick look and I could not find any Python 2 test invocation (which would require `python-mock` afaik). The change is fine for me, thanks!

**Comment by agraul** [comment]
Another small thing, IMO we don't need to add changelog entries for such changes. RPM consumers probably don't care if we change out our test dependencies

**Comment by sbluhm** [comment]
Done

**Comment by sbluhm** [comment]
@agraul , can you please merge this one? Thank you.

**Pull request merged**
