### PR TITLE
Remove the /var/log/rhn/tasko/* files

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Follow up of https://github.com/uyuni-project/uyuni/pull/6586

Move every taskomatic task log to the rhn_taskomatic_daemon.log as this makes it hard to find problems.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes
- [X] **DONE**

## Test coverage
- No tests: code removal
- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]
LGTM

**Review by renner — APPROVED** [review]
Thank you Cedric, it looks good. No objections, I don't think that the current UIs are showing the repo sync details in case of errors, so it should be okay to remove.

**Comment by mcalmer** [comment]
@cbosdo don't forget this. Also backport to 4.3

**Comment by cbosdo** [comment]
> @cbosdo don't forget this. Also backport to 4.3

Yes, working on it ATM

**Pull request merged**
