### PR TITLE
Backport of #7170 #7180 #7188 and tagging

### PR DESCRIPTION
**Pull request by deneb-alpha**
## What does this PR change?

**Backport of #7170 #7180 #7188 and tagging**

## Links

Related https://github.com/SUSE/spacewalk/issues/20419
Related https://github.com/SUSE/spacewalk/issues/21856

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by deneb-alpha** [comment]
@cbosdo / @keichwa looking at the merge conflict  I'm wondering if there's more to cherrypick on `Uyuni-2023.04` and backport after tagging on master.

Could  you please help me with this?

**Comment by cbosdo** [comment]
> @cbosdo / @keichwa looking at the merge conflict I'm wondering if there's more to cherrypick on `Uyuni-2023.04` and backport after tagging on master.
> 
> I think I'll also need a backport to `Uyuni-2023.04` of #7030. It looks to me that [a3863f1](https://github.com/uyuni-project/uyuni/commit/a3863f149c72a6e73eb4c1746a5a17c7b51546c9) is the commit that (to my understanding) is introducing the merge conflict. But I'll need your help
> 
> Could you please help me with this?

I'm on the way back home and will have vacation tomorrow and next week. Better find someone else for such an urgent task. And you got the wrong Karl: @Etheryte

**Comment by deneb-alpha** [comment]
> > @cbosdo / @keichwa looking at the merge conflict I'm wondering if there's more to cherrypick on `Uyuni-2023.04` and backport after tagging on master.
> > I think I'll also need a backport to `Uyuni-2023.04` of #7030. It looks to me that [a3863f1](https://github.com/uyuni-project/uyuni/commit/a3863f149c72a6e73eb4c1746a5a17c7b51546c9) is the commit that (to my understanding) is introducing the merge conflict. But I'll need your help
> > Could you please help me with this?
> 
> I'm on the way back home and will have vacation tomorrow and next week. Better find someone else for such an urgent task. And you got the wrong Karl: @Etheryte

Actually was the autocomplete from github fooling me. I was suppose to tag @lucidd because he made the  PR for the missing fix.

**Comment by mackdk** [comment]
Not sure to fully understand your workflow here, but the pull request https://github.com/uyuni-project/uyuni/pull/7030 is already on master. The conflicts is because https://github.com/uyuni-project/uyuni/pull/7189/commits/af2bdad2ae9a253cefd2de897c862300c6e9ba27 is based on an older version of the `SessionSwap` class (the one from 4.3). So that commit needs to be adapted while merging.

**Review by juliogonzalez — APPROVED** [review]
Backport LGTM

**Comment by deneb-alpha** [comment]
> warning No changelog entry has been added. @deneb-alpha, please add necessary changelog entries with an additional PR.

for future readers... the changelog entries are available. this PR is a backport of changes from the MU branch and related tagging.

**Comment by juliogonzalez** [comment]
> for future readers... the changelog entries are available. this PR is a backport of changes from the MU branch and related tagging.

Right, but I wonder with the GitHub action failed. Did you talk to the author?

**Pull request merged**
