### PR TITLE
Cleaning of spacewalk-java.spec/susemanager.spec/spacewalk-setup.spec

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?
spacewalk-java:
- Cleanup of spacewalk-java file to reduce complexity.
- Remove glassfish-jaxb-core requirement for Enterprise Linux.
- Update package requirement libtcnative-1-0 to tomcat-native to have common name between EL and SUSE.

spacewalk-setup:
- Corrected tomcat installation requirement.

susemanager.spec
- Ensure installation of make for building. Build might fail (does fail on copr) otherwise.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests" (Test skipped, there are no changes to test)

### CODE REVIEW

**Comment by sbluhm** [comment]
@mcalmer may I have this one please?

**Review by mcalmer — APPROVED** [review]
LGTM, but master is currently locked

**Comment by juliogonzalez** [comment]
> LGTM, but master is currently locked

I see you added `merge-candidate`, but FMPOV it can wait until 2023.04 is out (hopefully this week).

I will add this PR to the list of PRs to be merged after the release, and before we unfreeze.

**Comment by sbluhm** [comment]
ok, if it won't make 04.2023 anymore, then I guess there is no urgency anymore then. Was just hoping to get it squeezed in to have a good baseline.

**Comment by juliogonzalez** [comment]
> ok, if it won't make 04.2023 anymore, then I guess there is no urgency anymore then. Was just hoping to get it squeezed in to have a good baseline.

We blocked the branch, to prepare 2023.04 ASAP, so for now we are only merging things that are required to fix important problems (mostly blockers)

**Comment by deneb-alpha** [comment]
@sbluhm could you please look at the conflicts?

**Comment by deneb-alpha** [comment]
> @sbluhm could you please look at the conflicts?

I directly fixed the conflict

**Comment by deneb-alpha** [comment]
@sbluhm hello :) 

I left you a comment on Gitter, but I'm not sure if you saw it.  

Could you please clarify  some of  the changes you made in this PR?

* The tile mentions only `spacewalk-java.spec/susemanager.spec`, but you also edited `spacewalk-setup.spec`
* the description mentions fixes for make, but you also `Corrected tomcat requirement` on `spacewalk-setup`, and you mentioned  `Simplify Java package dependencies` in `spacewalk-java`.

As a side note, for `spacewalk-java` I also have some clean-up to do, switching `gnu-jaf`/`jaf` directly to `glassfish-activation-api`. Before maging this  change I would also  like to clarify with you this part and avoid to introduce more merge conflicts

**Comment by sbluhm** [comment]
@deneb-alpha , thank you for informing me on your message!
The PR scope increased a bit after i found some small changes to fix but I never updated the description. I have done so now.

Do feel free to do these changes. If required, I will re-align any Enterprise Linux requirements ideally on package side. Only important change to me to remove
[`BuildRequires:  glassfish-jaxb-core`](https://github.com/uyuni-project/uyuni/pull/6825/files#diff-2de3ee26fbb18696208de9203d6937cc7551c86324f208e4dee716f4d43cf874L158)

[`Requires:       libtcnative-1-0`](https://github.com/uyuni-project/uyuni/pull/6825/files#diff-2de3ee26fbb18696208de9203d6937cc7551c86324f208e4dee716f4d43cf874L243)

[`Requires:       glassfish-jaxb-core
Requires:       jakarta-activation
Requires:       jaxb-api`](https://github.com/uyuni-project/uyuni/pull/6825/files#diff-2de3ee26fbb18696208de9203d6937cc7551c86324f208e4dee716f4d43cf874L254-L256)

`tomcat-native`

**Review by deneb-alpha — APPROVED** [review]
LGTM

**Review by juliogonzalez — APPROVED** [review]

**Pull request merged**
