### PR TITLE
change jar versions in ivy configuration file

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

ivy update - The big java update was now also released to Leap.
Some packages changed the repo, so we need to update obs-to-maven config as well.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Port of https://github.com/SUSE/spacewalk/pull/20806

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by jordimassaguerpla — APPROVED** [review]

**Review by jordimassaguerpla — CHANGES_REQUESTED** [review]
Hi! I just realized the java test fails with `suse#httpclient-4.5.6` not found. Could it be we need to wait a bit more?

**Comment by mcalmer** [comment]
> Hi! I just realized the java test fails with `suse#httpclient-4.5.6` not found. Could it be we need to wait a bit more?

No, I changed a bit too much .... fixing.

**Review by jordimassaguerpla — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
thanks @mcalmer . I see tests pass now. :+1:

**Comment by srbarrios** [comment]
Could we have duplicated java classes inside the classpath?

I have this error now when using JaCoCo tool that did not happened before:
```
12:41:16  FAIL: java -jar /tmp/jacococli.jar report /tmp/jacoco-allcli_sanity.exec  --xml /srv/www/htdocs/pub/jacoco-allcli_sanity.xml  --classfiles /srv/tomcat/webapps/rhn/WEB-INF/lib returned status code = 1.
12:41:16  Output:
12:41:16  [INFO] Loading execution data file /tmp/jacoco-allcli_sanity.exec.
12:41:16  Exception in thread "main" java.io.IOException: Error while analyzing /srv/tomcat/webapps/rhn/WEB-INF/lib/log4j_log4j-api.jar@org/apache/logging/log4j/util/Base64Util.class.
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:157)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:193)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeZip(Analyzer.java:265)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:196)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:226)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
12:41:16  at org.jacoco.cli.internal.commands.Report.analyze(Report.java:110)
12:41:16  at org.jacoco.cli.internal.commands.Report.execute(Report.java:84)
12:41:16  at org.jacoco.cli.internal.Main.execute(Main.java:90)
12:41:16  at org.jacoco.cli.internal.Main.main(Main.java:105)
12:41:16  Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/apache/logging/log4j/util/Base64Util
12:41:16  at org.jacoco.cli.internal.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer$1.visitEnd(Analyzer.java:99)
12:41:16  at org.jacoco.cli.internal.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
12:41:16  at org.jacoco.cli.internal.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
12:41:16  at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:725)
12:41:16  at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:401)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
12:41:16  ... 10 more
12:41:16  (RuntimeError)
```

**Pull request merged**
