### PR TITLE
QE: Cleanup deprecated files

### PR DESCRIPTION
**Pull request by nodeg**
## What does this PR change?

This will

- remove old/deprecated files related to Travis (discussed with @srbarrios and @Bischoff yesterday)
- updates our test suite `.gitignore` file

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- No tests: already covered

- [x] **DONE**

## Links

- Manager 4.3: https://github.com/SUSE/spacewalk/pull/18854
- Manager 4.2: https://github.com/SUSE/spacewalk/pull/18855
- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by Bischoff — APPROVED** [review]
fine with me, but i would have understood if you wanted to resurrect them

**Comment by nodeg** [comment]
I saved those 2 files locally and will try something with GitHub Actions in the future. I already created a [card](https://github.com/SUSE/spacewalk/issues/18835) for this.

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
> I saved those 2 files locally and will try something with GitHub Actions in the future. I already created a [card](https://github.com/SUSE/spacewalk/issues/18835) for this.

You can also find them in Manager-4.1, 4.0, 3.2, 3.1.. :trollface:

**Comment by nodeg** [comment]
I would backport only to 4.3 and 4.2 since 4.1 will be "gone" in October :wink:

**Pull request merged**
