### PR TITLE
Debian-11-Java-enablement

### PR DESCRIPTION
**Pull request by Shirocco88**
## What does this PR change?

Debian 11 Java enablement

## Fixes
https://github.com/uyuni-project/uyuni/issues/4118

### CODE REVIEW

**Comment by Shirocco88** [comment]
@juliogonzalez :
This files should be adapted:

susemanager-sync-data/additional_products.json
java/code/src/com/suse/manager/reactor/utils/test/productdata/additional_products.json
testsuite/features/build_validation/add_custom_repositories/srv_common_channels.feature

**Comment by mcalmer** [comment]
JFYI: `additional_products.json` is generated and has only an effect in SUSE Manager. Uyuni does not use it. We will take care of it as soon as we decide to add Debian 11 to SUSE Manager.
"build validation" is owned by our QA. It is ok to keep it unchanged for now.

**Comment by Shirocco88** [comment]
@mcalmer :
thanks for your comment;
please let me know, if there is anything I can help to add Debian11 to next uyuni release.

**Comment by Shirocco88** [comment]
@mcalmer : I've separated the files for QA/Testsuite to PR https://github.com/uyuni-project/uyuni/pull/4182 "Add-Debian-11-to-QA-testsuit" and gave permissions to my repo:branch to maintainers.

I think it is now easier to review and merge this PR.

**Comment by juliogonzalez** [comment]
For whoever is going to continue on this PR, I think more stuff will be needed. For reference, you can have a look at the PR I did for Rock Linux 8: https://github.com/uyuni-project/uyuni/pull/3959

I think we still need to add more stuff for the OS detection, maybe some changes for the DB to identify the provider (I seem to remember the Debian11 GPG key is different), etc.

But for now, the basic support is already available at https://github.com/uyuni-project/uyuni/pull/4122, and will be part of the first Uyuni release next year.

**Comment by juliogonzalez** [comment]
@rjmateus I think we don't need this one anymore, right?

**Comment by rjmateus** [comment]
@juliogonzalez nop, we don't need it anymore. 
Thanks for the contribution @Shirocco88

**Pull request closed without merging**
