### PR TITLE
Add RHEL channels to spacewalk-common-channels

### PR DESCRIPTION
**Pull request by lumarel**
## What does this PR change?

This PR adds the RHEL 7, 8 and 9 pool and tools channels to the spacewalk-common-channels.
We talked on Matrix/Gitter 2 months ago about that.
And this is the part which has to be changed for the application itself, the rest of changes will happen in the documentation.

## Documentation
- ~~No documentation needed: **add explanation. This can't be used if there is a GUI diff**~~
- ~~No documentation needed: only internal and user invisible changes~~
- ~~Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for ~~community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).~~
- ~~API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.~~
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/2157)

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by deneb-alpha** [comment]
@lumarel for info: I added an extra review for myself because there are some extra check to be done on the related  PR for the documentation.

sorry for the delay

**Comment by lumarel** [comment]
@deneb-alpha No worries, just thank you for taking a look, good to know I won't have to rebase a few more times anymore 🙂

**Comment by lumarel** [comment]
@deneb-alpha Will this be merged before the change to the new changelog format?
If not I'm going to update this PR 🙂

**Comment by deneb-alpha** [comment]
> @deneb-alpha Will this be merged before the change to the new changelog format? If not I'm going to update this PR slightly_smiling_face

I'll finish to review later today. :)

**Review by deneb-alpha — APPROVED** [review]
LGTM

**Comment by lumarel** [comment]
@deneb-alpha Thank you very much!
Here is the needed rebase 🙂

**Comment by agraul** [comment]
@lumarel just a small note for your next PR, please use a `-` for changelog entries :)

**Comment by lumarel** [comment]
Hey @agraul thank you for the note! Tbh this PR is just so old that all changelog entries had '*' back then, and I unfortunately didn't look closely enough on the rebase ^^
But yes, will follow the standard the next time,
next time with the new changelog format! (woohoo)

**Pull request merged**
