### PR TITLE
Scope off all Bootstrap 3 styles

### PR DESCRIPTION
**Pull request by Etheryte**
## What does this PR change?

The first step for migrating the core theme is to scope off the whole existing theme based on a class name. This means that we can toggle between themes without navigation flicker and it also means we can then do the same for Bootstrap 5 and Bob's your uncle.
This PR includes a lot of minor adjustments to make this work and also some changes to prepare for Bootstrap 5. (Actually I already have the Bootstrap 5 stuff since I worked on them in tandem, but I cherry-picked that out so this monster PR is easier to review.)

## GUI diff

Lots of small differences everywhere, hopefully I didn't break anything big.

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by Etheryte** [comment]
Note to self: do NOT squash this branch when merging it, the history has stuff we need laster.

**Comment by Etheryte** [comment]
Ping @lucidd @parlt91 @cbbayburt have you had time to have a look at this by any chance?

**Comment by jordimassaguerpla** [comment]
Hi ! We fixed a spelling mistake in the name of the tests and you will have to rebase your PR for the correct tests to run. Sorry for the inconvenience.

**Review by lucidd — APPROVED** [review]

**Comment by Etheryte** [comment]
Ping @parlt91 @cbbayburt, would you please have some time to have a look at this at some point?

**Pull request merged**
