### PR TITLE
Remove duplicated and stale query

### PR DESCRIPTION
**Pull request by ncounter**
## What does this PR change?

Simply get rid of a duplicated and stale query.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- No tests

- [x] **DONE**

## Links

Fixes #
Tracks #

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@ncounter should I merge this for the upcoming uyuni release and Beta1?

**Comment by ncounter** [comment]
> @ncounter should I merge this for the upcoming uyuni release and Beta1?

@juliogonzalez yes please. It does not fix anything and it is completely harmless but, "the sooner the better" to uncover possible implications :)

**Comment by juliogonzalez** [comment]
> "the sooner the better" to uncover possible implications :)

Meaning you are happy to work on this as P1 if it breaks Uyuni? Otherwise we better wait until the release is out.

**Comment by juliogonzalez** [comment]
Since this is not bugfixing nor a new feature, let's wait until the release is out, then we merge.

**Pull request merged**
