### PR TITLE
Remove Debian 9 unsupported client

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

Remove CentOS 6 and Debian 9 (the first 3 are not affected in this specific PR)

## Links

Issue: https://github.com/SUSE/spacewalk/issues/20607

Ports:
4.2: https://github.com/SUSE/spacewalk/pull/20630
4.3: https://github.com/SUSE/spacewalk/pull/20629

## Changelogs

- [x] No changelog needed

### CODE REVIEW

**Review by srbarrios — COMMENTED** [review]
I can only see Debian 9 removed, this PR still a draft?
If so, please convert to a draft so we are not notified.

**Comment by Bischoff** [comment]
> I can only see Debian 9 removed,

That's correct there are no occurrences of the other ones.


> this PR still a draft? If so, please convert to a draft so we are not notified.

No it's ready for proofreading, i'm doing last tests now.

**Review by ktsamis — APPROVED** [review]

**Review by srbarrios — APPROVED** [review]
Please re-title the PR, to mention that only Debian 9 was removed.

**Review by nodeg — APPROVED** [review]
LGTM.

**Comment by Bischoff** [comment]
> Please re-title the PR, to mention that only Debian 9 was removed.

it's in the description now

**Review by elariekerboull — APPROVED** [review]

**Pull request merged**
