### PR TITLE
JS: stop using global validator

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Using the statically linked validator library and the corresponding global variable makes it too painfull to test components depending on it.

In order to address the issue, move the validator as a yarn-managed dependency and use proper imports.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: would help testing later

- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by cbosdo** [comment]
This also means `validator.js` could be removed from the `susemanager-frontend-libs` package.

**Comment by Etheryte** [comment]
This looks good to me and a very nice thing to clean up while you're working on other things. 👍  

I'll let Can have the final call since I'm not familiar with the history behind this.

**Review by Etheryte — APPROVED** [review]

**Review by parlt91 — APPROVED** [review]
I like it very nice. Thanks :smiley:

**Review by cbbayburt — APPROVED** [review]
Subtle but great improvement :+1:

**Comment by cbosdo** [comment]
SR for the validator.js removal in the `susemanager-frontend-libs` package in Uyuni: https://build.opensuse.org/request/show/875432

**Pull request merged**
