### PR TITLE
Revert c37882bc435bea1c147ca416e609398290c69748

### PR DESCRIPTION
**Pull request by ktsamis**
## What does this PR change?

Reverts c37882bc435bea1c147ca416e609398290c69748 because it broke uyuni and head testsuites. 

Before (with printing the keyId and issuerKeyId and subject for debugging):
```
uyuni-master-srv:~ # /usr/bin/rhn-ssl-tool --gen-server --no-rpm --cert-expiration=3650 --set-org=SUSE --set-org-unit=SUSE --password=spacewalk --set-city=Nuernberg --set-email=uyuni@mgr.suse.de --dir=/root/ssl-
build-fubar --set-state=Bayern --set-hostname=uyuni-master-srv.mgr.suse.de --set-country=DE                                                                                                                        
                                                                                                                                                                                                                   
Generating the web server's SSL private key: /root/ssl-build-fubar/uyuni-master-srv.mgr/server.key                                                                                                                 
                                                                                                                                                                                                                   
Generating web server's SSL certificate request: /root/ssl-build-fubar/uyuni-master-srv.mgr/server.csr                                                                                                             
Using distinguished names:                                                                                                                                                                                         
    --set-country      = "DE"                                                                                                                                                                                      
    --set-state        = "Bayern"                                                                                                                                                                                  
    --set-city         = "Nuernberg"
    --set-org          = "SUSE"
    --set-org-unit     = "SUSE"
    --set-hostname     = "uyuni-master-srv.mgr.suse.de"
    --set-email        = "uyuni@mgr.suse.de"
Rotated: rhn-ca-openssl.cnf --> rhn-ca-openssl.cnf.1 

Generating/signing web server's SSL certificate: server.crt
uyuni-master-srv:~ # /usr/bin/mgr-ssl-cert-setup --root-ca-file=/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT --server-cert-file=/root/ssl-build-fubar/uyuni-master-srv.mgr/server.crt --server-key-file=/root/ssl-build
-fubar/uyuni-master-srv.mgr/server.key -c                                                                 
C0:0E:AF:F3:61:18:22:08:5B:3A:B8:2B:C3:FF:F3:51:C4:D2:6D:04
SERIAL:3D:A3:21:CD:75:6B:63:77:61:C3:05:C6:45:C0:DC:63:E2:C6:1E:F3
C = DE, ST = Bayern, O = SUSE, OU = SUSE, CN = uyuni-master-srv.mgr.suse.de, emailAddress = uyuni@mgr.suse.de

ERROR: Incomplete CA Chain. Key Identifiers do not match. Unable to find issuer of 'C = DE, ST = Bayern, O = SUSE, OU = SUSE, CN = uyuni-master-srv.mgr.suse.de, emailAddress = uyuni@mgr.suse.de'
```

After this fix:

```
uyuni-master-srv:~ # /usr/bin/rhn-ssl-tool --gen-server --no-rpm --cert-expiration=3650 --set-org=SUSE --set-org-unit=SUSE --password=spacewalk --set-city=Nuernberg --set-email=uyuni@mgr.suse.de --dir=/root/ssl-build-fubar --set-state=Bayern --set-hostname=uyuni-master-srv.mgr.suse.de --set-country=DE

Generating the web server's SSL private key: /root/ssl-build-fubar/uyuni-master-srv.mgr/server.key
Rotated: server.key --> server.key.1
Rotated: rhn-server-openssl.cnf --> rhn-server-openssl.cnf.1

Generating web server's SSL certificate request: /root/ssl-build-fubar/uyuni-master-srv.mgr/server.csr
Using distinguished names:
    --set-country      = "DE"
    --set-state        = "Bayern"
    --set-city         = "Nuernberg"
    --set-org          = "SUSE"
    --set-org-unit     = "SUSE"
    --set-hostname     = "uyuni-master-srv.mgr.suse.de"
    --set-email        = "uyuni@mgr.suse.de"
Rotated: server.csr --> server.csr.1

Generating/signing web server's SSL certificate: server.crt
Rotated: server.crt --> server.crt.1
uyuni-master-srv:~ # /usr/bin/mgr-ssl-cert-setup --root-ca-file=/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT --server-cert-file=/root/ssl-build-fubar/uyuni-master-srv.mgr/server.crt --server-key-file=/root/ssl-build-fubar/uyuni-master-srv.mgr/server.key -c
C0:0E:AF:F3:61:18:22:08:5B:3A:B8:2B:C3:FF:F3:51:C4:D2:6D:04
C0:0E:AF:F3:61:18:22:08:5B:3A:B8:2B:C3:FF:F3:51:C4:D2:6D:04
C = DE, ST = Bayern, O = SUSE, OU = SUSE, CN = uyuni-master-srv.mgr.suse.de, emailAddress = uyuni@mgr.suse.de
```



## GUI diff

No difference.


- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes no issue directly from testsuite review
Tracks no other PR, only on master this was changed before.

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)


## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [x] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
Let me have a look.

**Comment by sbluhm** [comment]
Do you have a timeline for the revert? Otherwise I would like to analyse this further this evening and try to submit a fix by tomorrow.

**Comment by ktsamis** [comment]
> Do you have a timeline for the revert? Otherwise I would like to analyse this further this evening and try to submit a fix by tomorrow.

The fix works because I tried locally in uyuni and it passed after the fix. I need to merge today to have the testsuites run by tomorrow. If you want to take another look and add openssl 3 functionality without breaking the cert generation, you can do it while the testsuites are running with the revert. So you can take all the time you need after I merge :)

**Comment by admd** [comment]
> Do you have a timeline for the revert? Otherwise I would like to analyse this further this evening and try to submit a fix by tomorrow.

Thank you Stefan for taking a look. We will revert it back soon to allow our test suits to run. However, we can then create an issue to discuss the matter further. This will enable you to thoroughly analyze the situation and together we can devise a better solution, taking into account any potential edge cases that may not be covered by this reversion. 

Would that be ok with you?

**Comment by sbluhm** [comment]
Sure sounds good! Go ahead.

**Comment by admd** [comment]
@sbluhm I have created this issue https://github.com/uyuni-project/uyuni/issues/7202 for tracking . Feel free to assign it to yourself.

**Comment by sbluhm** [comment]
Can you actually assign it to me? I don't have rights to do so. Thank you.

**Pull request merged**
