### PR TITLE
make autoinstallation provisoning compatible with GRUB and ELILO in addition to GRUB2 only

### PR DESCRIPTION
**Pull request by vzhestkov**
## What does this PR change?

Makes autoinstallation provisioning working for the systems using GRUB and ELILO bootloaders.
GRUB and ELILO are used in SLES 11 SP4 (ELILO is installed by default for UEFI systems)

## GUI diff

No difference.

## Documentation
- No documentation needed: only internal and user invisible changes

## Test coverage
- No tests

## Links

Tracks https://github.com/SUSE/spacewalk/pull/13003

## Changelogs

- make autoinstallation provisoning compatible with GRUB and ELILO
  in addition to GRUB2 only

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]
I just expect that you tested both new types.

**Comment by vzhestkov** [comment]
@mcalmer , Sure. I've tested not just new types, but also original GRUB2 in 2 variations (EFI & Legacy). And the reporter of the bug also confirmed the solution.

**Comment by mcalmer** [comment]
@vzhestkov any reason why this is not merged yet?

**Comment by vzhestkov** [comment]
@mcalmer Sorry, no any reason, I just don't know all of the processes yet.

**Pull request merged**
