### PR TITLE
Added missing make build requirements

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

Added "make" as build requirement for some packages.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]
LGTM

**Comment by mcalmer** [comment]
adding @juliogonzalez also for merging this. Maybe he need changelog entries.

**Comment by juliogonzalez** [comment]
> Added "make" as build requirement for some packages.

Well, I read at the PR desc `Added "make" as build requirement for some packages.`, but for the changelog I'd like to have a real reason. Is it because `make` is not preinstalled in some OS such as Alma9?


What I did for other package was adding:
```
- Add make as a BuildRequire for those operating systems that do
  not have it installed by default
```
Does this correctly explain the situation, @sbluhm ?

**Comment by sbluhm** [comment]
@juliogonzalez as far as I understand, `make` is also not installed by default on Leap. It seems that it gets pulled in by some other package. most likely `rpm-build`. This does not seem to be the case for Enterprise Linux 9.
As `make` is a build requirement for either OS, I would not make it a conditional statement as it is a bulid requirement. In my opinion a statement like the following would be more true:
`- Ensure installation of make for building`

Now making my comment long :)
I am still a bit confused on when to add a changelog entry and when not. As far as I understand, this change has no interest to any end user. It doesn't change any functionality. Probably one of the most minimum changes possible.
Based on that, I intentionally skipped the changelog entry. I am happy to add them if required. Just trying to do the right thing :)

**Comment by juliogonzalez** [comment]
> @juliogonzalez as far as I understand, `make` is also not installed by default on Leap. It seems that it gets pulled in by some other package. most likely `rpm-build`. This does not seem to be the case for Enterprise Linux 9. As `make` is a build requirement for either OS, I would not make it a conditional statement as it is a bulid requirement. In my opinion a statement like the following would be more true: `- Ensure installation of make for building`

ACK, I will use that.

> Now making my comment long :) I am still a bit confused on when to add a changelog entry and when not. As far as I understand, this change has no interest to any end user. It doesn't change any functionality. Probably one of the most minimum changes possible. Based on that, I intentionally skipped the changelog entry. I am happy to add them if required. Just trying to do the right thing :)

Well, what you did is usually right. Problem is that some packages usually do not change at all between releases, and in such cases we need a changelog entry so we can tag.

Usually you can figure that out by checking when was the last time we tagged it, or if the last tagging contained a comment about translations only.

And in general, the traditional packages are not maintained anymore, even if we still did not remove then, so those would require a changelog entry for sure (we'll remove it at some point in the future)

**Comment by juliogonzalez** [comment]
In any case, do not add changelogs now, I will handle it.

**Pull request merged**
