### PR TITLE
Ivy cleanup and update of dependency versions

### PR DESCRIPTION
**Pull request by renner**
## What does this PR change?

This is an attempt to update the ivy file and the corresponding jar repository to the latest versions of libraries as we take some of them from `SLE15 SP1`. Some further effort might be needed to bring this to `Leap 15.1`.

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed, this is only relevant for developers and CI systems.

- [x] **DONE**

## Test coverage

- No tests needed, this is only relevant for developers and CI systems.

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/7026.

- [x] **DONE**

## Changelogs

Copy the following sentence as a new comment if you don't need changelog entries:

> gitarro no changelog needed !!!

If the test `changelog_test`already run, then add another new comment with the following text:

> gitarro rerun changelog_test !!!

### CODE REVIEW

**Comment by renner** [comment]
gitarro no changelog needed !!!

**Comment by renner** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by renner** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by renner** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by renner** [comment]
@moio, @hustodemon and other reviewers, tests are green now, it would be very helpful if you could have a look here to help me with finding out why those jars were added and if we still need them:

https://github.com/uyuni-project/uyuni/pull/587/files#diff-6cc1362df8322552d5054d6d242eea61R117

For example, how do we use `ant` and `ant-junit` from the lib dir, don't we require those to be installed on the system where we are running the tests? Let me know if there is a use case and we can add those back.

**Comment by hustodemon** [comment]
I'd get rid of these:
- `ant` & `ant-junit` - we install those in the docker containers and as you said - if they are not installed, then pulling them via ivy does not work. I'd get rid of them for now.
- `cglib-nodep` - seems to be only used in `rhn-search`. and it looks like it's trying to reach an absolute path /usr/share/java/cglib-nodep.jar, not in the ivy target dir
- `gslib` and `jfreechart` - i couldn't find any usage whatsoever

For the rest I need to investigate a bit more.

**Comment by renner** [comment]
Thanks for your reviews! I would go with @hustodemon suggestion and tomorrow remove the jar files in question, merge the two ivy repositories (for testing I created a separate repo `ivy-head`) and finally this PR.

**Comment by moio** [comment]
Sorry, didn't have the time to review this. As pointed out, failure will be evident and easily fixable, so just go ahead without me

**Pull request merged**
