### PR TITLE
Python refactoring

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Move the backend, uyuni-commons and rhnlib code into a python-specific folder.
The actual source code of those packages is simply moved to a package structure that matches the one they have in the produced packages. Only the test code is changed in this PR.

### What do we gain from this?

* running the unit tests directly from the code, no need of a container any more
* pylint and all the python dev tools are now working out of the box. This will also make the code editor tooling more useful for the devs.
* Some cleanup

### Still to be done

* Go over the remaining tests in the code folders and figure out which to fix, keep and convert and which to drop. Those weren't executed by our CI before and may are sometimes in a really bad shape.
* Progressively convert the tests to pytest.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/11688

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by cbosdo** [comment]
This SR is not required to run the python unit tests, but I suspect it could be useful for others: https://build.opensuse.org/request/show/923454

**Review by mcalmer — CHANGES_REQUESTED** [review]
We need a discussion about this.
It will at least break the translation setup and I am not sure what consequeces it has for backporting and submission.

**Comment by cbosdo** [comment]
Partly fixes Fixes https://github.com/SUSE/spacewalk/issues/15190

**Comment by juliogonzalez** [comment]
I rejected the SRs. Please submit again when the PR is ready to be merged.

**Comment by cbosdo** [comment]
@agraul we need separate strings localiztion IIRC since 4.2 l10n is based on master strings

**Comment by agraul** [comment]
> @agraul we need separate strings localiztion IIRC since 4.2 l10n is based on master strings

What exactly do we need to change? While our wiki covers a lot of "how to translate", I haven't yet found out how the translations are set up especially wrt. the 4.2 <-> master relationship.

**Comment by cbosdo** [comment]
> > @agraul we need separate strings localiztion IIRC since 4.2 l10n is based on master strings
> 
> What exactly do we need to change? While our wiki covers a lot of "how to translate", I haven't yet found out how the translations are set up especially wrt. the 4.2 <-> master relationship.

That's the thing, but @mcalmer will correct me if my memory fails me, the localization for 4.2 uses the same strings than the master one.

**Comment by mcalmer** [comment]
@cbosdo when you plan to bring this in, we need to coordinate this with changes in weblate.

**Review by juliogonzalez — APPROVED** [review]
Changes at `rel-eng/packages` look good.

**Review by agraul — APPROVED** [review]
From my perspective this is great work! Thanks a lot for doing all of this, it will make our lives a lot easier going forward.

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
