### PR TITLE
Skip channels with no channel_family_id

### PR DESCRIPTION
**Pull request by brejoc**
## What does this PR change?

If you are triggering an import (`satellite-sync -m /var/spacewalk/export/`), then you might run into this error: `IntegrityError: null value in column "channel_family_id" violates not-null constraint`

This is coming from an `executemany()` that got values like this:

```
[[1913, 1811, 1919, None, 1787, 1937, 1745, 1856, 1781, 1748, 1928, 1832, 1946], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
```

The `None` here is causing the problem. With this PR we would skip that value pair.

## GUI diff

No difference.

## Documentation
- No documentation needed: only internal and user invisible changes

## Links

Was discovered after fixing this bug: https://bugzilla.suse.com/show_bug.cgi?id=1181274

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by brejoc** [comment]
@mcalmer Is this making sense to you or would the import be flawed because there was the `None` in the first place?

**Comment by mcalmer** [comment]
I would like to see the input data. 

```
    def preprocess(self):
        for item in self.batch:
            item['org_id'] = 1
            if item['system_entitlement'] == "0":
                families = {}
                families[item['label']] = None
                self.backend.lookupChannelFamilies(families)
                item['channel_family_id'] = families[item['label']]
                self._sub_data.append(item)
```

That input data should have a "label" which is evaluated to an ID. None can only happen when that family is not
in the DB. But AFAIK importing channel families is happening much earlier than importing subscriptions.

Do you have the input data and can check which subscription was not found?

**Comment by brejoc** [comment]
We have this as an input:

```
(Pdb) pp self._sub_data
[[<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1913, 'label': 'SLESMT', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1811, 'label': 'SLE-HAE-X86', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': None, 'label': 'SUSE', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1919, 'label': 'SMP', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1735, 'label': 'private-channel-family-1', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1787, 'label': 'SES', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1937, 'label': 'SUSE_CLOUD', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': None, 'label': 'nVidia', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1745, 'label': '7261', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1856, 'label': 'SLES12-GA-LTSS-X86', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1781, 'label': 'RES', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1748, 'label': 'AiO', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1928, 'label': 'SMS-X86', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1832, 'label': 'SLE-SDK', 'system_entitlement': '0', 'group_type': None}],
 [<spacewalk.server.importlib.importLib.SuseSubscription instance; attributes={'max_members': 0, 'org_id': 1, 'channel_family_id': 1946, 'label': 'WEBYAST', 'system_entitlement': '0', 'group_type': None}]]
```

**Review by mcalmer — APPROVED** [review]
Looks good. The case here is caused by removed product classes. We had them in the past but now they are unused and removed. I think it is safe to skip them

**Comment by brejoc** [comment]
Thanks!

**Comment by brejoc** [comment]
> warning The changelog has not been updated. Please update it @brejoc.

@github-actions bad bot!

**Pull request merged**
