### PR TITLE
Payg timer

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

For PAYG we need some data from the host available in the container.
This is a timer service which collect the data and write it into a volume which is used by the container

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/24209

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by vzhestkov — APPROVED** [review]
LGTM :+1:

**Review by mackdk — APPROVED** [review]
Looks good :+1: SonarCloud is [complaining about the camel case](https://sonarcloud.io/project/issues?id=uyuni-project_uyuni&pullRequest=8691&resolved=false&inNewCodePeriod=true) of the variables, if you want to fix it.

**Comment by mcalmer** [comment]
> Looks good 👍 SonarCloud is [complaining about the camel case](https://sonarcloud.io/project/issues?id=uyuni-project_uyuni&pullRequest=8691&resolved=false&inNewCodePeriod=true) of the variables, if you want to fix it.

Not now. I may fix it for the next version

**Review by deneb-alpha — APPROVED** [review]
LGTM

**Pull request merged**
