### PR TITLE
[WIP] Add 'create first user' functionality to xmlrpc API and spacecmd

### LINKED ISSUE #296: Add possibility to automate initial organization/user creation
**Is your feature request related to a problem? Please describe.**
I'm currently writing a Chef cookbook for automating Uyuni test deployments.
After installing Uyuni, the first organization still needs to be created using
the web page.

I understand that there is an automation tool `spacecmd`, but this seems not to
work if no organization or admin user exist:

```
# spacecmd org_create
Spacewalk Username:
Spacewalk Password:
ERROR: Invalid credentials
```

I figured out that entering no username/password does not work (*also not via
the `.spacecmd/config` file*) - so therefore the error message seems legit.

**Describe the solution you'd like**
It would be great if `spacecmd` would work without username/password for the first setup or supply a dedicated command for this, e.g. `spacecmd initial_setup`

**Describe alternatives you've considered**
As a workaround, I'm using `curl` to get the CSRF token and send a POST request to the appropriate script:

```
csrf="$(curl --insecure https://localhost/rhn/newlogin/CreateFirstUser.do |
grep csrf | grep -o 'value=.*' | tr -d 'a-zA-Z">=')"
curl --insecure -d
"csrf_token=$csrf&submitted=true&orgName=demoOrg&login=admin&desiredpassword=Mimimi01&desiredpasswordConfirm=Mimimi01&email=info@xxxxxxxxxxxx&firstNames=Paula&lastName=Pinkepank"
-X POST https://localhost/rhn/newlogin/CreateFirstUser.do
```

**Additional context**
See also the discussion on the mailing list: https://lists.opensuse.org/uyuni-devel/2018-11/msg00009.html

### PR DESCRIPTION
**Pull request by wombelix**
## What does this PR change?

Implements Feature Request https://github.com/uyuni-project/uyuni/issues/296 by adding functionality to `xmlrpc API` and `spacecmd` to create the first user / initial organization after finishing the Uyuni Server Setup.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/issues/1227
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [X] **DONE**

## Test coverage
- Unit tests were added

- [X] **DONE**

## Links

Fixes #296

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
This needs to get rebased against master to get new dependencies in. Otherwise the tests cannot run anymore.

**Review by SchoolGuy — APPROVED** [review]
So I took a look at the Python side and only glanced towards the Java Side. From my side I would love to have this in. A test would be nice but we only have a rudimentary test for login, so I don't see this as a requirement for merging.

However I would say that this needs a Cucumber Integration test since we don't want this to fail. But this can also be added in a later PR.

I did not test this PR myself.

**Comment by wombelix** [comment]
@mcalmer @SchoolGuy
Apologize that I left the PR untouched and was unresponsive for such long time.
I merged with the latest state of master and did some adjustments regarding the Java Tests.

Right now during init of the tests, there is already a new org created.
So for now I check if an Org with ID 1 already exist and only if not, the actual test of the new method createFirst will be performed.

I'm still quite new to the Uyuni Code Base and as far I can see there will be changes necessary at lot of different places to fully cover the new code into the tests.

Especially Cucumber tests are new to me and I still have a lot to learn about it first.

I would highly appreciate some guidance from you about the next steps and a possible way forward.

**Comment by mcalmer** [comment]
@wombelix I think this looks good so far. Would be good if you could rebase this PR against current master to fix the file conflicts. If you want you can also squash some of the commits to keep the git history clean. But we can also squash everything on merge.

I put this on the list to be merged after master gets unblocked.

**Review by mcalmer — APPROVED** [review]

**Review by thesp0nge — APPROVED** [review]
After reviewing the code I had a private slack talk with @renner, fora having a better understanding of the whole setup process to evaluate all risks.

The new API doesn't have an authentication mechanism. However, it's called by a python script from the same SUMA server and it is called by root.

Other subsequent calls are denied by the API itself.
The only attack scenario is when the attacker executes the python script before the legitimate root executes it as well.
In this scenario: a) server root can undo attacker's actions, simply removing the rogue SUMA organization b) there is no impact on minions, because the attacker can't jump on client servers asking to join SUMA without being noticed. The rogue admin could start registering systems obviously, in case he has SSH credentials to access them. If this happens, the attacker already compromised a huge amount of secrets.

We agreed that the new API is fine and it could be merged.

**Comment by agraul** [comment]
> The new API doesn't have an authentication mechanism. However, it's called by a python script from the same SUMA server and it is called by root.
> 

Please correct me if I'm wrong: as far as I know, `spacecmd` can be called from any system that can connect to the SUMA server's XMLRPC API.

**Comment by thesp0nge** [comment]
I had the incorrect assumption. My fault, sorry.
I think it's a tradeoff here, as most of the time. For sure, having an authenticated API with a token, created during installation and given to the user in output will be great.

On the other side let us assume the attacker feeds the initial org. What he can do next? If I understood correctly, there is no compromise menace. It's just a matter of re-installing the package. Is it correct?

**Comment by thesp0nge** [comment]
So even if my initial assumption was wrong we can say that at the moment there are no risks justifying spending time adding the authentication layer to this API. However, since it's a good practice, maybe we can track to add for all XMLRPC calls in the future.

**Comment by meaksh** [comment]
I've fixed the conflicts with the changelogs and will merge this PR as soon as tests are green. Thanks!

**Comment by wombelix** [comment]
Hey guys, thank you very much, glad the PR got accepted and was merged :)

**Pull request merged**
