### PR TITLE
CML: Filter Patches by type

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Filter patches by type:

- Product Enhancement Advisory
- Security Advisory
- Bug Fix Advisory

## GUI diff

Screenshot_20190812_103254

Screenshot_20190812_103450

- [x] **DONE**

## Documentation
- General doc update for CLM with new Filters needed. See other PRs.

- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/8984
Tracks 

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests" 		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by hustodemon** [comment]
LGTM. I even tried this out and it was working nice. One subjective style suggestion: what about using radio buttons for the advisory type specification? To me it'd look slighly better and it'd be a very simple code change (see below):

ss

```jsx
{
  filtersEnum.enum.ERRATUM_BYTYPE.key === props.filter.type &&
  <div className="row">
    <Radio
      name="advisoryType"
      defaultValue="Security Advisory"
      items={[
        {"label": t("Security Advisory"), "value": "Security Advisory"},
        {"label": t("Bug Fix Advisory"), "value": "Bug Fix Advisory"},
        {"label": t("Product Enhancement Advisory"), "value": "Product Enhancement Advisory"}
      ]}
      label={t("Advisory Type")}
      labelClass="col-md-3"
      divClass="col-md-6" />
  </div>
}
```

**Comment by mcalmer** [comment]
@hustodemon hmm, what about checkboxes and allow multiple selections. Like:

Deny: Bug Fix and Product Enhancement Advisories 

(AKA: only Security Advisories are allowed)

**Comment by hustodemon** [comment]
In theory this sounds great! It'd complicate backend logic though. I think the same can be achieved by combining simple filters (e.g. only single advisory type possible) with different rules (allow/deny).

**Comment by mcalmer** [comment]
@hustodemon I will sleep over it and decide tomorrow

**Comment by mcalmer** [comment]
@hustodemon I used the radio buttons

**Pull request merged**
