### PR TITLE
Fix: handle corner case of deb pkg compare version (bsc#1173201)

### PR DESCRIPTION
**Pull request by mbologna**
## What does this PR change?

Fix: handle corner case of deb pkg compare version (bsc#1173201)
    
Before, a wrong update request was notified:
    
Installed package version is:   fwupd-signed-1.27.1ubuntu1+1.3.9-4ubuntu0.1.amd64-deb
Proposed version to update is:  fwupd-signed-1.27+1.3.9-4.amd64-deb
   
This patch takes care of addressing corner case in Java and database

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: internal 

- [X] **DONE**

## Test coverage

- Unit AND database (!!!) tests were added

- [X] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/11789

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle" 
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql" 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Bischoff** [comment]
@lkotek, do you see how to verify this?

**Comment by mbologna** [comment]
> @lkotek, do you see how to verify this?

I manually installed the database patch on d201 QAM - and that would be enough for testing.

For the instruction to reproduce it, `reproducer:c0` in https://bugzilla.suse.com/show_bug.cgi?id=1173201 , but you already know that, right? ;)

**Comment by mbologna** [comment]
> Wrong schema migration filename. The next schema version is 4.1.10 and not 4.2.0

You are right. I fixed it. Thanks!

**Comment by mcalmer** [comment]
Java unit tests and schema migration test are failing. Needs to be checked

**Comment by juliogonzalez** [comment]
Looks to me the failed tests were some kind of infra problem, but I don't understand why.

**Comment by juliogonzalez** [comment]
@mbologna please amend and force push.

**Comment by lkotek** [comment]
> > @lkotek, do you see how to verify this?
> 
> I manually installed the database patch on d201 QAM - and that would be enough for testing.
> 
> For the instruction to reproduce it, `reproducer:c0` in https://bugzilla.suse.com/show_bug.cgi?id=1173201 , but you already know that, right? ;)

Yep, I know :-) I just tested it and your fix works just fine, thanks :-)

**Pull request merged**
