### PR TITLE
We test virtualization host enablement elsewhere

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

Fix small side effect of activation keys refactoring

We already test the virtualization enablement in the virtualization tests, no need to have it in core too.

## Links

Ports:
* 4.0: SUSE/spacewalk#13884
* 4.1: SUSE/spacewalk#13883

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
LGTM.

I just would love that we don't repeat tests like those checks:
```
    And I should see a "Details" link
    And I should see a "Packages" link
    And I should see a "Configuration" link in the content area
    And I should see a "Groups" link
    And I should see a "Activated Systems" link
```
But ok, not the scope of this PR.

**Comment by Bischoff** [comment]
> LGTM.
> 
> I just would love that we don't repeat tests like those checks:
> 
> ```
>     And I should see a "Details" link
>     And I should see a "Packages" link
>     And I should see a "Configuration" link in the content area
>     And I should see a "Groups" link
>     And I should see a "Activated Systems" link
> ```
> 
> But ok, not the scope of this PR.

OK, feel free to create a card to move them to secondary.

**Review by calancha — APPROVED** [review]
LGTM.

**Review by cbosdo — APPROVED** [review]
ran cucumber virtualization features locally with that change and tests passed, thanks!

**Pull request merged**
