### PR TITLE
Cobbler setup fix

### LINKED ISSUE #4165: Uyuni Bugreport - Uyuni Master 2021-08-25: spacewalk-setup-cobbler empties cobbler.conf
When running `spacewalk-setup-cobbler` (standalone or via mgr-setup), the program fails with `io.UnsupportedOperation: not readable`.
example:
```
# /usr/bin/spacewalk-setup-cobbler --apache2-config-directory /etc/httpd/conf.d
Cobbler modules:
/etc/cobbler/modules.conf
Apache Conf modules:
/etc/httpd/conf.d/cobbler.conf
Traceback (most recent call last):
  File "/usr/bin/spacewalk-setup-cobbler", line 124, in <module>
    main()
  File "/usr/bin/spacewalk-setup-cobbler", line 119, in main
    remove_virtual_host(HTTPD_CONFIG_DIRECTORY, COBBLER_HTTP_CONFIG)
  File "/usr/bin/spacewalk-setup-cobbler", line 97, in remove_virtual_host
    http_lines = http_config.readlines()
io.UnsupportedOperation: not readable
```

Checking on the file, it gets truncated.
Example:
Before running `spacewalk-setup-cobbler`:
```
# ll /etc/httpd/conf.d/cobbler.conf
-rw-r--r--. 1 root root 1243 25. Aug 21:26 /etc/httpd/conf.d/cobbler.conf
```
After running `spacewalk-setup-cobbler`
```
# ll /etc/httpd/conf.d/cobbler.conf
-rw-r--r--. 1 root root 0 25. Aug 21:30 /etc/httpd/conf.d/cobbler.conf
```

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

- Added Apache config folder to default rhn.conf.
- Removed hard coding of Apache config folder during setup.
- Fixed cobbler.conf truncation during setup.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

Fixes #4165 , #4163 

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
Can this PR please be merged?

**Comment by SchoolGuy** [comment]
@sbluhm In theory yes. I just don't have the time to test due to my other numerous tasks. I'll set a reminder for myself that I try to do so until the end of the week. If not I will try to find someone who can test.

**Comment by sbluhm** [comment]
Apologies, I misunderstood your previous comment.

**Comment by calancha** [comment]
@SchoolGuy Talking about this file:
https://github.com/uyuni-project/uyuni/blob/1aaf84f1dd8c606653b90f5bf04cf3c15695587a/spacewalk/setup/bin/spacewalk-setup-cobbler#L30

The old Perl script had a check for a missing  `/etc/httpd/`:
```
 # To be replaced by central configuration in future.
 my $HTTPCONFDIR = '/etc/httpd/';
 if (! -d $HTTPCONFDIR) {
     $HTTPCONFDIR = '/etc/apache2/';
 }
```

Shouldn't we add this check in the new Python script as well?
I see this in the Uyuni CI:
```
    File "/usr/bin/spacewalk-setup-cobbler", line 41, in backup_file
      copyfile(file_path, "%s.backup" % file_path)
    File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
      with open(src, \'rb\') as fsrc:
  FileNotFoundError: [Errno 2] No such file or directory: \'/etc/httpd/cobbler.conf\'
```

**Comment by calancha** [comment]
> @calancha , is this for the current master version or for my change? 

@sbluhm It's for the current master version.

> My change should cover this and get the config centrally from rhn.conf.
> (I put the change into perl to identify SUSE/Enterprise Linux 8 directories, not to actually do a verification.)

That's great! Then we must be OK. Thank you!

**Comment by SchoolGuy** [comment]
Great news! Today I will be able to test this. It will take a while since I need to set everything up but I will report once it is done.

**Comment by SchoolGuy** [comment]
So I now tested this PR now and it is good as far as I can see. I will merge this thus.

**Pull request merged**
