### PR TITLE
WIP - Better transitions between react pages in SPA - DelayedAsyncTransitionSurface

### PR DESCRIPTION
**Pull request by lneves12**
This depends on https://github.com/uyuni-project/uyuni/pull/1366 https://github.com/liferay/senna.js/pull/320 https://github.com/liferay/senna.js/pull/323

## What does this PR change?

Better transitions between react pages in SPA.

As the react render is done client-side whenever we transit to a page using React it's possible to visualize a white flicker, which happens due to the interval of removing the old page and React start rendering the new page.

This PR improves that navigation keeping the old page until the React of the next page is done with the first render. This improves a lot the smoothness between pages, giving an experience closer to a desktop/native app.

## GUI diff

Before:
before_spa_react

After:
after spa

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- [doc-susemanager](https://github.com/SUSE/doc-susemanager) PR or issue was created (GitHub automatic link expected below)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by ncounter** [comment]
Still pending on https://github.com/liferay/senna.js/pull/323 . Once it is merged, I'll revisit this. Please keep this open for now.

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by srbarrios** [comment]
This PR still WIP @ncounter ?

**Comment by ncounter** [comment]
> This PR still WIP @ncounter ?

It comes with perfect timing your question: I pinged two days ago upstream about the pending PR to unblock this one, but they kind of closed it without merging. Reasons are the upstream PR from Luis is quite old and has quite a lot of conflicts now, and they are also moving to a different repo/project. Therefore I'd say we should close this for now. Resurrecting later will be a different story diverged a lot from here, we will evaluate at that point in time.

**Pull request closed without merging**
