### PR TITLE
QA: Fix default Cucumber profile

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

The default Cucumber profile must have some content, otherwise it fails.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were added

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Bischoff** [comment]
oooh `-r features` maybe we don't have to specify it anymore from command line? if so, very cool

**Comment by srbarrios** [comment]
> oooh `-r features` maybe we don't have to specify it anymore from command line? if so, very cool

As it will take allways the default profile, unless you specify one.
Yes, the options there are not anymore necessery to be passed in our manual runs.

**Comment by Bischoff** [comment]
> > oooh `-r features` maybe we don't have to specify it anymore from command line? if so, very cool
> 
> As it will take allways the default profile, unless you specify one.
> Yes, the options there are not anymore necessery to be passed in our manual runs.

I tried yesterday on 4.1 and still had to specify the option. But maybe it was not ported yet to 4.1?

**Comment by calancha** [comment]
> I tried yesterday on 4.1 and still had to specify the option. But maybe it was not ported yet to 4.1?

That's correct: it is not ported yet.

**Pull request merged**
