### PR TITLE
Use storybook's docs addon rather than the info one.

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

The story book info addon can't display the doc of the flow properties
of components and has been deprecated starting storybook 5.2. Update to
storybook 5.2.8 and add the docs addon that replaces it and behaves
nicely with the flow docs.

This also drags updates for Babel and react among others.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only affecting dev tools

- [X] **DONE**

## Test coverage
- No tests: only affecting dev tools

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by cbosdo** [comment]
Merry Christmas @ncounter :santa:

**Comment by cbosdo** [comment]
Screenshot of it with the new `FormMultiInput`component
Screenshot_2019-12-20 Forms FormMultiInput - Example ⋅ Storybook

**Comment by cbosdo** [comment]
Found out that this commit is introducing huge slowness in eslint. Digging into the issue

**Comment by cbosdo** [comment]
OK, I'll update the commit message. As a side node, we'll need to keep in mind to progressively replace the `UNSAFE_*` functions since those are likely to be kicked away by React 17.

**Comment by cbbayburt** [comment]
> OK, I'll update the commit message. As a side node, we'll need to keep in mind to progressively replace the `UNSAFE_*` functions since those are likely to be kicked away by React 17.

Right. A grep shows ~20 usages of them currently.

**Comment by cbbayburt** [comment]
@ncounter I'd appreciate an additional review by you for this. It might potentially introduce regressions.

**Comment by cbosdo** [comment]
Wiki page updated: https://github.com/uyuni-project/uyuni/wiki/Frontend-Development-Environment

**Comment by cbbayburt** [comment]
> [...] but I am looking for some confident test before merging as it is touching very important pieces (like upgrading React).

BTW, @cbosdo please keep an eye on the testsuite for a couple of runs after this is merged.

**Comment by cbosdo** [comment]
> @cbosdo : as @cbbayburt says he tested manually, can I ask to you as well what is the level of test and how you did it? I mean, did you test manually, or did you run a complete testsuite against a local setup with your changes, or? I am asking because so far everything looks good, but I am looking for some confident test before merging as it is touching very important pieces (like upgrading React).

So far it was only manual tests. I am using those commits on my dev setup where I'm mostly playing with the virtualization pages.

**Comment by cbosdo** [comment]
> > [...] but I am looking for some confident test before merging as it is touching very important pieces (like upgrading React).
> 
> BTW, @cbosdo please keep an eye on the testsuite for a couple of runs after this is merged.

Sure

**Pull request merged**
