### PR TITLE
Add SLE 15 SAP Product ID to SLE15 bootstrap repositories

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

Add SLE 15 SAP Product ID to SLE15 bootstrap repositories. It is required to get python3-M2Crypto (bsc#1189422)

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed

- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/15699
https://bugzilla.suse.com/show_bug.cgi?id=1189422

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — CHANGES_REQUESTED** [review]
This will not work. The PDID list all required products. You need to duplicate the whole section, rename the keyword and exchage the LTSS product id with the ID of SLES for SAP which receive the LTSS Updates

**Comment by jordimassaguerpla** [comment]
> This will not work. The PDID list all required products. You need to duplicate the whole section, rename the keyword and exchage the LTSS product id with the ID of SLES for SAP which receive the LTSS Updates

If I rename the keyword, to for example SLE4SAP15, should I do anything else with this keyword? Should it be at some other place so bootstrapping the clients add this one?

**Comment by jordimassaguerpla** [comment]
@mcalmer should it be one for SP1, SP2, SP3 ?

**Review by mcalmer — APPROVED** [review]

**Comment by mcalmer** [comment]
> > This will not work. The PDID list all required products. You need to duplicate the whole section, rename the keyword and exchage the LTSS product id with the ID of SLES for SAP which receive the LTSS Updates
> 
> If I rename the keyword, to for example SLE4SAP15, should I do anything else with this keyword? Should it be at some other place so bootstrapping the clients add this one?

Nothing else to do. This keyword is, what the customer see and can select. As long as we did not introduce new dependencies after the regular maintenance period, SLES and SLES for SAP is the same. But as soon as it is required to have LTSS Channel for SLES to install the lastest salt package, we need to split SAP in an extra target to define the other product ID.

**Comment by jordimassaguerpla** [comment]
Customer reported this fixed the issue.

**Pull request merged**
