### PR TITLE
Fix UT when checksum data isn't there from the first run

### PR DESCRIPTION
**Pull request by isbm**
## What does this PR change?

Fixes broken UT by this commit: https://github.com/uyuni-project/uyuni/commit/b1e57faf41faf014ba6141af5a374081a214b15b#diff-48784950a76c1dbc3d46f3a330a04602

### CODE REVIEW

**Comment by isbm** [comment]
@mcalmer this doesn't need a CL entry, as this is follow-up to @moio 's PR that broke testing. His PR already made the CL entry.

**Comment by isbm** [comment]
gitarro no changelog needed !!!

**Comment by juliogonzalez** [comment]
rerun changelog_test

**Comment by juliogonzalez** [comment]
Merging.

**Pull request merged**
