### PR TITLE
added workaround for min_ubuntu_salt

### PR DESCRIPTION
**Pull request by atighineanu**
## What does this PR change?
This PR is a workaround for Uyuni branch, in order to avoid  this: https://github.com/SUSE/spacewalk/issues/14452#issuecomment-820255541

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ x ] No changelog needed

### CODE REVIEW

**Comment by Bischoff** [comment]
Will probably not be needed, as salt will be promoted in emergency.

**Comment by srbarrios** [comment]
We can close this, it worked here: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-dev-cucumber-NUE/1448/

**Review by srbarrios — CHANGES_REQUESTED** [review]
Don't merge it please.

**Comment by atighineanu** [comment]
Closing PR as it's an ugly (optional) workaround.

**Pull request closed without merging**
