### PR TITLE
Simplified/fixed postgresql14 requirement.

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

1. Simplified postgresql14 requirement.
2. Official RHEL postgresql14 provides postgresql >= 14 which also causes a conflict with postgresql >= 15.
the requirement simplification works around it.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql" (Test skipped, there are no changes to test)
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
@juliogonzalez , any chance of a quick merge on this one?

**Review by juliogonzalez — COMMENTED** [review]
LGTM, my question is... what will happen when we change 107 to be `150500` and maybe require postgresql15? We need to that ahead of the change of Leap for Uyuni, because of SUSE Manager... so I guess we'll complicate the requirement again?

@mbussolotto @jordimassaguerpla thoughts?

**Comment by mbussolotto** [comment]
> LGTM, my question is... what will happen when we change 107 to be `150500` and maybe require postgresql15? We need to that ahead of the change of Leap for Uyuni, because of SUSE Manager... so I guess we'll complicate the requirement again?
> 
> @mbussolotto @jordimassaguerpla thoughts?
yes, honestly I would keep just one OS type in a if statement (so sles/opensuse inside a if and redhat in another one). IMHO it would be more readable and easier to maintain.
instead I'm 100% agree to get rid of `%if 0%{?suse_version} || 0%{?is_opensuse}`: `sle_version` covers both the cases https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto . Thanks for noticing it !

**Comment by sbluhm** [comment]
@mbussolotto , I have reverted the changes and modified the first if statement to your comment.

Overall, I have "hard coded" the else section to postgresql14 / not postgresql15 due to a bug in the PostgreSQL package. We can revert it once the official package is fixed.
(https://www.postgresql.org/message-id/17507-7c4325dda6d8445f%40postgresql.org)

**Review by mbussolotto — APPROVED** [review]

**Review by juliogonzalez — APPROVED** [review]

**Pull request merged**
