### PR TITLE
Using a new user per feature (Mandatory for parallel tests)

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

Related to https://github.com/SUSE/spacewalk/issues/9748

Creating a new user per feature, using a scenario hook that will only pass for the first scenario per feature, acting as a feature hook.

It will by-pass the authentication of testing or admin users, using the regular step, when the feature variable @username is not null.

It creates a user name based on the feature filename because the feature name is too long and we have secondary features that acts on several clients during the same feature, so client name can't be use for that purpose on regular CI Tests. 

How to debug parallel tests is another topic, that we can discuss and improve separetely.
The aime of that PR is only to fix the current issue with multiple systems selected as described in the issue linked.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were changed, need to check on CI

- [x] **DONE**

## Links

None

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by srbarrios** [comment]
I would like to test directly in our "staging" CI, on NUE.

**Comment by srbarrios** [comment]
> Instead of a random number, I would like to derive the user's name from the minion's name. Example: `user-sle_minion`.
> 
> It would make debugging easier and avoid potential name duplicates (yeas, I know they are unlikely). With your templating system, it should not be difficult to pass minion's name to the step.

As mentioned in the description, this PR aimes to fix the current parallel execution issue on regular CI Tests. The templates are only used on QAM TesuSuite where the smoke tests are the same for all the clients. We can't use host name for username per feature, as some features on regular testsuite are acting on more than one client, also our current organization in regular CI tests don't allow us to parallelize by client our secondary tests, for that purpose first we will need to reorganize and isolate the features by client.

**Comment by Bischoff** [comment]
> > Instead of a random number, I would like to derive the user's name from the minion's name. Example: `user-sle_minion`.
> > It would make debugging easier and avoid potential name duplicates (yeas, I know they are unlikely). With your templating system, it should not be difficult to pass minion's name to the step.
> 
> As mentioned in the description, this PR aimes to fix the current parallel execution issue on regular CI Tests. The templates are only used on QAM TesuSuite where the smoke tests are the same for all the clients. We can't use host name for username per feature, as some features on regular testsuite are acting on more than one client, also our current organization in regular CI tests don't allow us to parallelize by client our secondary tests, for that purpose first we will need to reorganize and isolate the features by client.

I don't see where the problem is. Don't you instantiate your templates with different client names each time? You could then pass this client's name to the step.

**Comment by srbarrios** [comment]
> > > Instead of a random number, I would like to derive the user's name from the minion's name. Example: `user-sle_minion`.
> > > It would make debugging easier and avoid potential name duplicates (yeas, I know they are unlikely). With your templating system, it should not be difficult to pass minion's name to the step.
> > 
> > 
> > As mentioned in the description, this PR aimes to fix the current parallel execution issue on regular CI Tests. The templates are only used on QAM TesuSuite where the smoke tests are the same for all the clients. We can't use host name for username per feature, as some features on regular testsuite are acting on more than one client, also our current organization in regular CI tests don't allow us to parallelize by client our secondary tests, for that purpose first we will need to reorganize and isolate the features by client.
> 
> You need to create the user before you bootstrap, and you bootstrap on a per-client basis. Just create the user in some feature that is client-specific. You don't need to reaorganize and isolate all, only the user creation needs to.

Ok, I'm going to try to explain the workflow:

At some moment during the testsuite, we get all the secondary features, we group separate them in groups with the same quantity of feature files and we run those groups in different threads.

Each group will contain then a random set of secondary features, for each of those groups we need a different user name, to fix the problem of selected systems per user, which are stored on database.

We want to make parametrizable the amount of groups (threads) we want to have to execute them in parallel. Also as the minimum unit to parallelize is the feature, we would like to use a user per feature, so if we change anything else in the organization of features, this solution is not affected.

**Comment by Bischoff** [comment]
> Ok, I'm going to try to explain the workflow:
> 
> At some moment during the testsuite, we get all the secondary features, we group separate them in groups with the same quantity of feature files and we run those groups in different threads.
> 
> Each group will contain then a random set of secondary features, for each of those groups we need a different user name, to fix the problem of selected systems per user, which are stored on database.
> 
> We want to make parametrizable the amount of groups (threads) we want to have to execute them in parallel. Also as the minimum unit to parallelize is the feature, we would like to use a user per feature, so if we change anything else in the organization of features, this solution is not affected.

Sorry for the delay in answering @srbarrios .

Ah ok, the different threads might address the same minions. I did not know that.

OK, let me just insist a last bit before I give up with my idea :stuck_out_tongue: : what about indexing the user names based on the feature name, then ?

**Comment by srbarrios** [comment]
> > Ok, I'm going to try to explain the workflow:
> > At some moment during the testsuite, we get all the secondary features, we group separate them in groups with the same quantity of feature files and we run those groups in different threads.
> > Each group will contain then a random set of secondary features, for each of those groups we need a different user name, to fix the problem of selected systems per user, which are stored on database.
> > We want to make parametrizable the amount of groups (threads) we want to have to execute them in parallel. Also as the minimum unit to parallelize is the feature, we would like to use a user per feature, so if we change anything else in the organization of features, this solution is not affected.
> 
> Sorry for the delay in answering @srbarrios .
> 
> Ah ok, the different threads might address the same minions. I did not know that.
> 
> OK, let me just insist a last bit before I give up with my idea  : what about indexing the user names based on the feature name, then ?

Yep, actually that's what is in place now:
https://github.com/uyuni-project/uyuni/pull/1660#issuecomment-564023585

I forgot to update the description

**Comment by Bischoff** [comment]
> Yep, actually that's what is in place now:
> [#1660 (comment)](https://github.com/uyuni-project/uyuni/pull/1660#issuecomment-564023585)
> 
> I forgot to update the description

Cool! :tada: 

Er @srbarrios , sorry to be such a nitpicker, but I suggest that you replace the word "random" with "unique" in:
* the commit messages
* this PR's title

:smile_cat:

**Comment by srbarrios** [comment]
> > Yep, actually that's what is in place now:
> > [#1660 (comment)](https://github.com/uyuni-project/uyuni/pull/1660#issuecomment-564023585)
> > I forgot to update the description
> 
> Cool! 
> 
> Er @srbarrios , sorry to be such a nitpicker, but I suggest that you replace the word "random" with "unique" in:
> 
> * the commit messages
> * this PR's title

Ok, I will change them, just one remark before was really "unique" using the random appended value. Now we will need to rely in us, to don't create two features with the same filename in a different folder. But.. I consider good enough.

**Comment by Bischoff** [comment]
> Ok, I will change them, just one remark before was really "unique" using the random appended value. Now we will need to rely on us to don't create two features with the same filename in a different folder. But.. I consider it good enough.

Right.

Thanks for the changes.

**Comment by srbarrios** [comment]
I would really like to work on that one, and close it, so we can use parallel tests in our CI TestSuite.
@ktsamis FYI as coordinator ^^^

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by mcalmer** [comment]
I have the feeling this is dead. I am closing it.
Feel free to continue working and reopen it.

**Comment by srbarrios** [comment]
No, this is not dead, I just don't have time for it :(

**Comment by srbarrios** [comment]
I resolved conflicts and did some clean-up as some of the work made here, was already merged in other PRs.

**Review by vandabarata — APPROVED** [review]

**Comment by srbarrios** [comment]
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1498/TestSuite_20Report_20for_20Pull_20Request_20systemsmanagement_3aUyuni_3aMaster_3aPR_3a1660/


All good here, we can merge.

**Pull request merged**
