### PR TITLE
Systems list crash

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Fixes crash when filtering in systems lists with multiple users connected.

## GUI diff

No difference.
- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: requires multiple users and some patience to reproduce
- [X] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/18898, https://github.com/SUSE/spacewalk/issues/18891 and https://github.com/uyuni-project/uyuni/issues/5890

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
Should I merge this one?

**Review by cbbayburt — APPROVED** [review]

**Comment by admd** [comment]
@cbosdo is this something that could have affected 4.2 as well or problem was it specific to 4.3?

**Comment by cbosdo** [comment]
I don't think the related code has been ported to 4.2...

**Comment by admd** [comment]
it seems customers are facing the same problem on 4.2 as well because symptoms are very similar except that they don't have anything in logs.

**Comment by cbosdo** [comment]
> it seems customers are facing the same problem on 4.2 as well because symptoms are very similar except that they don't have anything in logs.

@admd the code that was causing the issue in 4.3 and master is not in 4.2... it cannot be the same problem.

**Pull request merged**
