### PR TITLE
pg-migrate: check latest postgresql??-server package

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

You can have postgresql-server-14 and postgresql13-server. Thus, what we
need to check is the version of postgresql??-server instead of the
postgresql-server package version.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed

- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links

Fixes # https://github.com/SUSE/spacewalk/issues/16334

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [x] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]
Give it a try

**Comment by jordimassaguerpla** [comment]
> Give it a try

I just have adapted the script based on this feedback https://bugzilla.suse.com/show_bug.cgi?id=1192368#c19

**Comment by srbarrios** [comment]
Should we also include a new file:
`/usr/lib/susemanager/bin/pg-migrate-12-to-14.sh` ?

**Comment by jordimassaguerpla** [comment]
> Should we also include a new file: `/usr/lib/susemanager/bin/pg-migrate-12-to-14.sh` ?

Not yet. pg13 is the default in SLES, so we use that one. We use postgresql13-* packages. We just need to check postgresql13-servers is installed and ignore postgresql-server version.

**Comment by srbarrios** [comment]
It worked with the current script... but it's weird as it suppose to use 14, but the script says 13.

``` 
suma-long-41-srv:~ # /usr/lib/susemanager/bin/pg-migrate-12-to-13.sh
16:51:50    You have postgresql-server 13 installed.
16:51:50    You have postgresql server 12 configured.
16:51:50   Checking diskspace... ok.
16:51:50   Shut down spacewalk services...
Shutting down spacewalk services...
Done.
16:51:51   Checking postgresql version...
16:51:51   postgresql 13 is already installed. Good.
16:51:51   Ensure postgresql 13 is being used as default...
16:51:51   Successfully switched to new postgresql version 13.
16:51:51   Create a backup at /var/lib/pgsql/data-pg12...
16:51:51   Create new database directory...
16:51:51   Initialize new postgresql 13 database...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Berlin
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/pgsql/data -l logfile start

16:51:52   Successfully initialized new postgresql 13 database.
16:51:52   Upgrade database to new version postgresql 13...
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok
Checking for presence of required libraries                 ok
Checking database user is the install user                  ok
Checking for prepared transactions                          ok
Checking for new cluster tablespace directories             ok

If pg_upgrade fails after this point, you must re-initdb the
new cluster before continuing.

Performing Upgrade
------------------
Analyzing all rows in the new cluster                       ok
Freezing all rows in the new cluster                        ok
Deleting files from new pg_xact                             ok
Copying old pg_xact to new server                           ok
Setting oldest XID for new cluster                          ok
Setting next transaction ID and epoch for new cluster       ok
Deleting files from new pg_multixact/offsets                ok
Copying old pg_multixact/offsets to new server              ok
Deleting files from new pg_multixact/members                ok
Copying old pg_multixact/members to new server              ok
Setting next multixact ID and offset for new cluster        ok
Resetting WAL archives                                      ok
Setting frozenxid and minmxid counters in new cluster       ok
Restoring global objects in the new cluster                 ok
Restoring database schemas in the new cluster
                                                            ok
Copying user relation files
                                                            ok
Setting next OID for new cluster                            ok
Sync data directory to disk                                 ok
Creating script to analyze new cluster                      ok
Creating script to delete old cluster                       ok
Checking for extension updates                              ok

Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade so,
once you start the new server, consider running:
    ./analyze_new_cluster.sh

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
16:52:15   Successfully upgraded database to postgresql 13.
16:52:15   Tune new postgresql configuration...
INFO: Database configuration has been changed.
INFO: Wrote new general configuration. Backup as /var/lib/pgsql/data/postgresql.2021-11-24-16-52-16.conf
INFO: Wrote new client auth configuration. Backup as /var/lib/pgsql/data/pg_hba.2021-11-24-16-52-16.conf
INFO: Configuration has been changed, but your database is right now offline.
Database is offline
System check finished
16:52:16   Successfully tuned new postgresql configuration.
16:52:16   Starting PostgreSQL service...
16:52:16   Reindexing database. This may take a while, please do not cancel it!
REINDEX
16:52:53   Starting spacewalk services...
Starting spacewalk services...
  Running DB schema upgrade. This may take a while.
  Call the following command to see progress: journalctl -f -u uyuni-check-database.service
```

**Comment by srbarrios** [comment]
Ahmmm ok, I see, so we will not use postgresql14 in fact, ok!

**Review by srbarrios — APPROVED** [review]
Tested and works

**Comment by jordimassaguerpla** [comment]
smdba seconday tests passed on this one.

**Comment by jordimassaguerpla** [comment]
> smdba seconday tests passed on this one.

@mcalmer can we merge this one?

**Comment by mcalmer** [comment]
> > smdba seconday tests passed on this one.
> 
> @mcalmer can we merge this one?

@ktsamis decide what we merge today. I would just add the "merge-candidate" label and then we need to talk to him what we merge today

**Pull request merged**
