### PR TITLE
Manager no scc setup

### PR DESCRIPTION
**Pull request by mantel**
## What does this PR change?

remove SCC setup from YaST SUSE Manager setup

## GUI diff

When user runs "yast2 susemanager_setup", there is no longer a dialog allowing to enter SCC credentials.

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@mantel: why do we need this :-?

**Comment by juliogonzalez** [comment]
BTW: I am pretty sure this will need doc changes.

**Comment by mcalmer** [comment]
@mantel please open a issue for updating the docs. And you need to check how the cucmber testsuite is affected by this change. This maybe easier when this is merged, so should merge it when alpha 2 is done.

**Comment by juliogonzalez** [comment]
@mantel, AFAIK that's right: cucumber does not use the yast2 setup wizard, but a file with answers, so this is always tested manually.

I was not aware of SUSE/spacewalk#4424, but if it was requested... well, ok. I guess it makes Uyuni more agnostic.

**Comment by mantel** [comment]
> Please take care that the doc issue exists and that we adapt the cucumber testsuite to not set the credentials via mgr-setup, but in a test via UI or commandline

What is the problem with setting the credentials via "mgr-setup"? This is what is currently being done in sumaform (it is creating a setup_env.sh with those values added). For the testsuite it does not matter at all who is adding those credentials to the setup_env.sh file!?

**Comment by mantel** [comment]
gitarro rerun schema_migration_test_pgsql !!!

**Comment by mantel** [comment]
gitarro rerun susemanager_unittests !!!

**Pull request merged**
