### PR TITLE
Enhance hardware data sent to SCC by memory

### PR DESCRIPTION
**Pull request by rjpmestre**
## What does this PR change?

As SCC API can now collect systems memory (RAM).  
This enhances hardware data sent to SCC by adding total memory in MiB

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/22758

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — COMMENTED** [review]
Good first step. Next challenge: check the database triggers we have for hardware.
The idea is, that when this value change in DB, we add the system to a table which make the taskomatic job run and update the data in SCC.
We have trigger for CPU already. Now we need a trigger for memory

**Comment by rjpmestre** [comment]
> Good first step. Next challenge: check the database triggers we have for hardware. The idea is, that when this value change in DB, we add the system to a table which make the taskomatic job run and update the data in SCC. We have trigger for CPU already. Now we need a trigger for memory

The only triggers that fit this description (actually the only ones i found) are rhn_cpu_mod_trig, rhn_cpu_mod_trig and rhn_cpu_up_trig.
There seems to already exist a variation to the rhnram table.
Am i missing something here?

```
select * from information_schema.triggers 
where event_object_table in ('rhncpu','rhnram')
order by event_object_table, trigger_name, event_manipulation ;
```

**Comment by mcalmer** [comment]
Yes, we have the trigger already. I was not aware. (schema/spacewalk/postgres/triggers/rhnRam.sql)

"rhn_ram_up_trig" update suseSCCRegCache table when the value change

**Comment by mcalmer** [comment]
@rjpmestre something with the rebase did not work. You have commits in this PR which are already in merged.
And please backport to 4.3. Thanks

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
