### PR TITLE
Prevent deadlock on delete_server (bsc#1173073)

### PR DESCRIPTION
**Pull request by moio**
## What does this PR change?

This reverts two earlier deadlock fixes, that are not useful any more given more recent Postgres solve the underlying root problem at the database level. Actually those fixes carry an extra risk of more deadlocks, and one such case was actually found in the context of bsc#1173073:

```
ERROR:  deadlock detected
DETAIL:  Process 8479 waits for ShareLock on transaction 399669498; blocked by process 14346.
	Process 14346 waits for AccessShareLock on tuple (60052,11) of relation 17045 of database 16384; blocked by process 14592.
	Process 14592 waits for ShareLock on transaction 399669163; blocked by process 8479.
	Process 8479: select * from delete_server($1)  as result
	Process 14346:
	            insert into rhnServerPackage
	            (server_id, name_id, evr_id, package_arch_id, installtime)
	            values (1000102753, LOOKUP_PACKAGE_NAME('rhn-org-trusted-ssl-cert'), LOOKUP_EVR(NULL, '1.0', '10'),
	                LOOKUP_PACKAGE_ARCH('noarch'), TO_TIMESTAMP('2020-06-07 15:45:10', 'YYYY-MM-DD HH24:MI:SS')
	            )
	Process 14592: select * from rhn_server.update_needed_cache($1) as result
```

Here we have:
 - process 8479 deleting a client (Tomcat code)
 - process 14592 updating the errata cache of that same client (Taskomatic code)
 - process 14346 refreshing the client's package list (Python private XMLRPC API code)

Dependencies:
 - 8479 waits on 14346 because it is deleting the same rows in `rhnServerPackage` (not easily avoidable)
 - 14346 waits on 14592 because of the fix for bsc#918549 being reverted here
   - fix is not needed any more because it worked around a Postgres implementation detail later improved in version 9.5. I verified the bug is actually not any more reproducible in later versions
 - 14592 waits on 8479 because of the fix for bsc#969790 being reverted here
   - fix is not needed any longer because the bug was a consequence of the earlier fix for bsc#918549. With the former reverted, this bug can't be reproduced as well

More details in commit messages, references below:

- bug 918549
  - Bugzilla: https://bugzilla.suse.com/918549
  - Upstream PR: https://github.com/spacewalkproject/spacewalk/pull/233
  - Downstream PR: https://github.com/SUSE/spacewalk/pull/244
  - Explanations: http://www.moioli.net/progetti/a-postgres-deadlock-bug-case-study/ https://github.com/SUSE/spacewalk/wiki/Postgres-deadlocks...-now-what%3F#a-case-study-bug-918549
  - commit ID (Manager-3.2 and over): b0a27c0f22c2da5054a6543563e97790691c6711

- bug 969790
  - Bugzilla: https://bugzilla.suse.com/969790
  - Upstream PR: https://github.com/spacewalkproject/spacewalk/pull/449
  - Downstream PR: https://github.com/SUSE/spacewalk/pull/733
  - Explanation: https://github.com/SUSE/spacewalk/wiki/Bug-969790
  - commit ID (Manager-3.2 and over): e69bab06d22148f3c6c3ecf15e3baf5a68220cdb

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **bugfix**
- [x] **DONE**

## Test coverage
- No tests: **not easily reproducible, needs large infrastructure/highly automated**

- [x] **DONE**

## Links

Fixes partially https://bugzilla.suse.com/show_bug.cgi?id=1173073
Tracks https://github.com/SUSE/spacewalk/pull/11813 https://github.com/SUSE/spacewalk/pull/11812 https://github.com/SUSE/spacewalk/pull/12132

- [ ] **DONE**

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by moio** [comment]
> If it does not go into GMC2, you need to change the DB schema migration directory name.
> Please check, before merging

Thanks for the heads up. I will do that as soon as I get some word from the affected user.

**Comment by moio** [comment]
FTR: I am holding back merging a bit more while I get comprehensive evidence from the user noticing this problem that it is now solved.

**Comment by juliogonzalez** [comment]
@moio no news yet?

**Comment by moio** [comment]
unfortunately not

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Pull request merged**
