### PR TITLE
fix idempotency of schema migration

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

fix idempotency of schema migration

## Documentation
- No documentation needed: **internal**

- [x] **DONE**

## Test coverage
- No tests: **fixes test**

- [x] **DONE**

### CODE REVIEW

**Comment by juliogonzalez** [comment]
gitarro no changelog needed !!!

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by juliogonzalez** [comment]
And besides, even if this PR does not change `java/` I can't see why the test is failing :-(

**Comment by MalloZup** [comment]
we might open an issue with this PR referenced for further debugging

**Comment by mcalmer** [comment]
@juliogonzalez while it is goog to know why it is running even if it should not, I would suggest to run java tests always when the database schema changed.

**Comment by juliogonzalez** [comment]
@mcalmer, I agree, but I think we need to patch gitarro for that, to support multiple filters (instead of having more jobs and more gitarro instances running).

**Comment by juliogonzalez** [comment]
Job configured to be kept forever, and issue created at https://github.com/openSUSE/gitarro/issues/132

Michael request about running `java_pgsql_tests` for SQL stuff generated the following feature request: https://github.com/openSUSE/gitarro/issues/133

**Comment by juliogonzalez** [comment]
gitarro rerun java_pgsql_tests!!!

**Comment by juliogonzalez** [comment]
I am not 100% sure but I would think this kind of fake failure was happening to Franky some days ago, and he ran the test until it got green.

**Pull request merged**
