### PR TITLE
change GPG Key URL for openSUSE Leap to local file URL

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Change Leap GPG key url to a local file URL. The Key is part of the `openSUSE-build-key` package.
Exclude "leap_micro" as it might not have this package installed by default.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: We don't have tests for `spacewalk-common-channels`  for all OS.

- [x] **DONE**

## Links

Fixes https://github.com/uyuni-project/uyuni/issues/6215
Fixes https://github.com/SUSE/spacewalk/issues/19689

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by juliogonzalez — CHANGES_REQUESTED** [review]
One possible typo and... are you sure all versions of Leap and current Tumbleweed al use the same GPG key? Did you check?

I downloaded all keys from the URLs you are removing and seems Leap 15.5 and Tumbleweed use a new key... that I can't find at `uyuni-build-keys`? I'd assume both got this key changed recently as @raulillo82 tested Leap 15.5 and was working fine?

```
$ curl http://download.opensuse.org/distribution/leap/15.0/repo/oss/repodata/repomd.xml.key -o 15.0.key
$ curl http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/repomd.xml.key -o 15.1.key
$ curl http://download.opensuse.org/ports/aarch64/distribution/leap/15.1/repo/oss/repodata/repomd.xml.key -o 15.1-aarch.key
$ curl http://download.opensuse.org/distribution/leap/15.2/repo/oss/repodata/repomd.xml.key -o 15.2.key
$ curl http://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/repodata/repomd.xml.key -o 15.2-aarch.key
$ curl http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml.key -o 15.3.key
$ curl http://download.opensuse.org/distribution/leap/15.4/repo/oss/repodata/repomd.xml.key -o 15.4.key
$ curl http://download.opensuse.org/distribution/leap/15.5/repo/oss/repodata/repomd.xml.key -o 15.5.key
$ curl http://download.opensuse.org/tumbleweed/repo/oss/repodata/repomd.xml.key -o tumbleweed.key
```
A quick inspection with ls already shows differences:
```
$ ls -lh
total 40K
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:29 15.0.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:30 15.1-aarch.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:29 15.1.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:30 15.2-aarch.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:30 15.2.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:30 15.3.key
-rw-r--r-- 1 juliogonzalez users  988 abr 17 15:30 15.4.key
-rw-r--r-- 1 juliogonzalez users 1,7K abr 17 15:31 15.5.key
-rw-r--r-- 1 juliogonzalez users 1,7K abr 17 15:31 tumbleweed.key
```
And indeed seems 15.5 and Tumbleweed use a different key:
```
$ for file in $(ls); do echo "================= ${file} ==================="; gpg --show-keys ${file}; done
================= 15.0.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.1-aarch.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.1.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.2-aarch.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.2.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.3.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.4.key ===================
gpg: enabled debug flags: memstat
pub   rsa2048 2008-11-07 [SC] [caduca: 2024-05-02]
      22C07BA534178CD02EFE22AAB88B2FD43DBDC284
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= 15.5.key ===================
gpg: enabled debug flags: memstat
pub   rsa4096 2022-06-20 [SC] [caduca: 2026-06-19]
      AD485664E901B867051AB15F35A2F86E29B700A4
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
================= tumbleweed.key ===================
gpg: enabled debug flags: memstat
pub   rsa4096 2022-06-20 [SC] [caduca: 2026-06-19]
      AD485664E901B867051AB15F35A2F86E29B700A4
uid                      openSUSE Project Signing Key <opensuse@opensuse.org>

gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=3 cached=2 good=2 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks
```

**Review by juliogonzalez — COMMENTED** [review]
In general looks good, but on the chat you mentioned:

> Seems that Tumbleweed does not install the package with the GPG keys. So we need to keep the URL to external

However here you are changing the GPG for Tumbleweed to internal?

**Comment by mcalmer** [comment]
> In general looks good, but on the chat you mentioned:
> 
> > Seems that Tumbleweed does not install the package with the GPG keys. So we need to keep the URL to external
> 
> However here you are changing the GPG for Tumbleweed to internal?

We checked again on a Tumbleweed system and it has the openSUSE-build-keys package installed.
So we can use the same mechanism as on Leap.

**Review by juliogonzalez — APPROVED** [review]
LGTM, but let's wait for the merge until we can review the SRs for the build keys packages.

**Comment by mcalmer** [comment]
@juliogonzalez now it is ready and also moved the schema dir to current.

**Comment by juliogonzalez** [comment]
> @juliogonzalez now it is ready and also moved the schema dir to current.

ACK, ping me when the SRs are ready, and I will have a look, merge, and will merge this as well.

**Pull request merged**
