### PR TITLE
Master weblate

### PR DESCRIPTION
**Pull request by mackdk**
## What does this PR change?

Translation update

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — CHANGES_REQUESTED** [review]
over 10000 commits? This cannot be right

**Comment by mackdk** [comment]
@mcalmer No, it's not and I wasn't going to merge it. There was a problem with the github workflow `update_translations.yml` and it entered in a commit loop where it changed the formatting of a po file and weblate changed it again, on and on. It has basically  committed every 4 minutes since the 22nd on the `master-weblate` branch. The workflow is now stopped. I would like to squash all the wrong commits before merging to master, but after doing that I would need to do a reset from the weblate UI as well, right? I'm not very familiar with that.

**Comment by mcalmer** [comment]
> @mcalmer No, it's not and I wasn't going to merge it. There was a problem with the github workflow `update_translations.yml` and it entered in a commit loop where it changed the formatting of a po file and weblate changed it again, on and on. It has basically committed every 4 minutes since the 22nd on the `master-weblate` branch. The workflow is now stopped. I would like to squash all the wrong commits before merging to master, but after doing that I would need to do a reset from the weblate UI as well, right? I'm not very familiar with that.

Me neither :-)
But sounds good, I think you lock weblate, squash all the commits in master-weblate and push. Then you will see what the UI say about this. Maybe you need to run the conflict resolving script.

**Comment by mackdk** [comment]
I squashed the wrong commits and forced push the branch. The weblate clone is synced as well so I think now it should be safe to merge

**Review by mbussolotto — APPROVED** [review]

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
