### PR TITLE
QA: Update year in our MIT-LICENSE

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

Update year in our MIT-LICENSE, and rename it.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were modified

- [x] **DONE**

## Links

Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/17018
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/17019

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by vandabarata — APPROVED** [review]

**Review by nodeg — APPROVED** [review]

**Comment by nodeg** [comment]
I was wondering why the file is not simply named `LICENSE` and why it uses `.txt` as extension?

**Comment by srbarrios** [comment]
yeah, you might be right, maybe we should remove the extension. I think that was there almost from the beginning of this test framework.

**Comment by nodeg** [comment]
I would do it in this PR since it is already open and I think it`s less work than opening another one.

**Comment by srbarrios** [comment]
OK, change applied.

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
