### PR TITLE
QAM: Remove ubuntu custom repositories, we use common channels

### PR DESCRIPTION
**Pull request by ktsamis**
## What does this PR change?

QAM: Remove ubuntu custom repositories, we use common channels
It's covered already in https://github.com/SUSE/spacewalk/blob/Manager-4.1/testsuite/features/build_validation/reposync/srv_common_channels.feature

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/13904
Tracks https://github.com/SUSE/spacewalk/pull/13905
https://github.com/SUSE/spacewalk/pull/13906

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
LGTM

**Comment by Bischoff** [comment]
Just add the yaml file changes.

**Review by Bischoff — APPROVED** [review]
Now with the yaml file change LGTM

But I would also port it to 4.0 please, avoids polluting my diffs

**Review by calancha — APPROVED** [review]

**Comment by ktsamis** [comment]
This does not touch the testsuite, only the build validation part.

**Pull request merged**
