### PR TITLE
fix unittest - use local configuration file

### PR DESCRIPTION
**Pull request by vlad-belogrudov**
## What does this PR change?

fixes unit test tear down so that non-global config can be used, e.i. one specified via test_up2date = "../etc-conf/up2date.config"

## GUI diff

No difference.

## Documentation
- No documentation needed: typo in unittest

## Test coverage
- No tests:  typo in existing test fixed

## Changelogs
gitarro no changelog needed !!!

### CODE REVIEW

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by mcalmer** [comment]
gitarro no changelog needed !!!

**Comment by mcalmer** [comment]
gitarro rerun changelog_test !!!

**Comment by mcalmer** [comment]
Thanks for the contribution

**Pull request merged**
