### PR TITLE
Detect Amazon EC2 instances

### PR DESCRIPTION
**Pull request by vzhestkov**
## What does this PR change?

Show `Amazon EC2` in `Virtualization` field in the system profile for Amazon EC2 instances.

Requires https://github.com/openSUSE/salt/pull/555 to be present on the salt minion side.

## GUI diff

Before:
Virtualization field in system profile was shown as `KVM/QEMU` or `Para-Virtualized` if running as `xen` instance.

After:
Virtualization field in system profile is labeled as `Amazon EC2`

## Documentation
- No documentation needed: only internal and user invisible changes

## Test coverage
- No tests: there is no tests for this part of functionality

## Links

Fixes https://github.com/SUSE/spacewalk/issues/16940

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by vzhestkov** [comment]
@meaksh I found that initially `Amazon EC2` was added with https://github.com/uyuni-project/uyuni/pull/1388, but I didn't find the way of detecting it from salt side. The other point here that `Amazon EC2` instance can be `kvm` or `xen` based. Do we need to distinguish them somehow? There is a single entry in `rhnVirtualInstanceType` with `aws` label. In the current state of this PR, both of these instance types will look the same.

**Comment by meaksh** [comment]
@vzhestkov let me try to recall here...

When we implemented support for Amazon EC2 instances, we did it also for the context of "Virtual Host Managers", so we use `virtual-host-gatherer` to collect the instances on your AWS region, and you get a list of virtual instances (uuids) running there. 

Those virtual instances, if not existing in the DB as registered systems, are created as "aws" type, as we don't really have access to those virtual instances to perform any operation and gather more information at this point to those instances.

NOTE: Maybe `virtual-host-gatherer` can collect extra info for the virtual instance (about "xen" or "kvm") so we can have more accurate type from the begining.

In any case, once we do actually register that virtual instance in SUMA (via bootstrapping), then SUMA should notice the "uuid" is the same of that virtual instance and should match them. Maybe then is when we see this wrong "Para-Virtualized" or "QEMU/KVM" in the virtualization field.

AFAICS this is a valid bug and the changes you are doing look correct.

**Review by meaksh — APPROVED** [review]

**Comment by meaksh** [comment]
@vzhestkov hmmm, yeah, maybe we can create those new types and then during HW refresh we assign the right type now that we have more information about the instance. Small new feature to be definetely more accurate :smile: 

IIUC this shouldn't harm, we simply create a new type in the DB (+ schema migration file) and assign proper type during HW refresh action.

**Review by rjmateus — APPROVED** [review]
LGTM

**Pull request merged**
