### PR TITLE
Tese cases for RES with two base channels

### PR DESCRIPTION
**Pull request by mateiw**
## What does this PR change?

Port of https://github.com/SUSE/spacewalk/pull/6563

Fixes https://github.com/SUSE/spacewalk/issues/6025

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"  
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"

### CODE REVIEW

**Comment by mateiw** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by mcalmer** [comment]
@mateiw seems the 3.2 variant is merged but this not. Please get this fixed and merged as well.

**Comment by mateiw** [comment]
@mcalmer from what I see the changes all changes are in 3.2. Did I miss something ?

**Comment by mcalmer** [comment]
@mateiw - yes, to merge it in uyuni :-) This is the only request I have.

**Pull request merged**
