### PR TITLE
Migrated docs from doc-susemanager - update github actions

### PR DESCRIPTION
**Pull request by jcayouette**
## What does this PR change?

This PR migrates docs from our doc-susemanager repo into our code base. 

Documentation is now stored in **docs/**

Two github actions have been added for docs in **.github/workflows/**

- deploy_docs.yml
- test_docs.yml

## GUI diff

No difference.

Before:

After:

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- [doc-susemanager](https://github.com/SUSE/doc-susemanager) PR or issue was created (GitHub automatic link expected below)

- [x] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

Actions were added for testing, building and deploying docs. 

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Loquacity** [comment]
Happy for this to merge once tests are passing.

**Comment by juliogonzalez** [comment]
Since we now have the `uyuni-docs` repository, I understand this is not needed anymore.

If that's the case then @jcayouette, please close the PR.

**Comment by juliogonzalez** [comment]
Ping @jcayouette

**Comment by Loquacity** [comment]
I think we can close it.

**Pull request closed without merging**
