### PR TITLE
python3-certifi missing from bootstrap repo

### LINKED ISSUE #3567: Uyuni Client tools repo missing python3-certifi package for CentOS 8
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.02-116.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.02-116.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
Minion is unable to update Uyuni client tools due to missing python3-certifi package

OS: CentOS 8
Existing Packages
openpgm.x86_64                       5.2.122-16.30.uyuni                    @susemanager:centos8-uyuni-client-x86_64
python3-m2crypto.x86_64              0.35.2-1.27.uyuni                      @susemanager:centos8-uyuni-client-x86_64
python3-msgpack.x86_64               0.4.6-1.32.uyuni                       @susemanager:centos8-uyuni-client-x86_64
python3-salt.x86_64                  3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
python3-tornado.x86_64               4.2.1-1.32.uyuni                       @susemanager:centos8-uyuni-client-x86_64
python3-zmq.x86_64                   17.0.0-4.30.uyuni                      @susemanager:centos8-uyuni-client-x86_64
salt.x86_64                          3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
salt-minion.x86_64                   3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
zeromq.x86_64                        4.1.6-11.28.uyuni                      @susemanager:centos8-uyuni-client-x86_64

dnf update salt salt-minion
Error: 
 Problem 1: package salt-3000-29.1.uyuni.x86_64 requires python3-salt = 3000-29.1.uyuni, but none of the providers can be installed
  - cannot install the best update candidate for package salt-3000-25.1.uyuni.x86_64
  - nothing provides python3-certifi needed by python3-salt-3000-29.1.uyuni.x86_64
 Problem 2: package salt-minion-3000-29.1.uyuni.x86_64 requires salt = 3000-29.1.uyuni, but none of the providers can be installed
  - package salt-3000-29.1.uyuni.x86_64 requires python3-salt = 3000-29.1.uyuni, but none of the providers can be installed
  - cannot install the best update candidate for package salt-minion-3000-25.1.uyuni.x86_64
  - nothing provides python3-certifi needed by python3-salt-3000-29.1.uyuni.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

python3-certifi package only exists in EPEL so this can be fixed by adding EPEL to the client provided the EPEL repo is configured to exclude all other packages required by Uyuni client tools.
Bootstrapping likely also fails as this package isn't listed in uyuni/susemanager/src/mgr_bootstrap_data.py

The dependency doesn't exist in the client tools repo for CentOS 8 at https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/x86_64/

### PR DESCRIPTION
**Pull request by brejoc**
## What does this PR change?

This PR adds `python3-certifi` to the bootstrap repo for RES8.

## GUI diff

No difference.

## Documentation
- No documentation needed: only internal and user invisible changes

## Test coverage
- No tests: Well…

## Links

Fixes #3567

## Changelogs

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by juliogonzalez — APPROVED** [review]
The diff looks ok, but what requires python3-certifi and why was this working before? I guess someone tried a cloud image or something similar?

Remember to backport this.

**Comment by brejoc** [comment]
> The diff looks ok, but what requires python3-certifi and why was this working before? I guess someone tried a cloud image or something similar?
> 
> Remember to backport this.

Not sure, but RES7 also had `python-certifi`, so I guess this is how it should actually be.

**Comment by juliogonzalez** [comment]
> Not sure, but RES7 also had `python-certifi`, so I guess this is how it should actually be.

Can you please check? Could be the dependencies are different at RES8.

**Review by juliogonzalez — CHANGES_REQUESTED** [review]
I don't think this is needed: https://build.opensuse.org/package/view_file/systemsmanagement:Uyuni:Master:CentOS8-Uyuni-Client-Tools/salt/salt.spec?expand=1 (line 592).

Maybe the user needs to sync the Uyuni client tools for CentOS8? Looks to me he has an old salt there.

**Comment by brejoc** [comment]
Closing this, because `python3-certifi` is no longer needed for RES7: https://github.com/uyuni-project/uyuni/issues/3567#issuecomment-829067136

**Comment by juliogonzalez** [comment]
> Closing this, because `python3-certifi` is no longer needed for RES7: [#3567 (comment)](https://github.com/uyuni-project/uyuni/issues/3567#issuecomment-829067136)

You mean RES8, right? :-D

**Comment by brejoc** [comment]
> > Closing this, because `python3-certifi` is no longer needed for RES7: [#3567 (comment)](https://github.com/uyuni-project/uyuni/issues/3567#issuecomment-829067136)
> 
> You mean RES8, right? :-D

Yes, sorry. We've been talking in chat about a RES7 problem just before I've been answering and then it got mixed up in my head! :laughing:

**Pull request closed without merging**
