### PR TITLE
Update Notification.java

### PR DESCRIPTION
**Pull request by postastny**
The webUserID is inserted into userProperties in the ServerEndpointConfig object (this happens in the ModifyHandshake method [WebsocketSessionConfigurator class]), so this map exists in a config variable, not in a session. UserProperties in the session are empty.

## What does this PR change?

**add description**

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]
Your PR is looking good to me since it makes the code more understandable.

However I fail to see if that fixes an issue: the `config` object is used to populate the session user properties. Can you explain us what lead you to this PR?

Thank you for your contribution, we expect to see others from you soon 😉

**Comment by cbosdo** [comment]
Could you please rebase the PR on latest master? There is a library that changed since then and this causes the checkstyle test to fail.

**Comment by ncounter** [comment]
@postastny : is there any follow-up here, especially on @cbosdo question about the `config` object that populates the session user properties?

**Comment by cbosdo** [comment]
This PR didn't get a response in a year, I will close it. Feel free to reopen if you can provide answer to the questions asked in comments

**Pull request closed without merging**
