### PR TITLE
Spacewalk cherry pick 20200209

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Cherry pick changes from spacewalk which may be usefull for uyuni as well.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **internal**

- [x] **DONE**

## Test coverage
- No tests: **sw had no tests**

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests" 		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@juliogonzalez rhnlib has no changelog. I would suggest to not tag and submit until it got a real change.

**Comment by mcalmer** [comment]
@juliogonzalez we can decide during hackweek. But there seems to be new packages missing for mgr-libmod. The Media install test is failing

**Comment by juliogonzalez** [comment]
Yes, I pinged @isbm  about it on Friday. It seems his package requires `python3-libmodulemd` which I already added from openSUSE on Friday (not present at SLE), and it seems even more.

@isbm you will need to try tomorrow your package on a branched project and try to install on openSUSE15.1 and SLE15SP2 until it works.

**Comment by isbm** [comment]
@juliogonzalez I think I messed up the name of the required dependency, let me double-check that tomorrow.

**Comment by juliogonzalez** [comment]
@isbm fixed, it seems. I will mail you the packages that where required :-)

**Pull request merged**
