### PR TITLE
Testsuite: Pacify Rubocop

### PR DESCRIPTION
**Pull request by calancha**
## What does this PR change?
Rewrite a list of constant strings as suggested by Rubocop

### Ports
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13400
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13401

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
My personal opinion is that we should move these lists to a map of key(distro)-value(channels_list) in constants.rb
But... well I know this is also a controversial topic :p

**Review by lkotek — CHANGES_REQUESTED** [review]
Thanks for changes! I see we currently hit different rubocop problem (maximum method length, at least in case of ports). 

Can you align the list of repos for 15SP1 and 15SP2, so we have additional ones like in the case of 4.1, please?

Apart of this I don't have problem with formatting if it resolves the rubocop problem, but I am also interested what @Bischoff opinion about it is.

**Comment by calancha** [comment]
One channel per line as suggested by Rubocop, greatly improves readability.

**Comment by Bischoff** [comment]
yeah formatting is just fine @lkotek, fanks for the fix @calancha

**Pull request merged**
