### PR TITLE
fix java test

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

After these changes https://github.com/uyuni-project/uyuni/commit/b91d21ebfbb5a01449e4eef06ab6765ccfe51551 we had problems with migration test, and these changes supposed to fix it https://github.com/uyuni-project/uyuni/commit/8684be36ecc53906c14753296fd400a92ea46554, but they break java test.

So I had a deeper analysis about why migration test succeed before  https://github.com/uyuni-project/uyuni/commit/b91d21ebfbb5a01449e4eef06ab6765ccfe51551  and, after enabling debug mode I found:

```
* Configuring tomcat.
Command: '/usr/bin/spacewalk-setup-tomcat '
open3: exec of /usr/bin/spacewalk-setup-tomcat  failed: No such file or directory at /manager/spacewalk/setup/lib/Spacewalk/Setup.pm line 307.
```
so most of the function in `spacewalk-setup` were not executing during migration test.

This PR:
- revert the changes not required
- skip some step in `spacewalk-setup` during migration test

In the future we probably need a complete refactoring of all this part

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: already covered

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [x] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql" (Test skipped, there are no changes to test)
- [ ] Re-run test "java_pgsql_tests" (Test skipped, there are no changes to test)
- [x] Re-run test "schema_migration_test_pgsql" (Test skipped, there are no changes to test)
- [x] Re-run test "susemanager_unittests"
- [x] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests" (Test skipped, there are no changes to test)

### CODE REVIEW

**Comment by mbussolotto** [comment]
cucumber test: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2343/

**Review by srbarrios — APPROVED** [review]
LGTM

**Comment by mbussolotto** [comment]
@mcalmer I think we can avoid changelog, right?

**Comment by mcalmer** [comment]
> @mcalmer I think we can avoid changelog, right?

yes, no need for yet another changelog

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
