### PR TITLE
Manager bsc1171687

### PR DESCRIPTION
**Pull request by mantel**
## What does this PR change?

Methods in the spacecmd shell are supposed to return meaningful result codes. This is currently not the case, so when using it in a script for single commands, also failed commands will report success by always implicitly returning 0. This is fixed with this PR for the most relevant methods.

There are still some more which will require the same fixing, but it will affect almost every method, so I wanted to fix the most urgent and frequent ones (there is a pending L3) and want to get some feedback.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: Bugfix

- [X] **DONE**

## Test coverage
- No tests: 

- [X] **DONE**

## Links

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1171687

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@mantel your change caused unit tests to fail. You need to align them as well. It seems some where written to check the return code which now has changed.

**Comment by mantel** [comment]
> @mantel your change caused unit tests to fail. You need to align them as well. It seems some where written to check the return code which now has changed.

Ah, I see.

Honestly I wonder if we really want such a big change in one go. I just created a seperate PR that will only fix the L3 for which the problem got reported. It is a general issue and every method needs to get fixed. This current PR only contains some subset as I was looking for methods dealing with system lists. But we need to touch every do_* method because the problem can happen anywhere. What do you think? Should we first simply fix the L3 and do the big change later?

https://github.com/uyuni-project/uyuni/pull/2238

**Comment by mantel** [comment]
gitarro rerun spacecmd_unittests !!!

**Comment by mantel** [comment]
gitarro rerun spacecmd_unittests !!!

**Comment by mcalmer** [comment]
> Honestly I wonder if we really want such a big change in one go. I just created a seperate PR that will only fix the L3 for which the problem got reported. It is a general issue and every method needs to get fixed. This current PR only contains some subset as I was looking for methods dealing with system lists. But we need to touch every do_* method because the problem can happen anywhere. What do you think? Should we first simply fix the L3 and do the big change later?

How big is the chance that this customer try the next command and open the next L3 when no return value is returned?

I see this more a feature as spcecmd was not working like this.
I agree that we should change it and I am also fine with doing it via L3.
But I think we can use the chance to let the customer test the big change.
Yes, he has to wait a bit longer, but I think it is ok.

**Comment by mantel** [comment]
> > Honestly I wonder if we really want such a big change in one go. I just created a seperate PR that will only fix the L3 for which the problem got reported. It is a general issue and every method needs to get fixed. This current PR only contains some subset as I was looking for methods dealing with system lists. But we need to touch every do_* method because the problem can happen anywhere. What do you think? Should we first simply fix the L3 and do the big change later?
> 
> How big is the chance that this customer try the next command and open the next L3 when no return value is returned?
> 
> I see this more a feature as spcecmd was not working like this.
> I agree that we should change it and I am also fine with doing it via L3.
> But I think we can use the chance to let the customer test the big change.
> Yes, he has to wait a bit longer, but I think it is ok.

Ok, so I will simply ask in the bug. I agree that we should fix all the methods because chances are high the issue will pop up again in the future. And now it is mainly a diligent but routine piece of work. I will continue on this PR then.

**Comment by mantel** [comment]
gitarro rerun spacecmd_unittests !!!

**Comment by paususe** [comment]
> > Honestly I wonder if we really want such a big change in one go. I just created a seperate PR that will only fix the L3 for which the problem got reported. It is a general issue and every method needs to get fixed. This current PR only contains some subset as I was looking for methods dealing with system lists. But we need to touch every do_* method because the problem can happen anywhere. What do you think? Should we first simply fix the L3 and do the big change later?
> 
> How big is the chance that this customer try the next command and open the next L3 when no return value is returned?
> 
> I see this more a feature as spcecmd was not working like this.
> I agree that we should change it and I am also fine with doing it via L3.
> But I think we can use the chance to let the customer test the big change.
> Yes, he has to wait a bit longer, but I think it is ok.

If we are going to do the big change so that every method returns what it should, we should do that in 4.1 GA, not in a maintenance update.

**Pull request merged**
