### PR TITLE
Specify the result type of the JPQL queries to get rid of warnings

### PR DESCRIPTION
**Pull request by hustodemon**
## What does this PR change?

$subj

## GUI diff

No difference.
- [x] **DONE**

## Documentation
- No documentation needed: internal stuff
- [x] **DONE**

## Test coverage
- No tests: not testable change

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
coool

**Comment by hustodemon** [comment]
To go one step further, I removed the annotation from `RescheduleException` and `DownloadFaultException` too. It does not produce any warning in my IDE, but maybe Eclipse is more sensitive. Whenever you get a minute, could you check, what happens, when you remove those `@SuppressWarnings("serial")` annotations @mcalmer ?

**Comment by mcalmer** [comment]
> To go one step further, I removed the annotation from `RescheduleException` and `DownloadFaultException` too. It does not produce any warning in my IDE, but maybe Eclipse is more sensitive. Whenever you get a minute, could you check, what happens, when you remove those `@SuppressWarnings("serial")` annotations @mcalmer ?

It produce this warning:
  `The serializable class RescheduleException does not declare a static final serialVersionUID field of type long`

**Comment by hustodemon** [comment]
Thanks for the reviews! I'll keep the annotations `RescheduleException` and `DownloadFaultException`.

**Pull request merged**
