### PR TITLE
QE: Update test suite for using Leap 15.4

### PR DESCRIPTION
**Pull request by nodeg**
## What does this PR change?

This includes some more adjustments for using openSUSE Leap 15.4 in our Uyuni CI. KVM + Cobbler tests will still fail because of the missing TFTP package I was not able to find (see e.g. https://suse.slack.com/archives/C02CKHR76Q2/p1694189245268889).
I ran all tests manually on the Uyuni CI controller. Some of the tests look a little bit different in Uyuni than in SUMA because of e.g. no child channels were selected by default due to the missing reposync.

Furthermore, I also fixed an issue in the finishing stage where we could not extract the log files due to taking special care of the nested VM. This works now again:

```bash
uyuni-master-ctl:~/spacewalk/testsuite # cucumber features/dom.feature
Capybara APP Host: https://uyuni-master-srv.mgr.suse.de:8888
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname uyuni-master-srv and FQDN uyuni-master-srv.mgr.suse.de
Node: uyuni-master-srv, OS Version: 15.4, Family: opensuse-leap
Activating HTTP API
Using the default profile...
Feature: doms tests

  Scenario: doms tests                                     # features/dom.feature:3
      This scenario ran at: 2023-09-08 18:29:19 +0200
Node: uyuni-master-srv.mgr.suse.de
    When I extract the log files from all our active nodes # features/step_definitions/command_steps.rb:510
      This scenario took: 255 seconds

1 scenario (1 passed)
1 step (1 passed)
4m15.035s
```

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- Cucumber tests were added

- [x] **DONE**

## Links

- Fixes https://github.com/SUSE/spacewalk/issues/22421
- Manager 4.3: 
- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by vandabarata — APPROVED** [review]
had an overlook, trusting you tested this :p

**Review by ktsamis — APPROVED** [review]

**Comment by nodeg** [comment]
I pushed one more commit to fix https://github.com/SUSE/spacewalk/issues/22421

**Review by rjmateus — APPROVED** [review]
LGTM

**Comment by nodeg** [comment]
image
All tests are green. Merging now.

**Pull request merged**
