### PR TITLE
added spacecmd subcommand to show whether a reboot would be needed if available patches were applied

### PR DESCRIPTION
**Pull request by tobias-d-oe**
## What does this PR change?

added spacecmd subcommand to show whether a reboot would be needed if available patches were applied

## GUI diff

No difference.

Links:
https://github.com/uyuni-project/uyuni-docs/pull/2675

### CODE REVIEW

**Review by meaksh — COMMENTED** [review]
Thanks for your contribution! It looks good to me.

@tobias-d-oe is there any chance you could implement a test for this?

Thanks!

**Comment by tobias-d-oe** [comment]
> Thanks for your contribution! It looks good to me.
> 
> @tobias-d-oe is there any chance you could implement a test for this?
> 
> Thanks!

Hi @meaksh,

if you point me to documentation I will have a look.

**Comment by meaksh** [comment]
Hey @tobias-d-oe,
with `docker` installed on your system, you can trigger the execution of the "spacecmd" tests on top of your branch by simply running:

```console
# sh susemanager-utils/testing/automation/spacecmd-unittest.sh
```

For writting the test, maybe you can have a look at other system tests implemented at https://github.com/uyuni-project/uyuni/blob/5dd7f5852b9573af47689358ab2a9058dda8ea74/spacecmd/tests/test_system.py as example.

Hth and thanks for having a look!

**Comment by tobias-d-oe** [comment]
> @tobias-d-oe did you have a chance to add unit tests here? if you need any more assistance please let me know. Thanks!

Hello measksh,

yes, I've never created such test. I've tried to, but not sure, think my test do not really test. Also I've created the spacecmd commandset for add CLM, but also for this, I thing you would need such a test-setup so I haven't opened the PR for this.
 If someone with experience could takeover the test-setup, would be great.

**Comment by meaksh** [comment]
This PR was closed as staled, but I had a chance to add the missing unit tests for this.

Since this branch has conflicts with our current `master` branch, I just created a separated PR.

Closing this one in favor of https://github.com/uyuni-project/uyuni/pull/11116

Thanks again for contributing!

**Pull request closed without merging**
