### PR TITLE
Manager bsc1169780

### PR DESCRIPTION
**Pull request by mantel**
## What does this PR change?

cobbler profiles are just one-line files, so there can be more than one single occurrence of the term "kickstart" that needs to be changed to "autoinstall" during migration to the new cobbler version; for example snippets also have been renamed this way.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: Bugfix

- [X] **DONE**

## Test coverage
- No tests: no automated migration tests

- [X] **DONE**

## Links

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1169780

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@mcalmer should we merge this for 2020.07?

**Comment by mcalmer** [comment]
This is more important for 4.1 as for uyuni. But I would say "yes" if we can.
@mantel is back on Monday. Would that be early enough?

**Comment by mantel** [comment]
> This is more important for 4.1 as for uyuni. But I would say "yes" if we can.
> @mantel is back on Monday. Would that be early enough?

I already merged it into 4.0, but merging into 4.1 was not able so far because of blocked branch.

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by mcalmer** [comment]
@juliogonzalez is this part of 4.1.1?

**Comment by juliogonzalez** [comment]
No, it seems it isn't. His squad show review all PRs from Hubert and take care of getting merged into master and backported. Ping @ncounter @hustodemon.

As an exception I will do it in this case.

**Comment by mcalmer** [comment]
> No, it seems it isn't. His squad show review all PRs from Hubert and take care of getting merged into master and backported. Ping @ncounter @hustodemon.

Hubert was in Orion, not Naica.

> As an exception I will do it in this case.

Thanks

**Pull request merged**
