### PR TITLE
Testsuite - remove duplicity scenario and use tag for suma specific one

### PR DESCRIPTION
**Pull request by lkotek**
## What does this PR change?

This PR adds tag for SUSE Manager specific scenario and removes `List all products for Uyuni` scenario as this is fully covered by the steps from previous one (`List all products for SUSE Manager`) and also is specific for SUSE Manager again.

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by calancha — APPROVED** [review]

**Comment by Bischoff** [comment]
Nice catch @lukas

**Comment by srbarrios** [comment]
I'm sorry @lkotek  but I don't agree :p 

I think we should let:

```
@scc_credentials
@uyuni
  Scenario: List all products for Uyuni
    When I execute mgr-sync "list products --expand"
```

As this will not be covered in any place when running our Uyuni CI. The fix will be to check for different products, so instead of these ones:

```
    Then I should get "[ ] SUSE Linux Enterprise Server 12 SP4 x86_64"
    And I should get "[ ] SUSE Manager Proxy 4.0 x86_64"
```

We need to check other products visible in the list :

```
uyuni-master-srv:~ # mgr-sync list products --expand
Available Products:

(R) - recommended extension

Status:
  - [I] - product is installed
  - [ ] - product is not installed, but is available
  - [U] - product is unavailableI'm sorry but I don't agree :p 

I think we should let:

```
@scc_credentials
@uyuni
  Scenario: List all products for Uyuni
    When I execute mgr-sync "list products --expand"
```

As this will not be covered in any place when running our Uyuni CI. The fix will be to check for different products, so instead of these ones:

```

```


[ ] Ubuntu 18.04
[ ] Ubuntu 16.04
[ ] RHEL5 Base x86_64
[ ] RHEL5 Base i386
[ ] RHEL6 Base x86_64
[ ] RHEL6 Base i386
[ ] RHEL7 Base x86_64
....
```

**Comment by lkotek** [comment]
@srbarrios Nothing to sorry about :-) Different opinions are welcome ;-) Btw. we still have this scenario: 
```
@scc_credentials
  Scenario: List products with filter
    When I execute mgr-sync "list products --expand --filter x86_64"
    Then I should get "[ ] SUSE Linux Enterprise Server 12 SP4 x86_64"
    And I shouldn't get "ppc64"
    And I shouldn't get "s390x"
```
The only difference is `--filter x86_64` used.

**Comment by srbarrios** [comment]
Ah right! So then it's fine! I just went through the PR and the description :)
We are good then, we can just test both together.

**Pull request merged**
