### PR TITLE
Drop handling of legacy pillar and formula files

### PR DESCRIPTION
**Pull request by nadvornik**
## What does this PR change?

This PR drops support for legacy pillar and formula files. The data was moved to the database in 4.3

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed
- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links
https://github.com/uyuni-project/uyuni/issues/7639

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]
Do we have a directory or two we can remove in the spec files too?

**Comment by nadvornik** [comment]
> Do we have a directory or two we can remove in the spec files too?

Yes, thanks for reminder.

**Review by aaannz — APPROVED** [review]

**Review by vzhestkov — APPROVED** [review]
Looks good to me :+1: I like such deprecated code drops.

**Review by parlt91 — APPROVED** [review]
I think there should be a changelog entry for the `susemanager-sls` changes. Other than that it looks good to me

**Comment by cbosdo** [comment]
> I think there should be a changelog entry for the `susemanager-sls` changes. Other than that it looks good to me

Nice catch: added

**Pull request merged**
