### PR TITLE
Add clients tool product to generate bootstrap repo on OpenSUSE 15.x (bsc#1201189)

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Currently `venv-salt-minion` is not present on OpenSUSE bootstrap repo. Add `clients tool product` to generate bootstrap repo on OpenSUSE 15.x.
## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/18306
- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]
Looks good, but should be tested.
I wonder if we should remove openSUSE 15.1 and 15.2 as both are not maintained anymore.
Maybe a question for @juliogonzalez and  @admd 

But not in this PR

**Comment by juliogonzalez** [comment]
> Looks good, but should be tested. I wonder if we should remove openSUSE 15.1 and 15.2 as both are not maintained anymore. Maybe a question for @juliogonzalez and @admd

FMPOV... not yet. You know how customers/users are. We didn't cleanup RES6 or SLE11, or EoL'ed SLE12

But of course if someone is using them and has issues -> not supported

**Comment by mbussolotto** [comment]
> Looks good, but should be tested. 
Forgot to mention in the description. I patched manually a SUMA 4.3 and created bootstrap repo for `openSUSE-Leap-15.3-x86_64-uyuni` successfully

**Comment by mbussolotto** [comment]
CI Tests https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1398/

**Comment by juliogonzalez** [comment]
@mbussolotto merged, not sure if you need to backport to 4.2 as well.

**Pull request merged**
