### PR TITLE
QE: Remove reviewers.yml

### PR DESCRIPTION
**Pull request by nodeg**
## What does this PR change?

This file is a duplication of the CODEOWNERS file so we do not need
it anymore. According to the GitHub documentation [1] the CODEOWNERS
file does exactly the same. Thanks @Etheryte for bringing this up in Slack.

> Code owners are automatically requested for review when someone opens
> a pull request that modifies code that they own. Code owners are not
> automatically requested to review draft pull requests.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: 

- [x] **DONE**

## Links

[1] https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Etheryte** [comment]
You will probably also want to remove `.github/workflows/auto_request_review.yml` since that's the workflow that uses this configuration file, unless I misunderstand the intent of it.

**Review by ktsamis — APPROVED** [review]
Thanks for this, absolutely needed. :100:

**Comment by ktsamis** [comment]
> Thanks for this, absolutely needed. 100

Karl is right, also another file would not be used if we remove that one, so remove that one as well. Sorry for the premature approval

**Comment by nodeg** [comment]
Thank you @Etheryte I missed that. I will do another commit.

**Review by ktsamis — APPROVED** [review]

**Pull request merged**
