### PR TITLE
Fix single apostrophe curly interpolation bug, add linting rule to detect it

### PR DESCRIPTION
**Pull request by Etheryte**
## What does this PR change?

Fixes the issue outlined in https://github.com/SUSE/spacewalk/pull/23026 in other similar places, also adds linting to detect it elsewhere.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by cbbayburt** [comment]
Wow that's a lot of places. Did they all really show as {name} in the UI and nobody noticed? 😮

**Comment by Etheryte** [comment]
As far as I could see, yeah. Many of them are notification messages though that you only see after you perform some specific action, so it's easy to see how it would go unnoticed.

**Comment by Etheryte** [comment]
Ping @cbbayburt @mikeletux for a review please.

**Review by cbbayburt — APPROVED** [review]
LGTM :+1:

**Pull request merged**
