### PR TITLE
Assign default reviewers for the workflows

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Assign default reviewers for the workflows.

We should probably add more contributors. If you have ideas, please ping me and I will add them to https://github.com/orgs/uyuni-project/teams/workflows-reviewers/members

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: `CODEOWNERS`changes

- [x] **DONE**

## Test coverage
- No tests:  `CODEOWNERS`changes

- [x] **DONE**

## Links

As agreed at https://github.com/SUSE/spacewalk/issues/25344

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
Not sure I want to get a review for any github action .... this is making myself the bottleneck

**Comment by juliogonzalez** [comment]
> Not sure I want to get a review for any github action .... this is making myself the bottleneck

You don't need to review every PR, that's why we are setting up a pool (as long as one person of the pool reviews, that's OK)

**Comment by cbbayburt** [comment]
Also, not everyone in the group cam review any action. Each have very different purpose and functionality. The best way this works would be if everyone reviews the ones they're familiar with.

Setting multiple groups for different actions would be too much, but let's avoid round robin on this.

**Review by nodeg — APPROVED** [review]

**Review by cbbayburt — APPROVED** [review]

**Comment by juliogonzalez** [comment]
> e in the group can review any action. Each have very different purpose and functionality. The best way this works would be if everyone reviews the ones they're familiar with.
> 
> Setting multiple groups for different actions would be too much, but let's avoid round robin on this.

Of course I meant round robin not for all of the workflows, but for those where more than one person are familiar. I didn't want to setup the round-robin assignation.

Ideally, I think we should have more people, but please let me know who we are missing for the workflows you are not aware of, and I will add them to the group :-)

**Pull request merged**
