### PR TITLE
Enable automatic bundle migration for all minions

### PR DESCRIPTION
**Pull request by agraul**
## What does this PR change?

Open the classic salt-minion.rpm -> Salt Bundle migration to all Salt versions (not just 3000).

## GUI diff

No difference.

- [x] **DONE**

## Documentation

Need to check if we document which versions will get migrated. We need to document that all minions will get turned into venv-salt-minion automatically to prevent confusion.

- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage

I updated the build validation test, but it's still WIP. Previously, `venv-salt-minion` was installed manually before running the migration. That's not what we tell our customer, I think we can skip it.

- Cucumber tests were adapted

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/23754
Port(s): Just for Uyuni and the upcoming SUMA 5.0 release

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by meaksh — APPROVED** [review]
LGTM :+1:

**Comment by nodeg** [comment]
We are testing the Salt migration in BV. From what I read, this is only the case for Uyuni and SUMA 5.0. What I did not fully understood is, when will the migration happen? During the first highstate on a particular minion/SSH minion?

**Comment by agraul** [comment]
> We are testing the Salt migration in BV. From what I read, this is only the case for Uyuni and SUMA 5.0. 

Correct.

> What I did not fully understood is, when will the migration happen? During the first highstate on a particular minion/SSH minion?

Clients managed by SSH are not affected by this change, we're already using Salt Bundle for Salt SSH. The `switch_to_bundle.mgr_switch_to_venv_minion` state is part of the highstate: https://github.com/uyuni-project/uyuni/blob/a4e2307e4140fa90559c4916b2538da9c20161f6/susemanager-utils/susemanager-sls/modules/tops/mgr_master_tops.py#L38
The first highstate after installing the updated sls files will do the migration. This setup was already in place for Salt 3000 minions, we're now migrating 3006.0 minions as well.

**Review by srbarrios — APPROVED** [review]

**Comment by agraul** [comment]
Let's include this in the 5.0 beta 2 build and start testing it in BV. I ran the acceptance test suite (partially) and didn't spot any regressions yet.

**Pull request merged**
