### PR TITLE
Remove centos6 and ubuntu16 from testsuite

### PR DESCRIPTION
**Pull request by ktsamis**
## What does this PR change?

Remove centos6 and ubuntu16 from testsuite, they are both EOL. I deliberately didn't remove any mention of `POS_Image_JeOS6_head` and `POS_Image_JeOS6` because they are needed for retail kiwi tests, correct @lkotek ?

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/14778
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by ktsamis** [comment]
The java test exceeded the timeout but it's irrelevant, we don't need it for this PR.

**Review by srbarrios — APPROVED** [review]
Perfect.

Just three notes:

- In our `get_os_version` we have an exception for CentOS6, if there is no need for it, let's remove it too.
- Remember to clean up the mirror and the salt states for the mirrors
- Agree with Moio/Ricardo if we remove it also from sumaform, including the mirror provided inside sumaform

**Comment by ktsamis** [comment]
I deliberately didn't remove that detection just in case that we had a similar case that we wanted to have for later versions, basically without the correct detection a lot of other things would fail. I will remove it though no problem. About sumaform I don't think we should remove it. Others from the community are using the tool and they might (for whatever reason) want to deploy a centos6 or ubuntu16 image

**Comment by srbarrios** [comment]
> I deliberately didn't remove that detection just in case that we had a similar case that we wanted to have for later versions, basically without the correct detection a lot of other things would fail. I will remove it though no problem. About sumaform I don't think we should remove it. Others from the community are using the tool and they might (for whatever reason) want to deploy a centos6 or ubuntu16 image

I don't agree about sumaform mirror config, I think we should remove it from Head links (even 4.1), if we will not support it anymore.

https://github.com/uyuni-project/sumaform/blob/master/salt/mirror/minima.yaml

**Comment by ktsamis** [comment]
> I don't agree about sumaform mirror config, I think we should remove it from Head links (even 4.1), if we will not support it anymore.
> 
> https://github.com/uyuni-project/sumaform/blob/master/salt/mirror/minima.yaml

You are absolutely correct about that one. I didn't read it properly and thought you meant the image urls. The mirror config I will remove yes

**Comment by ktsamis** [comment]
> > I don't agree about sumaform mirror config, I think we should remove it from Head links (even 4.1), if we will not support it anymore.
> > https://github.com/uyuni-project/sumaform/blob/master/salt/mirror/minima.yaml
> 
> You are absolutely correct about that one. I didn't read it properly and thought you meant the image urls. The mirror config I will remove yes

This was done in https://github.com/uyuni-project/sumaform/pull/884

**Comment by ktsamis** [comment]
Sorry for asking again for review, I messed up a bit with the commits and needed to redo the changes manually. Just want to make sure nothing is missing.

**Review by srbarrios — APPROVED** [review]
It seems all good :)
Thank you again

**Pull request merged**
