### PR TITLE
Content Lifecycle Management

### PR DESCRIPTION
**Pull request by lneves12**
## What does this PR change?

Content Lifecycle Management - First implementation for BETA 2

### Implemented features
- Create/Read/Update/Delete:
  - Content Project
  - Environment
- attach/detach Content Sources to/from Content Project
- build Content Project
- promote Environment to the successor Environment

### Included PRS
This PR is an aggregation of the following PRs:
* Backend and XMLRPC
https://github.com/uyuni-project/uyuni/pull/499
https://github.com/uyuni-project/uyuni/pull/545
https://github.com/uyuni-project/uyuni/pull/642
https://github.com/uyuni-project/uyuni/pull/755 (superseded by https://github.com/uyuni-project/uyuni/pull/761)
* Frontend
https://github.com/uyuni-project/uyuni/pull/414
https://github.com/uyuni-project/uyuni/pull/430
https://github.com/uyuni-project/uyuni/pull/686
https://github.com/uyuni-project/uyuni/pull/745

## GUI diff
See the Frontend PRs above.

- [x] **DONE**

## Documentation
https://github.com/SUSE/spacewalk/issues/7445

- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

### CODE REVIEW

**Comment by lneves12** [comment]
I rebased and tested everything, it's looking good. :+1: 

Please take a quick review into my last 3 commits, it should be quick.

They add validations to the content project label on the project creation and fix this bug: https://github.com/SUSE/spacewalk/issues/7436

**Comment by hustodemon** [comment]
@lneves12 Both the bugfix and the validation look good to me! As for the validation, we should make use of it in the xmlrpc too. Let's discuss this later.

**Comment by ncounter** [comment]
@juliogonzalez : thanks a lot for your quick review pointing out those issues. I addressed all of them. I will wait now for the PR tests to complete.

**Comment by hustodemon** [comment]
The contents look good. Let me adjust the PR description.

**Pull request merged**
