### PR TITLE
Fix persisting the Cobbler UID in the database via XML-RPC createSystemRecord

### PR DESCRIPTION
**Pull request by SchoolGuy**
## What does this PR change?

TODO

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- Cucumber tests were added - https://github.com/uyuni-project/uyuni/pull/6628

- [x] **DONE**

## Links

Fixes [#](https://github.com/SUSE/spacewalk/issues/20333)
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by SchoolGuy** [comment]
The PR is working as expected in a test environment. Thus I will now start writing Unit Tests with Mockito (as discussed internally).

**Comment by SchoolGuy** [comment]
Git History is clean and Sonarlint should be happy about this PR. Tests need fixing as they are skeletons only at the moment.

**Comment by nodeg** [comment]
Any updates on this?

**Comment by ycedres** [comment]
@nodeg I'm currently working on getting this PR in shape so it can be merged.

**Comment by nodeg** [comment]
Thank you for the update, Yeray!

**Comment by meaksh** [comment]
Closing in favor of https://github.com/uyuni-project/uyuni/pull/7738

**Pull request closed without merging**
