### PR TITLE
RFC: Cleanup Cobbler XML-RPC client usage

### PR DESCRIPTION
**Pull request by SchoolGuy**
## What does this PR change?

This PR is reworking how the `CobblerClient` is used internally in the codebase. This is cleanup work to prepare the possible obsoletion of `com/redhat/rhn/taskomatic/task/CobblerSyncTask.java` and its sibling commands

- `com/redhat/rhn/manager/kickstart/cobbler/CobblerDistroSyncCommand.java`
- `com/redhat/rhn/manager/kickstart/cobbler/CobblerProfileSyncCommand.java`

This work is performed in the context of the L3 that is being tracked below.

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- No tests: already covered

- [x] **DONE**

## Links

Tracks [#20326](https://github.com/SUSE/spacewalk/issues/20326)

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by SchoolGuy** [comment]
I would love to get comments whether or not it is reasonable to abstract the `CobblerClient` class with an interface to make testing easier because we don't extend the real implementation anymore but instead implement the interface. Depending on the answer I will perform the discussed action or drop the `FIXME`.

**Review by cbosdo — APPROVED** [review]
LGTM, but maybe some commits should be squashed

**Comment by SchoolGuy** [comment]
@cbosdo Do we want to have an interface for `CobblerClient` or do we want to stick to the current way of extending the base class inside the tests?

**Comment by cbosdo** [comment]
> @cbosdo Do we want to have an interface for `CobblerClient` or do we want to stick to the current way of extending the base class inside the tests?

The new way seems to be to use an interface, but I suspect this is a matter of taste. Maybe @lucidd has an opinion

**Comment by lucidd** [comment]
It usually depends on a few things i like having an interface just to define the public api and put documentation there. For testing it depends a bit what and how you test if you clearly test something just using a client for a particular scenario or if you want to rely on the particular behavior of the implementation and just have to switch out certain parts. I'd say write the tests and add the interface later if you feel like its needed.

**Comment by SchoolGuy** [comment]
@lucidd At the moment we do already have the tests. However, the client per default opens a real network connection to Cobbler. This is undesired and as such I was thinking if overriding the Client to prevent it from making the network connection is the way to go or if it shouldn't be more desired to just have an interface that returns the desired data directly. In SUMA in most places we don't want to test the client itself but rather the classes that use the client. Having an interface would enable us to use dependency injection to insert the test client.

**Comment by cbosdo** [comment]
In such a case an interface implemented with only the data you want for the test may be the best thing to do: quick and easy to read

**Comment by cbosdo** [comment]
Do we want this PR closed?

**Comment by cbbayburt** [comment]
> Do we want this PR closed?

I think this could be still relevant, but someone needs to take responsibility for it. It needs to be properly tested.

**Pull request closed without merging**
