### PR TITLE
Don't add the request to the jade shared variables

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

When adding the HTTP Request to the jade share variables we sometimes
get invalid sessions and thus cannot render the navigation tabs.

It doesn't make any sense to store the request object there, instead use
it to change the context of the template rendering.

In order to make this simpler add `withUserAndSystem()` spark helpers to
be used along with the system-common jade template.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes
- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/14119

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by lucidd** [comment]
Maybe i missed it but i don't see the change where it removes the code that injects the request into the globally shared variables. It would also be nice to move the `sharedVariables` declaration and the whole jade engine initialization at the very end of the `setup` function that its after `Spark.before` and `Spark.exception` so its not in scope for those to use to prevent any bad ideas.

**Comment by srbarrios** [comment]
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/303/console

**Comment by cbosdo** [comment]
> https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/303/console

looks like the `terraform apply` exploded :bomb: :boom:

**Comment by cbosdo** [comment]
> Maybe i missed it but i don't see the change where it removes the code that injects the request into the globally shared variables. 

Nice catch! By wanting to remove it only at the end I forgot about it.

>It would also be nice to move the `sharedVariables` declaration and the whole jade engine initialization at the very end of the `setup` function that its after `Spark.before` and `Spark.exception` so its not in scope for those to use to prevent any bad ideas.

:+1:

**Comment by cbosdo** [comment]
@lucidd just changed according to your comment

**Review by renner — APPROVED** [review]
Good patch, it looks really good to me, tank you! :+1:

**Pull request merged**
