### PR TITLE
Add spacecmd function: cryptokey_update

### PR DESCRIPTION
**Pull request by blu-base**
## What does this PR change?

`spacecmd` has function for most API calls for managing SSL/GPG keys, such as creating and deleting. There also is an API call [to update](https://www.uyuni-project.org/uyuni-docs-api/uyuni/api/kickstart.keys.html#apidoc-kickstart_keys-update-loggedInUser-description-type-content) keys. However, the function to update a key is missing in `spacecmd`.

This PR adds the function `cryptokey_update` to update SSL/GPG keys in the same way as creating them via `spacecmd`.

Discussion point:  
This mostly duplicates code present in the `cryptokey_create` function, respectively the method `do_cryptokey_create` in `/spacecmd/src/spacecmd/cryptokey.py` and its test. It might be advantageous to extract the common logic between the create, and update function. Would you suggest further such work?

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- Doc strings for new python functions
- Documentation issue was created: Pending

- [ ] **DONE**

## Test coverage

- Unit tests were added

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

spacecmd.changes: - Add spacecmd function: cryptokey_update

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [x] Re-run test "backend_unittests_pgsql"
- [x] Re-run test "java_pgsql_tests"
- [x] Re-run test "schema_migration_test_pgsql"
- [x] Re-run test "susemanager_unittests"
- [x] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by blu-base** [comment]
Oh well, the bot is the same opinion, this is too much duplication...

**Comment by ycedres** [comment]
Thank you very much for the PR. 
Maybe what you could do to reduce code duplicaton is writing the common code between `do_cryptokey_create` and `do_cryptokey_create` in a separate function. In that way you would have one call to this common function followed by a call to  `self.client.kickstart.keys.create` or `self.client.kickstart.keys.update`.

**Review by ycedres — COMMENTED** [review]
Thank you very much for the PR.
Maybe what you could do to reduce code duplicaton is writing the common code between do_cryptokey_create and do_cryptokey_create in a separate function. In that way you would have one call to this common function followed by a call to self.client.kickstart.keys.create or self.client.kickstart.keys.update.

**Comment by meaksh** [comment]
> Thank you very much for the PR. Maybe what you could do to reduce code duplicaton is writing the common code between `do_cryptokey_create` and `do_cryptokey_create` in a separate function. In that way you would have one call to this common function followed by a call to `self.client.kickstart.keys.create` or `self.client.kickstart.keys.update`.

Oops, there was a typo on the previous message.

I think what @ycedres meant here is that you could refactor common code between `do_cryptokey_create` and `do_cryptokey_update` to avoid code code duplication.

@blu-base any chance to make these changes?

Thanks in advance!

**Comment by blu-base** [comment]
I was having trouble setting up a test environment with sumaform. I lacked training in terraform, so it was time-consuming to figure out my configuration issues. 

Leave me a few days to improve this pr.

**Comment by blu-base** [comment]
This should be ready for another look.

**Review by meaksh — APPROVED** [review]
Thanks for the changes. LGTM!

**Pull request merged**
