### PR TITLE
QA: Proxy not anymore a router

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

We don't want the proxy to be a router anymore

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were changed

- [x] **DONE**

## Links

Ports:
- Manager-4.1
- Manager-4.2

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by srbarrios** [comment]
We also need to merge  #4580 

Test using this branch plus #4580 
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1020/console

**Review by Bischoff — APPROVED** [review]
lgtm, but please test what happens when it's run - I hope the formula still works when this field is left blank

**Comment by srbarrios** [comment]
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1029/console

**Comment by srbarrios** [comment]
As seen with @mcalmer , CI seems to work without it at that point.... so maybe there is no need for it.
@Bischoff I would like in any case that after holidays you take a look to it, for now closing that one.

**Pull request closed without merging**
