### PR TITLE
CI: enable openscap test

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

CI: enable openscap tests given they pass.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed
- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links

[Issue(s)](https://github.com/SUSE/spacewalk/issues/20958)

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
Tests passed. Retriggering to see if they are stable.

**Comment by jordimassaguerpla** [comment]
Tests passed. We can consider this stable.

**Review by NamelessOne91 — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
Tests took 33 minutes, same as before.

**Review by srbarrios — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
This adds 59 steps of a total of 8485, increasing coverage by 0.7

**Comment by jordimassaguerpla** [comment]
Superseded by https://github.com/uyuni-project/uyuni/pull/8929

**Pull request closed without merging**
