### PR TITLE
Upgrade spacewalk package to postgresql13

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

This commit upgrades the spacewalk package to require postgresql13.

partial fix for https://github.com/SUSE/spacewalk/issues/13220

## GUI diff

No difference.

- [X] **DONE**

## Documentation

- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/13300), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/711).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [x] **DONE**

## Test coverage
- No tests: We need to check for regressions, no need additional tests.

- [X] **DONE**

## Links

Fixes #
Tracks # https://github.com/SUSE/spacewalk/issues/13220

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [X] DONE

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [x] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
RHEL8 does not shop with PostgreSQL13. Would we link to an external repository for PostgeSQL or actually rebuild it in OBS?

**Comment by mcalmer** [comment]
I would suggest to stay with postgres12 on rhel.

**Comment by jordimassaguerpla** [comment]
@mcalmer do you mean staying with this else clause https://github.com/uyuni-project/uyuni/blob/master/spacewalk/package/spacewalk.spec#L129 ? Or should I create an "if rhel" clause?

**Comment by sbluhm** [comment]
@jordimassaguerpla I have not submitted my changes for RHEL yet. So if you don't do it, I will consider these changes then.

**Comment by mcalmer** [comment]
@jordimassaguerpla I would suggest to stay with the %else as it is now pointing to 12.
We will see if we in future need a `%if 0%{?rhel}` or not.

**Comment by keichwa** [comment]
Do you think we should already start documenting it?  If yes, anything special we must consider?

**Comment by jordimassaguerpla** [comment]
> Do you think we should already start documenting it? If yes, anything special we must consider?

I have not finish testing, so I would wait until I have the results.

**Comment by jordimassaguerpla** [comment]
When starting a suma server, postgresql can't start because it encounters the wal_keep_segments option, more precisely:

```unrecognized parameter "wal_keep_segments" in file "/var/lib/pgsql/data/postgresql.conf"```

Which means it makes it more difficult to have only one configuration file for both pg12 and pg13, which was the initial idea by having both, wal_keep_size (pg13) and wal_keep_segments (pg12).

**Comment by mcalmer** [comment]
> When starting a suma server, postgresql can't start because it encounters the wal_keep_segments option, more precisely:
> 
> `unrecognized parameter "wal_keep_segments" in file "/var/lib/pgsql/data/postgresql.conf"`
> 
> Which means it makes it more difficult to have only one configuration file for both pg12 and pg13, which was the initial idea by having both, wal_keep_size (pg13) and wal_keep_segments (pg12) in /var/lib/pgsql/data/postgresql.conf .

The idea is, that smdba detect which version of postgresql is running and depending on this info, it select the correct options.

**Comment by jordimassaguerpla** [comment]
> > When starting a suma server, postgresql can't start because it encounters the wal_keep_segments option, more precisely:
> > `unrecognized parameter "wal_keep_segments" in file "/var/lib/pgsql/data/postgresql.conf"`
> > Which means it makes it more difficult to have only one configuration file for both pg12 and pg13, which was the initial idea by having both, wal_keep_size (pg13) and wal_keep_segments (pg12) in /var/lib/pgsql/data/postgresql.conf .
> 
> The idea is, that smdba detect which version of postgresql is running and depending on this info, it select the correct options.

Got it. I didn't know that smdba was setting this option. This should fix it:

https://build.suse.de/package/rdiff/Devel:Galaxy:Manager:TEST/smdba?opackage=smdba&oproject=Devel%3AGalaxy%3AManager%3AHead&rev=4

**Comment by mcalmer** [comment]
@jordimassaguerpla yes, but do you know that smdba has a git? https://github.com/SUSE/smdba
Using a patch for testing is fine.

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla yes, but do you know that smdba has a git? https://github.com/SUSE/smdba
> Using a patch for testing is fine.

This is where the patch comes from ;)

Once tests are green, I would vote for merging https://github.com/SUSE/smdba/pull/41 and creating a new smdba release. How/who creates the releases there?

**Comment by mcalmer** [comment]
Creating a release is pretty manual here.
I think there are two files with a "version". Change them both to 1.7.6(?) and make a commit.
I think I created tags manual.

Then call `build-src.sh` from the git root and it will create a tar-ball .
Copy that to the buildsevice, write a changelog, adapt the spec file and commit.

**Comment by mcalmer** [comment]
Ok, do a SR :-)

**Comment by jordimassaguerpla** [comment]
See https://github.com/SUSE/smdba/pull/42

**Review by mcalmer — APPROVED** [review]
Give it a try

**Pull request merged**
