### PR TITLE
Remove ABRT and the "Software Crashes" feature

### PR DESCRIPTION
**Pull request by ricardoasmarques**
## What does this PR change?

This PR removes the **ABRT** and the "**Software Crashes**" feature which includes removing all related WebUI and command-line parts as well as the corresponding database tables.

## GUI diff

Before:

Screenshot from 2021-01-13 16-33-49

After:

All "Sofware Crashes" occurrences were removed, including the one from the left main menu.

- [x] **DONE**

## Documentation
- Documentation PR: https://github.com/uyuni-project/uyuni-docs/pull/770

- [x] **DONE**

## Test coverage
- No tests: This PR only removes features, so it does not add any tests.

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/13075

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by moio** [comment]
@mcalmer we were reflecting on the client-side implications of this:

 - here we are dropping the spacewalk-abrt package from the git repo (spec/changes). We expect this to be fine for Uyuni
 - we should not remove the package from the Internal Build Service though, as client tools are shared by all (SUSE Manager) versions. So 4.0/4.1 users will still need spacewalk-abrt until the respective products are EOL'd
 - IIUC, it will not be possible to just add a `Conflicts` on some other package to `spacewalk-abrt` to make sure is removed on upgrade, exactly because that would remove it on 4.0 and 4.1 as well
 - thus, we should somehow tell users they need to remove `spacewalk-abrt` from their clients if they are on 4.2 or Uyuni
 - for sure, we should at least inform users in case some of the dropped API calls are used (backend/server/handlers/xmlrpc/abrt.py)

Is this correct? Do you have any notes to add?

**Comment by mcalmer** [comment]
@moio good points. I think we need to discuss with @paususe what we say about our support statement for it.

If we remove spacewalk-abrt from master we cannot maintain it anymore in the client tools. So customers with 4.1, where this feature still exists on the server side, cannot get updates anymore. L3 for this would also be funny.

I wonder if we can remove support for it in all versions ?

Other possibility: we keep the client package and drop only the server side. As soon as the 4.1 goes EOL we can drop the client package as well.

**Comment by ricardoasmarques** [comment]
Package build succeed: https://ci.suse.de/view/Manager/view/Manager-Test/job/manager-TEST-Hexagon-2obs/1599/

**Comment by paususe** [comment]
I think @mcalmer 's proposal of dropping the server side now and waiting until 4.1 goes EOL to remove the client toom makes sense.

**Comment by ricardoasmarques** [comment]
This PR is dropping code from the following components:
- `backend/*`
- `client/tools/spacewalk-abrt/*`
- `java/*`
- `reporting/*`
- `schema/*`
- `spacecmd/*`

@mcalmer Just to make sure I understood correctly, by "_dropping the server-side only_" you mean the WebUI interface only, which means we should only drop code under `java/*` for now, is this assumption correct?

**Comment by mcalmer** [comment]
> This PR is dropping code from the following components:
> 
> * `backend/*`
> * `client/tools/spacewalk-abrt/*`
> * `java/*`
> * `reporting/*`
> * `schema/*`
> * `spacecmd/*`
> 
> @mcalmer Just to make sure I understood correctly, by "_dropping the server-side only_" you mean the WebUI part only, which means we should only drop code under `java/*` for now, is this assumption correct?

~~* `client/tools/spacewalk-abrt/*`~~
~~* `spacecmd/*`~~

Keep these two ^^^^ .
All the other are server side and can be dropped

**Comment by ricardoasmarques** [comment]
> ~* `client/tools/spacewalk-abrt/*`~
> ~* `spacecmd/*`~
> 
> Keep these two ^^^^ .
> All the other are server side and can be dropped

@mcalmer But the client depends on the server, so I'm afraid I have to keep at least the `xmlrpc` API and the `schema` (because we cannot drop tables yet)

**Comment by moio** [comment]
> @mcalmer But the client depends on the server,

How exactly?

**Comment by mcalmer** [comment]
We document that with 4.2 server this is not working anymore and everybody should de-install spacewalk-abrt. 
AFAIK our java API has a version which can be checked. So in theory it would be possible to check the API version in spacecmd and exit with a nice error when somebody calls functions which you remove.

**Comment by ricardoasmarques** [comment]
> > @mcalmer But the client depends on the server,
> 
> How exactly?

@moio Some `spacecmd` commands like `system_listcrashedsystems` will call the `xmlrpc` API.

**Comment by ricardoasmarques** [comment]
> We document that with 4.2 server this is not working anymore and everybody should de-install spacewalk-abrt.
> AFAIK our java API has a version which can be checked. So in theory it would be possible to check the API version in spacecmd and exit with a nice error when somebody calls functions which you remove.

But that assumes we will change `spacecmd` code in a way that those commands will display a message explaining that this feature is no longer available, this this will **not** work if user upgrades the `server` without upgrading the `spacecmd`.

If we want to display the correct message, event for older `spacecmd` versions, we need to keep `xmlrpc` API but change it to simply return an error message explayning that it's no longer available.

**Comment by ricardoasmarques** [comment]
So, my understanding is that we have the following dependencies: 

- `spacewalk-abrt` calls `backend/xmlrpc` which depends on `schema`

- `spacecmd` calls `java/xmlrpc` which depends on `schema`

- `spacewalk-report` depends on `schema`

**Comment by moio** [comment]
@ricardoasmarques hmm, not really, I can probably explain in a better way.

Keep in mind this is the `master` branch, which has three properties:
1. changes here impact Uyuni. _Server and client side_ codebases
2. changes here impact SUSE Manager's major version (4.2). _Server and client side_ codebases
3. changes here **also** impact the currently maintained SUSE Manager's major version (4.1). _But client side **only**_! And only at the time when 4.2 is released. This is the tricky part!


Reason for 3. is that we only have one client-side codebase across all major SUSE Manager versions. Currently, the `Manager-4.1` branch hosts client side code for both the 4.0 and 4.1 versions. When release time for 4.2 comes, then we will switch the branch to `Manager-4.2` for all client side code - at that point 4.1 and 4.2.


So dropping anything which is on the Server side (eg. Web UI, schema, Java XMLRPC APIs, Python XMLRPC APIs, spacecmd...) is fine here in this branch. We just have to keep in mind that those will not be dropped from all versions, so we can't yet remove any bits that go to the client side (eg. `spacewalk-abrt`) as we have to keep them for 4.1 (which retains the Server-side bits).

The client side bits should be documented though (now that you found them) - so that when the next major release comes and no supported release has the Server-side bits any more, we can drop the client-side bits without redoing work.

Does this make sense to you?

**Comment by ricardoasmarques** [comment]
> Reason for 3. is that we only have one client-side codebase across all major SUSE Manager versions. Currently, the `Manager-4.1` branch hosts client side code for both the 4.0 and 4.1 versions. When release time for 4.2 comes, then we will switch the branch to `Manager-4.2` for all client side code - at that point 4.1 and 4.2.

@moio Ok, now I understand https://github.com/uyuni-project/uyuni/pull/3122#issuecomment-760853180.

One thing that I would like to clarify is which components are considered client-side codebase, so they follow the "branch" rule you described, is the following list correct?

**SERVER-SIDE**
- backend/xmlrpc
- java/xmlrpc
- schema
- webapp
- spacecmd
- spacewalk-report

**CLIENT-SIDE**
- spacewalk-abrt

**Comment by ricardoasmarques** [comment]
Assuming that my previous comment is correct, and the only part that is considered "client-side" is the `spacewalk-abrt`, I've now updated this PR to **NOT** remove `spacewalk-abrt` (everything else is being removed as before), which means we are now removing the following parts:
- backend/xmlrpc
- java/xmlrpc
- schema
- webapp
- spacecmd
- spacewalk-report

**Comment by mcalmer** [comment]
@ricardoasmarques `spacecmd` is in the client tools repository

**Comment by ricardoasmarques** [comment]
> @ricardoasmarques `spacecmd` is in the client tools repository

@mcalmer Thanks for the hint, I've now updated this PR to **BUMP java API version**, and **NOT** remove `spacecmd` commands.

1. If `client` is updated, but `server` is not updated yet, the following "warning" message will be displayed:
```
server:~ # spacecmd -- system_listcrashedsystems
INFO: Connected to https://server.tf.local/rpc/api as admin
WARNING: This method is deprecated and will be removed in API version 25

Count | System ID | Profile Name
--------------------------------
...
```

2. If both `client` and `server` are updated, the following "error" message will be displayed:
```
server:~ # spacecmd -- system_listcrashedsystems
INFO: Connected to https://server.tf.local/rpc/api as admin
ERROR: This method was removed since API version 25
```

3. If `server` is updated, but `client` is not updated yet, the following "error" message will be displayed:
```
server:~ # spacecmd -- system_listcrashedsystems
INFO: Connected to https://server.tf.local/rpc/api as admin

Count | System ID | Profile Name
--------------------------------
ERROR: The specified handler cannot be found
```

-----

Latest summary of this PR is:

**REMOVED**
- backend/xmlrpc
- java/xmlrpc
- schema
- webapp
- spacewalk-report

**UPDATED**
- spacecmd

**UNTOUCHED**
- spacewalk-abrt

**Comment by ricardoasmarques** [comment]
This PR is now ready for review.

**Comment by Conan-Kudo** [comment]
I'm surprised, I would have figured you folks would have an ABRT and retrace server system for crash report handling. I vaguely recall that the ABRT packages build and run on SUSE distributions...

**Comment by mcalmer** [comment]
I tried some years ago to build it. It required tons of other packages we did not had and the code flow was not really understandable. I traced the communication and it was always "calling home" and I did not find a way to disable sending data to a fedora server.
So this was never really running on SLE and openSUSE.

**Comment by Conan-Kudo** [comment]
That doesn't seem right...

Aside from libreport and satyr (both of which are part of ABRT project), it uses exclusively dependencies that are already in SUSE distributions.  Unless you deploy the retrace server in openSUSE infrastructure, you'd just have to disable the retrace plugin at build time and set the bug reporting URL to point to the SUSE Bugzilla. @xsuchy, is there something I'm missing here?

**Review by mcalmer — APPROVED** [review]
Looks good, but before you merge please check the database schema migration directory again.
AFAIK we are about to release a new Uyuni version and a SUMA one and this PR may go in after all of this.
So the schema migration may need to go into a different directory.

**Comment by xsuchy** [comment]
ABRT Analytics is pretty trivial to set up. We have a bunch of documentation for that:

- https://abrt.github.io/faf/container/2017/09/20/FAF-in-container/
- https://abrt.github.io/abrt/ansible/faf/url/setup/2017/10/15/ABRT-ansible-faf-url-setup/
- https://abrt.github.io/faf/container/openshift/2018/03/05/self-contained-faf/

**Pull request merged**
