### PR TITLE
spacewalk-setup: Support cobbler 3.2.0+

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

The config file name /etc/cobbler/settings changes with cobbler 3.2.1 to /etc/cobbler/settings.yaml.
This PR replaces the config file in spacewalk-setup.cobbler in case cobbler is > 3.2.0.
This PR can be reversed and adapted once the minimum supported version is 3.2.2. (or 3.3.1)

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

Manually tested build and installation on AlmaLinux 8 and Leap 15.3 using different cobbler versions.

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
@SchoolGuy , gently chasing :)

**Comment by SchoolGuy** [comment]
@sbluhm I now started our full internal testsuite on this PR and will try to test manually as well as doing the code review today.

**Review by SchoolGuy — APPROVED** [review]
Codewise this is okay for me. Of course as the comment says we need to remove this once we do ship a more recent version of Cobbler per default.

**Comment by SchoolGuy** [comment]
@vzhestkov @agraul @meaksh Could you please double check that I haven't forgotten anything?

Link to internal testsuite run: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/900/

**Comment by SchoolGuy** [comment]
@sbluhm `master` is blocked atm in preparation for the next release, so you need to rebase after the next Uyuni release because of the changelog I believe.

**Review by vzhestkov — APPROVED** [review]
Looks good

**Comment by SchoolGuy** [comment]
I couldn't find any problems in the testsuite (the Salt error is unrelated I believe). With manual testing I couldn't find problems. So let's wait until the branch is unfrozen.

**Comment by sbluhm** [comment]
@mcalmer, any chance to sneak this into the current release or is the risk too high? That would give me an overall clean base with the next version already.

**Comment by mcalmer** [comment]
> @mcalmer, any chance to sneak this into the current release or is the risk too high? That would give me an overall clean base with the next version already.

We better ask @juliogonzalez - He is responsible for the release

**Comment by juliogonzalez** [comment]
Adding the `merge-candidate` label. As soon as we have acceptable results on the acceptance tests with the salt bundle included, this will get merged.

**Comment by juliogonzalez** [comment]
@sbluhm, I just merged the PR.

**Pull request merged**
