### PR TITLE
Almalinux mirrorlist urls

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Use mirrorlist URLs for Alma Linux 8

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **manual**

- [x] **DONE**

## Links

Port of https://github.com/SUSE/spacewalk/pull/16330

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@juliogonzalez I think in master we need to change the URLs in spacewalk-common-channels.ini as well, right?

**Comment by juliogonzalez** [comment]
@mcalmer are you sure this PR makes sense? I see https://github.com/SUSE/spacewalk/issues/14388 is still pending.

**Comment by mcalmer** [comment]
> @mcalmer are you sure this PR makes sense? I see [SUSE/spacewalk#14388](https://github.com/SUSE/spacewalk/issues/14388) is still pending.

We need to merge both at the same point in time.

**Comment by juliogonzalez** [comment]
> > @mcalmer are you sure this PR makes sense? I see [SUSE/spacewalk#14388](https://github.com/SUSE/spacewalk/issues/14388) is still pending.
> 
> We need to merge both at the same point in time.

Ok, if https://github.com/uyuni-project/uyuni/pull/4324 is the fix, then it makes sense.

We need two things:

1. Adapting `spacewalk-common-channels.ini`
2. A SQL script to change already created repositories, more or less what we did for the CentOS6 EoL.

**Comment by mcalmer** [comment]
Ahhh, *this* PR is duplicate of https://github.com/uyuni-project/uyuni/pull/4449 . I'll keep this one and close this other

**Pull request merged**
