### PR TITLE
Remove cobbler synchronization when adding system

### PR DESCRIPTION
**Pull request by m-czernek**
## What does this PR change?

When using the API to add a system, the API explicitly triggers a Cobbler synchronization. This should not be necessary because:

a) Cobbler shouldn't need a sync after adding a system
b) There is the `cobbler-sync-default` task in SUMA to schedule Cobbler sync periodically.

The default cadence of executing the `cobbler-sync-default` is every minute. This can be computationally expensive in large environments that add/remove a lot of systems in a short period of time, esp. because one `cobbler sync` can take longer than 5 minutes.

In this PR, I'm increasing the default schedule from 1 minute to every 5 minutes.

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage
- No tests: already covered

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/23775

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by rjmateus** [comment]
@aaannz would this somehow affect Retail scenarios?

**Comment by aaannz** [comment]
No, we are not using this API and our saltboot system create is not calling sync after anyway.

**Review by aaannz — APPROVED** [review]
LGTM, but changelog should have bug reference.

**Review by aaannz — APPROVED** [review]
👍🏾

**Pull request merged**
