### PR TITLE
Change sources to DEB822 format when apt >= 2.7.12 (Ubuntu 24.04)

### PR DESCRIPTION
**Pull request by mayrstefan**
## What does this PR change?

This changes the repository sources file format to DEB822 starting with Ubuntu 24.04 (which uses apt 2.7.12)

## GUI diff

No difference.

## Documentation
- No documentation needed: only internal and user invisible changes for not yet supported OS (Ubuntu 24.04 and future Debian versions)

## Test coverage
- No tests: Did not find a test for repository sources

- [ ] **DONE**

## Links

Issue(s): #8448
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by meaksh — DISMISSED** [review]

**Comment by stasjok** [comment]
Should it also remove old `susemanager:channels.list`? What if system is upgraded from previous release?

**Comment by mayrstefan** [comment]
> Should it also remove old `susemanager:channels.list`? What if system is upgraded from previous release?

I'm not sure if this is addressed by susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls. 
Or do you think this code has to be duplicated to susemanager-utils/susemanager-sls/salt/channels/init.sls?

**Comment by stasjok** [comment]
> > Should it also remove old `susemanager:channels.list`? What if system is upgraded from previous release?
> 
> I'm not sure if this is addressed by susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls. Or do you think this code has to be duplicated to susemanager-utils/susemanager-sls/salt/channels/init.sls?

I'm not a maintainer here. I meant `channels/init.sls`. I considered a case when system is already managed with older apt or older version of uyuni. Then when something is updated salt can leave old .list file unmanaged, resulting in a duplicate repo definitions that can cause troubles later. That's why I think it makes sense to remove other file.

**Comment by mayrstefan** [comment]
> > > Should it also remove old `susemanager:channels.list`? What if system is upgraded from previous release?
> > 
> > 
> > I'm not sure if this is addressed by susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls. Or do you think this code has to be duplicated to susemanager-utils/susemanager-sls/salt/channels/init.sls?
> 
> I'm not a maintainer here. I meant `channels/init.sls`. I considered a case when system is already managed with older apt or older version of uyuni. Then when something is updated salt can leave old .list file unmanaged, resulting in a duplicate repo definitions that can cause troubles later. That's why I think it makes sense to remove other file.

I've added the file removal to be sure

**Pull request merged**
