### PR TITLE
CI: build api docs

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

This builds the API docs so we can test changes like https://github.com/uyuni-project/uyuni/actions/runs/8645765435/job/23703636429?pr=8588
Thanks @bisht-richa 

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed
- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links
Issue: https://github.com/SUSE/spacewalk/issues/18335 https://github.com/SUSE/spacewalk/issues/20744

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]

**Review by deneb-alpha — APPROVED** [review]
from what I see, LGTM. please,  check the  failed tests before merging

**Review by Etheryte — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
From time to time, there is a timeout when building the apidocs, a timeout coming from the disc.

**Comment by jordimassaguerpla** [comment]
> From time to time, there is a timeout when building the apidocs, a timeout coming from the disc.

```
  [javadoc] Visiting unknown tag: apidoc.returntype
  [javadoc] Call Return content: #return_array_begin()
  [javadoc]       #struct_begin("action")
  [javadoc]           #prop_desc("int", "failed_count", "Number of times action failed.")
  [javadoc]           #prop_desc("string", "modified", "Date modified. (Deprecated by
  [javadoc]                      modified_date)")
  [javadoc]           #prop_desc($date, "modified_date", "Date modified.")
  [javadoc]           #prop_desc("string", "created", "Date created. (Deprecated by
Error: timed out waiting for file /var/lib/containers/storage/overlay-containers/17667f41b6b35f6941135e4f1a101476de41e3f700ba565f43a1f5428ffd347c/userdata/174a396d79a42470dd7c4c3525870571bcf595407283f7baad5326638f592b68/exit/17667f41b6b35f6941135e4f1a101476de41e3f700ba565f43a1f5428ffd347c: internal libpod error

```

**Comment by jordimassaguerpla** [comment]
> > From time to time, there is a timeout when building the apidocs, a timeout coming from the disc.
> 
> ```
>   [javadoc] Visiting unknown tag: apidoc.returntype
>   [javadoc] Call Return content: #return_array_begin()
>   [javadoc]       #struct_begin("action")
>   [javadoc]           #prop_desc("int", "failed_count", "Number of times action failed.")
>   [javadoc]           #prop_desc("string", "modified", "Date modified. (Deprecated by
>   [javadoc]                      modified_date)")
>   [javadoc]           #prop_desc($date, "modified_date", "Date modified.")
>   [javadoc]           #prop_desc("string", "created", "Date created. (Deprecated by
> Error: timed out waiting for file /var/lib/containers/storage/overlay-containers/17667f41b6b35f6941135e4f1a101476de41e3f700ba565f43a1f5428ffd347c/userdata/174a396d79a42470dd7c4c3525870571bcf595407283f7baad5326638f592b68/exit/17667f41b6b35f6941135e4f1a101476de41e3f700ba565f43a1f5428ffd347c: internal libpod error
> ```

@bisht-richa : Even tests pass, I think we better not merge this, at least not yet, because we would be adding unstability. Until we can fix this, I think you better use the tag `skip_if_github_validation` in your PR.

**Comment by jordimassaguerpla** [comment]
timed out again even with the "--log-driver=none" option

**Comment by jordimassaguerpla** [comment]
> timed out again even with the "--log-driver=none" option

It happens on average every 8 executions. Each workflow runs 5 executions in parallel, which means, on average, it fails once every two workflow runs.

**Comment by jordimassaguerpla** [comment]
If I update to the latest podman version, 3.4.4 . It run 55 times without error! However, network is not working :(

**Comment by jordimassaguerpla** [comment]
trying a workaround  for https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
sudo sed -ie "s/\"cniVersion\": \"1.0.0\"/\"cniVersion\": \"0.4.0\"/g" /etc/cni/net.d/uyuni-network-1.conflist

**Comment by jordimassaguerpla** [comment]
Even with latest version of podman and with latest package updates, it fails with

```
Error: timed out waiting for file /var/lib/containers/storage/overlay-containers/
```

**Review by srbarrios — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
Using Ubuntu 24.04 fixed all issues!! I run 4 times the builds and all green :dancers:

**Comment by jordimassaguerpla** [comment]
@bisht-richa : This is green now :) Feel free to "squash and merge" to your branch.

**Pull request closed without merging**
