### PR TITLE
bootstrap repo: set optional package

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Currently the bootrap repo contains some packages from Uyuni Client tools channel: since these packages are just used for the traditional stack and in some scenario the Uyuni Client tools channel is not synced (e.g. when just a uyuni proxy is connected to the uyuni server), they should be marked as optional.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: no documentation present for describing packages on bootstap repo.

- [x] **DONE**

## Test coverage

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Also adding mc to the review list.

**Comment by mcalmer** [comment]
I think the packages should not be optional for SUMA as SUMA Proxy should have the traditional packages available.
I think the problem is only on "Uyuni Proxy", right?

So I would mark only the packages as optional which are used for a "Uyuni Proxy". 
I think this is the "PKGLIST15_TRAD" list.

**Comment by juliogonzalez** [comment]
> I think the packages should not be optional for SUMA as SUMA Proxy should have the traditional packages available. I think the problem is only on "Uyuni Proxy", right?
> 
> So I would mark only the packages as optional which are used for a "Uyuni Proxy". I think this is the "PKGLIST15_TRAD" list.

True, but do we still support traditional proxies on 4.3?

**Comment by mcalmer** [comment]
> > I think the packages should not be optional for SUMA as SUMA Proxy should have the traditional packages available. I think the problem is only on "Uyuni Proxy", right?
> > So I would mark only the packages as optional which are used for a "Uyuni Proxy". I think this is the "PKGLIST15_TRAD" list.
> 
> True, but do we still support traditional proxies on 4.3?

Yes, I am not aware there we forbid that.

**Review by mcalmer — APPROVED** [review]
I hope this is enough to fix the problem.

**Comment by mcalmer** [comment]
> ok, now the changes are just in `PKGLIST15_TRAD`, but it is also used by SLE/SUMA ..should I create another category just for uyuni?

I think this is not easy possible. We have not really the possibility to differ between SUMA and Uyuni at this point.
I think you need the fix "now". Maybe we rollback this after we branched 4.3 and remove the optional again?

And short after this, we can remove all the traditional packages from the bootstrap repos as Uyuni / Master and SUMA 4.4 will not support it anymore.

**Pull request merged**
