### PR TITLE
QAM: Moving Ubuntu external repositories

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

This re-organization of scenarios aims to be more flexible when running our QAM pipelines, having the need of re-run the test pipeline due to issues in the custom channels or the activation keys.
The reason is that the repo sync stage must only run once, inside the deployment pipeline, but the custom channels injections can be triggered several times if we run the cleanup command : 
```
#Remove all channels:
for channel in $(spacecmd -u admin -p admin -q softwarechannel_list); do spacecmd -y -u admin -p admin -q softwarechannel_delete $channel; done;
```

So after this cleanup, we run again the custom channel injection stage, and we will have recreated everything that is not a permanent channel that can't be deleted.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were moved

- [x] **DONE**

## Links

Ports:
- Manager-4.0  https://github.com/SUSE/spacewalk/pull/13808
- Manager-4.1  https://github.com/SUSE/spacewalk/pull/13807

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by Bischoff — COMMENTED** [review]
No objection, but the real expert here is @ktsamis. I suggest you wait for his blessing.

**Comment by srbarrios** [comment]
> No objection, but the real expert here is @ktsamis. I suggest you wait for his blessing.

I will just merge, well at least the 4.1 branch hehe so I unblock it, I need it for my current job to pass the tests.

**Comment by srbarrios** [comment]
Those channels and repos will not be destroyed with "softwarechannel_delete".
So we are safe, closing this PR.

**Comment by Bischoff** [comment]
@srbarrios Did I miss something, or was the revert for 4.0 forgotten ?

**Pull request closed without merging**
