### PR TITLE
Fix build-packages-local-obs.sh check_repo to use the value of $untracked instead and ignore grep exit code

### PR DESCRIPTION
**Pull request by lneves12**
## What does this PR change?

Fix build-packages-local-obs.sh check_repo to use the value of $untracked instead and ignore grep exit code

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed.

- [x] **DONE**

## Test coverage
- No tests

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"

### CODE REVIEW

**Comment by lneves12** [comment]
I am still having problems to run this "check_repo" function locally with "#!/bin/bash -e"

it's only working with "#!/usr/bin/env bash"

Is it a misconfiguration in my machine?

**Comment by juliogonzalez** [comment]
LGTM! Thanks!

**Comment by juliogonzalez** [comment]
> I am still having problems to run this "check_repo" function locally with "#!/bin/bash -e"
> it's only working with "#!/usr/bin/env bash"
> Is it a misconfiguration in my machine?

If you remove `-e` it means the script will not exit on errors.

Does it work if you use `#!/usr/bin/env bash -e`?

I will not merge yet, so you can verify and fix if needed.

**Comment by lneves12** [comment]
ah, now it's working fine after the last commit! thanks for the hint, I don't know why I overlooked that "-e".

The problem was that the grep command returns exit code 1 when there isn't any match

**Comment by juliogonzalez** [comment]
@isbm what if we disable error detection only when running those two lines, so the script can still fail at other places?

That can be done with `set +e` and `set -e`.

**Comment by lneves12** [comment]
IMO it's safer to have it failing earlier and ignore the result explicitly if you don't need it. You can also avoid mistakes like having an "echo" in the end and your script will always run successfully, no matter what.  

However, I am fine with both solutions.

**Comment by isbm** [comment]
@juliogonzalez I am not sure which direction you want to go. You can enable errors and try suppress them with `||:` ways. Or you can just disable all that but then your code should be more safe. I would personally use `-e` only when this is critical to transactional way, something that should immediately abort and do not change the state of the system. _This_ script is just an app-wrapper around few commands. So I personally see no reason of `-e` and would prefer rather STDOUT/STDERR errors instead of silent quit.

In any case, now you know that:

- It does work without `-e`.
- It does work with `-e` and `||:` fix.
- @lneves12 wants keep it as is.
- I would rather disable strict mode instead, since I don't care if my build might wrong locally due to another bug in this script.

Now is your call. :wink:

**Comment by juliogonzalez** [comment]
@lneves12, I think you can merge it as it is.

**Comment by lneves12** [comment]
> @juliogonzalez I am not sure which direction you want to go. You can enable errors and try suppress them with `||:` ways. Which is conceptually odd to me a bit, because it is anyway the only place which is intermediate: everything else is just calling OBS. Or you can just disable all that but then your code should be more safe. I would personally use `-e` only when this is critical to transactional way, something that should immediately abort and do not change the state of the system. _This_ script is just an app-wrapper around few commands. So I personally see no reason of `-e` and would prefer rather STDOUT/STDERR errors instead of silent quit.
> 
> In any case, now you know that:
> 
> * It does work without `-e`.
> * It does work with `-e` and `||:` fix.
> * @lneves12 wants keep it as is.
> * I would rather disable strict mode instead, since I don't care if my build might wrong locally due to another bug in this script, but I would hate script silently ends and that's it.
> 
> Now is your call.

but if the problem is it failing silently, wouldn't it be worse without the option -e ? In that case, the script would fail in the wrong place in unexpected ways because of a wrong previous command, to detect the root misbehavior command could also be a pain in the ass.

It would be nice if we could trap the program exit and somehow print the last executed command.

**Comment by lneves12** [comment]
> @lneves12, I think you can merge it as it is.

ok :+1:

**Pull request merged**
