### PR TITLE
Fix spacecmd with no parameters produces a traceback on SLE 11 SP4 (bsc#1176823)

### PR DESCRIPTION
**Pull request by vzhestkov**
#2669  What does this PR change?

Fixes syntax issue for Python 2.6 used in SLE 11 SP4 and keeps the functionality the same.

Before:
traceback on running spacecmd with no parameters on SLE 11 SP4

After:
normal behavior

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1176823

## Changelogs
- [x] No changelog needed

## Re-run a test

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by meaksh — COMMENTED** [review]
Thanks for the fix @vzhestkov ! 

Only thing missing here is to add a changelog message to the corresponding `spacecmd.changes` file.

**Comment by juliogonzalez** [comment]
Rememeber about the changelog message and to backport.

**Comment by Bischoff** [comment]
Thanks for the fix, Victor.

**Review by juliogonzalez — APPROVED** [review]
Changelog entry looks good, remember about the backports :-)

**Comment by juliogonzalez** [comment]
And just for the record: it is safe to ignore the java_lint_checkstyle test.

**Review by meaksh — APPROVED** [review]
LGTM :+1:

**Pull request merged**
