### PR TITLE
Fix arch in spacewalk common channels

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

spacewalk-common-channels:
The arch name is sometimes written a bit exotic. Translate it to a more normal string compartible with the values used in the config file

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **manual**

- [x] **DONE**

## Links

Fixes https://github.com/uyuni-project/uyuni/issues/2838

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by juliogonzalez — APPROVED** [review]
LGTM

**Comment by dkloos** [comment]
Just tested it but the channel is not picked up

x86 is working
```
uyuni-hai01:/ # spacewalk-common-channels -u de20617 -a x86_64 'sles15-sp2-uyuni-client'
SUSE Manager password:
INFO: sle-product-sles15-sp2-pool-x86_64 exists
```

But for ooc64le no Channel is found

```
uyuni-hai01:/ # spacewalk-common-channels -u de20617 -a ppc64le 'sles15-sp2-uyuni-client'
SUSE Manager password:
```
**No channels matching your selection.**

**Comment by juliogonzalez** [comment]
@mcalmer can you have a look?

**Comment by mcalmer** [comment]
@dkloos do you have sle-product-sles15-sp2-pool-ppc64le created? I tried here and it worked. I just found other issues but unrelated to this .

**Pull request merged**
