### PR TITLE
fix byte-buddy runtime dependency

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

fix byte-buddy runtime dependency. Testing it here: https://build.opensuse.org/project/show/home:mbussolotto:branches:systemsmanagement:Uyuni:Master

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- No tests
- [x] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni/issues/8859

- [ ] **DONE**

## Changelogs

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests" 
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Comment by mbussolotto** [comment]
@raulillo82 @deneb-alpha Is there any particular reason why we were using `byte-buddy` from 
 `Others` repo https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master:Other/byte-buddy ?

**Comment by mcalmer** [comment]
In your test project, spacewalk-java still uses byte-buddy 1.11 .
That spec file still has byte-buddy => 1.11

**Comment by mbussolotto** [comment]
looks like `byte-buddy >= 1.14` is not avaialable for `aarch64`... is it ok for you to bump the `Uyuni_Others` rpm ? @deneb-alpha @raulillo82

**Comment by mbussolotto** [comment]
>@mbussolotto I don't think that will fix the problem. You need to rebuild hibernate5 with the newer version.

$> osc rbl systemsmanagement:Uyuni:Master:Other hibernate5 openSUSE_Leap_15.6 x86_64
this show that we build with byte-buddy 1.11.12.
The Requires: byte-buddy => 1.14 will not work when the package is not available.

mmm it actually worked using `ant` patch, but I agree with you, the should use the same version of course. Let's see if we can bump `byte-buddy` version

**Comment by mcalmer** [comment]
I added merge-candidate label to not forget after we created the 5.0 branch and can do this for Uyuni/master only

**Review by mcalmer — APPROVED** [review]

**Comment by mcalmer** [comment]
@admd i remember that this require also a package submission. AFAIK @deneb-alpha closed the SR some weeks ago.
Check carefully, this can create problems

**Comment by deneb-alpha** [comment]
...indeed, it was
https://build.opensuse.org/request/show/1180901
The SR had conflicts and was reverting other changes. I'll check this on Monday

**Pull request merged**
