### PR TITLE
Update translations workflow

### PR DESCRIPTION
**Pull request by hustodemon**
Will merge after the holidays.

(review commit-by-commit)

## What does this PR change?

Adding a workflow that is triggered as a github action after push to `master` branch.

The result can be seen here: https://github.com/hustodemon/uyuni (the action added new commits on top of master).

Questions:

- [ ] shall we make this action lock the branch somehow?

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: automation
- [x] **DONE**

## Test coverage
- No tests:  automation

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]
I hope all the git commands in update-all-translation-strings do not conflict with github and that it does the right thing when it failes

**Comment by hustodemon** [comment]
>...  that it does the right thing when it fails

If the update script returns non-zero, nothing is committed. But there is probably a whole set of problems not caught by this. Let's see.

@parlt91 Could you also review this? In particular, can you check the 7 latest commits in the master branch of https://github.com/hustodemon/uyuni? These are generated by the update script, when running on current state of `master` (commit e24afbf4dfb224c8c6a804f9c5793d7eaf3f7107 at this time). To me it's a lot of lines in those generated commits, but maybe it's ok.

**Review by parlt91 — APPROVED** [review]
LGTM as far as I can tell. We will have to see how this performs in practice, only one way to find out. Let it loose :stuck_out_tongue: 
About the large diff: they are normal. The line numbers of the strings origin are tracked in the `po` files. So if anyone makes a change to the origin files all the strings following the changes line number must be updated in all the `po` files (if the change add/removes a line in the file)

**Review by juliogonzalez — APPROVED** [review]
From what I can understand from thie PR... LGTM. Let's give it a try and we'll see.

**Comment by juliogonzalez** [comment]
# IMPORTANT

@juliogonzalez remember to disable thechangelog_text reqirement after the PR is merged!

**Comment by juliogonzalez** [comment]
Ping @hustodemon, PR merged, changelog_approval test is not mandatory anymore, remember to adjust weblate.

**Pull request merged**
