### PR TITLE
reposync: Prepared for dnf plugin.

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?
Reposync related changes:
- Modified reposync to use variables for apache uid, gid and yum backend type (zypper/dnf).
- Renamed yum_src plugin to yum_zypper_src to allow for the upcoming yum_dnf_src.
- Moved common yum repo code out into yum_src_common.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: No functional change.
 
- [X] **DONE**

## Test coverage
- No tests: modified files tested manually on Leap 15.2 and CentOS: reposync success and fail case.
Package bulid tested on Leap 15.2 and CentOS 8.

- [X] **DONE**

## Links

Relates to: #3074 

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql" 
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by meaksh — COMMENTED** [review]
These changes look good to me, but I think this will require to fix the DB schema and prepare a schema migration to fix the content of `rhnContentSourceType` table:

https://github.com/uyuni-project/uyuni/blob/master/schema/spacewalk/common/data/rhnContentSourceType.sql 

Thanks a lot for pushing this!

**Review by meaksh — APPROVED** [review]
Wait! I just noticed the schema migration is not needed. The content source is kept as `yum` in the DB and UI but you simply resolve to the right backend here: https://github.com/uyuni-project/uyuni/pull/3125/files#diff-28a14014c2cdd3d9ea556afa81179c8a3f07c30890c01ff5bd1903dbfbbb0753R719

This looks even better. I'm approving this, thanks! :+1:

**Comment by sbluhm** [comment]
I just realised that I have to adapt the test cases for the new plugin name. I will re-work this.

**Comment by sbluhm** [comment]
I just realised that the yum_src plugin is loaded in additional places like spacewalk-utils or spacewalk-backend-cdn-tools.

The detection logic and yum_dnf_src testcases will be added with the next pull request.

**Comment by mcalmer** [comment]
spacewalk-backend-cdn-tools is not really used by us as it requires tons of RedHat/Fedora python packages which we did not want to build. It might be an option to remove this tool.

**Comment by sbluhm** [comment]
I changed my mind on this one for time being (or definite). I believe I just found an easier final solution than I initially planned.

**Pull request closed without merging**
