### PR TITLE
Fix bootstrapping SLE15 client (bsc#1128541)

### PR DESCRIPTION
**Pull request by dincamihai**
Co-authored-by: Jochen Breuer <jbreuer@suse.de>

## What does this PR change?

Fixes bootstrapping SLE15 https://bugzilla.suse.com/show_bug.cgi?id=1128564

## GUI diff

No difference.

Before:

After:

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- [doc-susemanager](https://github.com/SUSE/doc-susemanager) PR or issue was created (GitHub automatic link expected below)

- [x] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Copy the following sentence as a new comment if you don't need changelog entries:

> gitarro no changelog needed !!!

If the test `changelog_test`already run, then add another new comment with the following text:

> gitarro rerun changelog_test !!!

### CODE REVIEW

**Comment by brejoc** [comment]
This basically fixes this change: https://github.com/uyuni-project/uyuni/commit/74f0461ebe62c5ddfe15f20134fca0cee0b8954f

**Comment by juliogonzalez** [comment]
@dincamihai, sorry I did not notice when reviewing, but tito-wrapper noticed that the commit and the PR mentions:
> Fix bootstrapping SLE15 client (bsc#1128541)

While the changelog mentions:
> - Fix bootstrapping SLE15 traditional client (bsc#1128564)

I think the changelog is right, and the commit and PR are wrong (as bsc#1128541 is the problem with cobbler tokens). Is it correct or am I missing something?

Please confirm tomorrow morning, so I can tag and submit.

**Comment by Bischoff** [comment]
I think you're right @juliogonzalez, but let's wait for confirmation from Mihai.

**Comment by dincamihai** [comment]
> @dincamihai, sorry I did not notice when reviewing, but tito-wrapper noticed that the commit and the PR mentions:
> 
> > Fix bootstrapping SLE15 client (bsc#1128541)
> 
> While the changelog mentions:
> 
> > * Fix bootstrapping SLE15 traditional client (bsc#1128564)
> 
> I think the changelog is right, and the commit and PR are wrong (as bsc#1128541 is the problem with cobbler tokens). Is it correct or am I missing something?
> 
> Please confirm tomorrow morning, so I can tag and submit.

Of course, you are right. Wrong copy-paste.

**Pull request merged**
