### PR TITLE
Correct expected text for product sync

### PR DESCRIPTION
**Pull request by ktsamis**
## What does this PR change?

Correct expected text for product sync, adding the text that appears in the UI. This should only be for 4.2 for master.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes No issue, directly from BV testsuite review
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by ktsamis** [comment]
Still draft I want to make sure that it works by testing locally.

**Comment by ktsamis** [comment]
Ok now all reposyncs passed. Ready to be merged.

**Comment by ktsamis** [comment]
I still have no idea why these lines are necessary unfortunately. The rest of the products don't need them but these do? Maybe because they are in BETA? Not sure but at least now it's green

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
> I still have no idea why these lines are necessary unfortunately. The rest of the products don't need them but these do? Maybe because they are in BETA? Not sure but at least now it's green

Well, I guess these lines just increase a bit the time we wait on the scenario. But they are totally right lines.

**Pull request merged**
