### PR TITLE
Gather some tiny components into a new utils folder

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Gathers and extracts a few ReactJS components into a `utils` folder.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: code reorganization

- [X] **DONE**

## Test coverage
- No tests: Code reorganization

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@cbosdo we have conflicts here. How important is this for the Uyuni release?

**Comment by cbosdo** [comment]
@juliogonzalez depends what you call important ;) This is some JS refactoring / code moving... the release can live without it.

**Comment by cbosdo** [comment]
@ncounter adding you as reviewer here, since you the other one working on UI stuff ;)

**Comment by cbosdo** [comment]
> +1 Thanks for this re-organization.
> Wouldn't it make sense to move also the `HelpIcon.js` in `/components/utils/` and reuse it inside the new `HelpLink.js` component?

Makes sense

> Generally speaking, I wonder if it would make sense to move more components then, and how to distinguish/split them in categories which to move and which not, something like "simple graphical component to be reused can be moved into components/utils", or something like that. What do you think?

Yeah, unless they are really representing something in particular (like actions, dialogs, etc). Of course the line may not be that easy to draw and we'll hit blurry parts of it.

**Comment by cbosdo** [comment]
`HelpIcon` now in `utils` and reused by `HelpLink`

**Pull request merged**
