### PR TITLE
New menu look&feel

### PR DESCRIPTION
**Pull request by ncounter**
## What does this PR change?

Update menu style to a fresh look and feel.

*Highlights*:
- get rid of the `dot-circle direct-link`, use the node text instead
- get rid of left list lines to keep aligned the menu level with the siblings
- let only the menu scroll, the menu search box stays fixed instead
- better footer icon image
- smaller footer box
- let the last element of the breadcrumb be a link as well
- on `webkit` engine based browsers, use a custom smaller and lighter `nav scrollbar`

## GUI diff

Before:
old-menu

After:
Screenshot from 2019-05-04 22-01-05

- [x] **DONE**

## Documentation
- @Loquacity pinging you here because of two reasons:
  - documentation will need fresh screenshots
  - should we document the new behavior in a *textual written mode*? if yes, how? So far I plan to explain the new behavior during a training-demo, but  I have no idea about the *paper/written* mode.

- [x] **DONE**

## Test coverage
- No tests: test coverage is already in place

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Copy the following sentence as a new comment if you don't need changelog entries:

> gitarro no changelog needed !!!

If the test `changelog_test`already run, then add another new comment with the following text:

> gitarro rerun changelog_test !!!

### CODE REVIEW

**Comment by ncounter** [comment]
gitarro rerun changelog_test !!!

**Comment by lneves12** [comment]
I tested it and it's looking good overall. I think the new behavior will get better after merging the new concept of SPA! 

2 remarks:

- The eos and scc menu icons still seem to be bigger: 18x18. IMO they would look better a bit larger like eos and scc.
- I think when we press the new direct link it shouldn't close the menu. It's weird if you have the menu open then press the direct link, it will close the menu and open again after loading the direct link.

**Comment by lneves12** [comment]
Maybe the direct link shouldn't open the menu at all

**Comment by ncounter** [comment]
> Maybe the direct link shouldn't open the menu at all

Totally agreed!! I noticed it, I have it on my list to fix. I think it does not prevent to have the new design merged, but it would be muuuuuch better to have it fixed since the merge happens. I will focus on this behavior fix. Thanks.

**Comment by ncounter** [comment]
> Maybe the direct link shouldn't open the menu at all

@lneves12 addressed in https://github.com/uyuni-project/uyuni/pull/438/commits/ed14adb9bc20868b43c07f5ecc2d0ed2bb2b798c

**Comment by Loquacity** [comment]
> 
> ## Documentation
> * @Loquacity pinging you here because of two reasons:
>   
>   * documentation will need fresh screenshots

Agreed. Pinging @jcayouette and @keichwa for visibility.

>   * should we document the new behavior in a _textual written mode_? if yes, how? So far I plan to explain the new behavior during a training-demo, but  I have no idea about the _paper/written_ mode.

This is something that could work well in the beginning of the Reference Guide. It's a low priority, but certainly something we should consider.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

>>   * should we document the new behavior in a _textual written mode_?
>> if yes, how? So far I plan to explain the new behavior during a
>> training-demo, but I have no idea about the _paper/written_ mode.
>
> This is something that could work well in the beginning of the Reference
> Guide. It's a low priority, but certainly something we should consider.

Thanks for the reminder.  I created
https://github.com/SUSE/spacewalk/issues/7766


-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nürnberg)

**Pull request merged**
