### PR TITLE
QE: Add missing Cobbler scopes

### PR DESCRIPTION
**Pull request by nodeg**
## What does this PR change?

This adds missing Cobbler scopes to some of our features. CC @SchoolGuy 

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- Cucumber tests were adjusted

- [x] **DONE**

## Links

Manager 4.2
Manager 4.1

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by ktsamis — APPROVED** [review]

**Review by vandabarata — APPROVED** [review]

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
Don't worry about the java unit tests issue.

**Comment by nodeg** [comment]
Jep. I am still wondering why it runs every time. It makes more sense to only run in certain cases.

**Comment by srbarrios** [comment]
> Jep. I am still wondering why it runs every time. It makes more sense to only run in certain cases.

Some Unit tests still running in Jenkins jobs, instead of GitHub actions.
In Jenkins we use a custom tool named Gitarro, we have some issues with that tool, but is not worth to spend any person time on improving that tool. Let's see when we can move all to GitHub Actions at least for Uyuni.

**Comment by nodeg** [comment]
Good idea.

**Pull request merged**
