### PR TITLE
Allow package changelog entries with more than 3000 characters (bsc#1144889)

### PR DESCRIPTION
**Pull request by meaksh**
## What does this PR change?

This PR changes the type of the `text` column from `rhnPackageChangeLogData` database table to use `TEXT` instead of `VARCHAR2(3000)`.

This way we allow to store the complete text of a package changelog entry and prevents situations were a duplicated is created in the DB due truncating the changelog message.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **bugfix**

- [x] **DONE**

## Test coverage
- No tests: **bugfix**

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/pull/9053

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by meaksh** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by meaksh** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by mcalmer** [comment]
This is one of the problems we get with this:

https://stackoverflow.com/questions/17204361/unique-index-on-postgresql-text-column-can-it-cause-high-cpu-load

But I think there is no big different between VARCHAR(3000) and TEXT .

**Comment by meaksh** [comment]
Yeah, that's true. Indexing long text values hits performance but, since we were already dealing with VARCHAR(3000) I also think this wouldn't have much difference.

**Pull request merged**
