### PR TITLE
spacewalk-java: Removed unused joda-time dependencies

### LINKED ISSUE #4123: Uyuni Enhancement Request - Uyuni 2021-08 - Replace joda-time
# Short description
spacewalk-java requires package joda-time

Joda-time is no longer in active development except to keep timezone data up to date. From Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project. For Android users, java.time is added in API 26+. Projects needing to support lower API levels can use the ThreeTenABP library.

Removing the joda-time dependency would also remove the joda-convert dependency, saving two additional packages.

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

This removes joda-time dependencies from the Java build and spec files.
Package compiles and builds successfully. A Uyuni instance can be installed and started.

Servlet requireement for RHEL has also been aligned with SUSE requirements.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

Manual build on AlmaLinux8 successfull. (Automatic build on copr not possible atm).

- [X] **DONE**

## Links

Fixes #4123 

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by juliogonzalez — COMMENTED** [review]
I can't review this PR, this is more for the Java teams. I will add some reviewers

**Review by cbbayburt — COMMENTED** [review]
Looking at the failing unit tests, we're using `joda-time` indirectly for the SSO functionality (See `SSOControllerTest.java` failures).

`com.onelogin.saml2.settings.SettingsBuilder` is using it when building the SSO config parameters.

Looks like they weren't unused after all. I'm not familiar with the SSO applications in SUMA, so I'm not sure if the `joda-time` dependencies can be avoided with some workaround.

**Comment by mcalmer** [comment]
@mbologna please have a look as well

**Comment by sbluhm** [comment]
Apparently you can replace them with  java.time.
Let me see where this issue is. Grep didn't return any joda hits...

**Comment by sbluhm** [comment]
Nevermind: https://github.com/onelogin/java-saml/issues/201

**Comment by sbluhm** [comment]
I won't dare to ask if anyone really needs the SSO module (SSO is overrrated. The more often you type your password, the better you remember it...).

Let me close the PR instead and document the dependency in the enhancement request.

Are there any other tests failing or is this the only one?

**Comment by sbluhm** [comment]
Actually, in hindsight, the requirement of package java-saml is wrong. That one should have the joda-time dependencies. Not spacewalk-java.
So I might re-open this PR at a later stage.

**Comment by mbologna** [comment]
> Actually, in hindsight, the requirement of package java-saml is wrong. That one should have the joda-time dependencies. Not spacewalk-java.
> So I might re-open this PR at a later stage.

Yes, I agree to remove it just from the specfile, though. It _might_ work, depending on how the dependency chain is handled by the tetra packaging.

**Pull request closed without merging**
