### PR TITLE
Add tests of spacecmd to softwarechannel module

### PR DESCRIPTION
**Pull request by isbm**
## What does this PR change?

Adds unit tests, ongoing bug fixes and minor refactorings to `spacecmd.softwarechannel` module.

NOTE: Changelog entry will be added after the work-in-progress is over.

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed (only adds tests plus minor refactors that are not visible to the user)

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by meaksh** [comment]
This needs to be rebased and retested before merging. We've created an issue to track this in our board: https://github.com/SUSE/spacewalk/issues/12644

Let's keep this open for some for now.

**Comment by isbm** [comment]
Wow, two years soon :wink: I thought I merged that...

**Comment by brejoc** [comment]
> Wow, two years soon wink I thought I merged that...

It's still WIP. Feel free to finish it! :wink:

**Comment by agraul** [comment]
I rebased the branch and deleted a few unused things + flattened the test module. When we touch other spacecmd test I think we should also flatten them.

**Review by meaksh — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
