### PR TITLE
Cluster removal

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Remove the cluster management feature

## GUI diff

All the cluster menu disappeared!

- [X] **DONE**

## Documentation
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/16392

- [X] **DONE**

## Test coverage
- No tests: code removal

- [X] **DONE**

## Links

Fixes part of https://github.com/SUSE/spacewalk/issues/16392

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by Etheryte — APPROVED** [review]
Very cool stuff, didn't know we were doing this, but that's a lot less code to worry about. Really nice. Frontend changes look good. 👍

**Review by vzhestkov — APPROVED** [review]
Looks good

**Comment by cbosdo** [comment]
@mbologna you probably want to have a look at this since you were the one writing the code

**Review by mbologna — APPROVED** [review]

**Comment by cbosdo** [comment]
Closing as it was taken over by @ricardoasmarques  while I was away

**Pull request closed without merging**
