### PR TITLE
Formual tab rename

### PR DESCRIPTION
**Pull request by mseidl**
## What does this PR change?
This changes the Formula tab text to Configuration 

## GUI diff

No difference.

Before:
formula_tab_before

After:
formula_tab_after

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- [doc-susemanager](https://github.com/SUSE/doc-susemanager) PR or issue was created (GitHub automatic link expected below)

- [ ] **DONE**

## Test coverage
- No tests:   I don't think we need to change the cucumber tests

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mseidl** [comment]
@Bischoff  Can you comment and make sure I don't need to change anything for the test suite?

**Comment by Bischoff** [comment]
> @Bischoff Can you comment and make sure I don't need to change anything for the test suite?

Sure.

* features/secondary/min_salt_formulas_advanced.feature -> should be no problem

**Comment by joesusecom** [comment]
I think the "Configuration" has the wrong font (some serif font). Maybe you need to separate out the icon into its own tag instead of applying the css class to the `<a>` tag? I've seen it used with an `<i>` tag in other places.

**Comment by keichwa** [comment]
I forgot to mention that we must adjust the docs accordingly: update screen shot and string change (Reference Guide and the one where we discuss the Formulas with Froms feature.  @Loquacity shall I create an documentation issue?

**Comment by Loquacity** [comment]
> I forgot to mention that we must adjust the docs accordingly: update screen shot and string change (Reference Guide and the one where we discuss the Formulas with Froms feature. @Loquacity shall I create an documentation issue?

Yes please.

**Comment by mseidl** [comment]
formula_tab_fix_fixed



fixed it

**Comment by mseidl** [comment]
> From the technical POV it LGTM. (The icon in the tab looks weird though.)

@paususe   Should we change it?

**Comment by Loquacity** [comment]
> > I forgot to mention that we must adjust the docs accordingly: update screen shot and string change (Reference Guide and the one where we discuss the Formulas with Froms feature. @Loquacity shall I create an documentation issue?
> 
> Yes please.

https://github.com/SUSE/spacewalk/issues/11051

**Pull request merged**
