### PR TITLE
set product_tree tag to Beta and change the config value to SUMA5.0

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Prepare for the next SUSE Manager major version, set product_tree tag to Beta and change the config value to SUMA5.0

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered
  @uyuni-project/qe This change will make the "Beta Client Tools Channels" visible in the Product Page. This needs to be handled in the testsuite. 

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
Thank you :)

**Review by deneb-alpha — APPROVED** [review]
LGTM, but  this should be  merged when QE  is ready too or we will break the  tests

**Comment by deneb-alpha** [comment]
adding a reference  to https://github.com/SUSE/spacewalk/issues/22011. this needs to  go in the  next milestone, not in Alpha

**Review by nadvornik — APPROVED** [review]
LGTM

**Pull request merged**
