### PR TITLE
Remove auditlog-keeper

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Remove auditlog-keeper.

Kudos to @lucidd for the java part.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- https://github.com/uyuni-project/uyuni-docs/pull/53

- [x] **DONE**

## Test coverage
- No tests: Was removed from cucumber long ago.

- [x] **DONE**

## Links

Related: https://github.com/SUSE/spacewalk/issues/1573

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Actully maybe @mcalmer is right.

`java_pgsql_tests` is failing:
```
    [junit] javax.servlet.UnavailableException: Cannot initialize RequestProcessor of class com.redhat.rhn.common.logging.AuditLogRequestProcessor: java.lang.ClassNotFoundException: com.redhat.rhn.common.logging.AuditLogRequestProcessor

**Comment by mcalmer** [comment]
I was wrong. That code really seems to be from us.
But remember we also have some python code used for auditlog-keeper which should be removed as well.
@renner Maybe you can point to it?

**Comment by juliogonzalez** [comment]
Maybe...
```
backend/server/test/unit-test/test_auditlog.py:import spacewalk.server.auditlog as auditlog
backend/server/test/unit-test/test_auditlog.py:from spacewalk.server.auditlog import auditlog_xmlrpc, AuditLogException
backend/server/test/unit-test/test_auditlog.py:class AuditLogTest(unittest.TestCase):
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_uid = Mock(return_value="42(geeko)")
backend/server/test/unit-test/test_auditlog.py:        self._real_server_proxy = auditlog.ServerProxy
backend/server/test/unit-test/test_auditlog.py:        self.auditlog_server = Mock()
backend/server/test/unit-test/test_auditlog.py:        self.auditlog_server.log = Mock()
backend/server/test/unit-test/test_auditlog.py:        auditlog.ServerProxy = Mock(return_value=self.auditlog_server)
backend/server/test/unit-test/test_auditlog.py:        auditlog._read_config = Mock(return_value=(True, "bogus_url"))
backend/server/test/unit-test/test_auditlog.py:        auditlog.ServerProxy = self._real_server_proxy
backend/server/test/unit-test/test_auditlog.py:        auditlog._read_config = Mock(return_value=(False, ""))
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc("method", "method_name", "args", "request")
backend/server/test/unit-test/test_auditlog.py:        self.assertFalse(self.auditlog_server.log.called)
backend/server/test/unit-test/test_auditlog.py:        auditlog.ServerProxy = self._real_server_proxy
backend/server/test/unit-test/test_auditlog.py:            self.assertRaises(AuditLogException, auditlog_xmlrpc,
backend/server/test/unit-test/test_auditlog.py:        wanted_err = ("Could not establish a connection to the AuditLog "
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", "args", "request")
backend/server/test/unit-test/test_auditlog.py:        self.assertFalse(self.auditlog_server.log.called)
backend/server/test/unit-test/test_auditlog.py:        auditlog.rhnServer.get = Mock(return_value=rhnserver_got)
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(auditlog._get_server_id(api_method, args),
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(auditlog.rhnServer.get.call_args,
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("arg1", "arg2")))
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc(api_method, "api_method_name", ["args"], request)
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("arg1", "arg2")))
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc(api_method, "api_method_name", ["args"], request)
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unit-test/test_auditlog.py:    def test_remote_auditlog_error(self):
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("arg1", "arg2")))
backend/server/test/unit-test/test_auditlog.py:        self.auditlog_server.audit.log = Mock(side_effect=Error)
backend/server/test/unit-test/test_auditlog.py:            self.assertRaises(AuditLogException, auditlog_xmlrpc, api_method,
backend/server/test/unit-test/test_auditlog.py:        wanted_err = ("Got an error while talking to the AuditLogging server "
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("args",)))
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", ["args"], request)
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unit-test/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("args",)))
backend/server/test/unit-test/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", ["args"], request)
backend/server/test/unit-test/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unittest/test_auditlog.py:import spacewalk.server.auditlog as auditlog
backend/server/test/unittest/test_auditlog.py:from spacewalk.server.auditlog import auditlog_xmlrpc, AuditLogException
backend/server/test/unittest/test_auditlog.py:class AuditLogTest(unittest.TestCase):
backend/server/test/unittest/test_auditlog.py:        auditlog._get_uid = Mock(return_value="42(geeko)")
backend/server/test/unittest/test_auditlog.py:        self._real_server_proxy = auditlog.ServerProxy
backend/server/test/unittest/test_auditlog.py:        self.auditlog_server = Mock()
backend/server/test/unittest/test_auditlog.py:        self.auditlog_server.log = Mock()
backend/server/test/unittest/test_auditlog.py:        auditlog.ServerProxy = Mock(return_value=self.auditlog_server)
backend/server/test/unittest/test_auditlog.py:        auditlog._read_config = Mock(return_value=(True, "bogus_url"))
backend/server/test/unittest/test_auditlog.py:        auditlog.ServerProxy = self._real_server_proxy
backend/server/test/unittest/test_auditlog.py:        auditlog._read_config = Mock(return_value=(False, ""))
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc("method", "method_name", "args", "request")
backend/server/test/unittest/test_auditlog.py:        self.assertFalse(self.auditlog_server.log.called)
backend/server/test/unittest/test_auditlog.py:        auditlog.ServerProxy = self._real_server_proxy
backend/server/test/unittest/test_auditlog.py:            self.assertRaises(AuditLogException, auditlog_xmlrpc,
backend/server/test/unittest/test_auditlog.py:        wanted_err = ("Could not establish a connection to the AuditLog "
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", "args", "request")
backend/server/test/unittest/test_auditlog.py:        self.assertFalse(self.auditlog_server.log.called)
backend/server/test/unittest/test_auditlog.py:        auditlog.rhnServer.get = Mock(return_value=rhnserver_got)
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(auditlog._get_server_id(api_method, args),
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(auditlog.rhnServer.get.call_args,
backend/server/test/unittest/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc(api_method, "api_method_name", ["args"], request)
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unittest/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc(api_method, "api_method_name", ["args"], request)
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unittest/test_auditlog.py:    def test_remote_auditlog_error(self):
backend/server/test/unittest/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=
backend/server/test/unittest/test_auditlog.py:        self.auditlog_server.audit.log = Mock(side_effect=Error)
backend/server/test/unittest/test_auditlog.py:            self.assertRaises(AuditLogException, auditlog_xmlrpc, api_method,
backend/server/test/unittest/test_auditlog.py:        wanted_err = ("Got an error while talking to the AuditLogging server "
backend/server/test/unittest/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("args",)))
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", ["args"], request)
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/test/unittest/test_auditlog.py:        auditlog._get_server_id = Mock(return_value=("system_id", ("args",)))
backend/server/test/unittest/test_auditlog.py:        auditlog_xmlrpc(api_method, "method_name", ["args"], request)
backend/server/test/unittest/test_auditlog.py:        self.assertEqual(self.auditlog_server.audit.log.call_args,
backend/server/Makefile:                  auditlog suseEula
backend/server/apacheRequest.py:from spacewalk.server.auditlog import auditlog_xmlrpc, AuditLogException
backend/server/apacheRequest.py:        # it will cause AuditLogException below.
backend/server/apacheRequest.py:            auditlog_xmlrpc(func, method, params, self.req)
backend/server/apacheRequest.py:        except AuditLogException as e:
backend/server/apacheRequest.py:                      extra="AuditLogging error: %s" % e)
backend/server/apacheRequest.py:        auditlog_xmlrpc(func, method, params, self.req)
backend/server/auditlog.py:class AuditLogException(Exception):
backend/server/auditlog.py:def auditlog_xmlrpc(method, method_name, args, request):
backend/server/auditlog.py:        raise AuditLogException("An attempt to call unknown method at server %s." % server_url)
backend/server/auditlog.py:        raise AuditLogException("Could not establish a connection to the "
backend/server/auditlog.py:                                "AuditLog server. IOError: %s. "
backend/server/auditlog.py:            raise AuditLogException("Got an error while talking to the "
backend/server/auditlog.py:                                    "AuditLogging server at %s. Error was: %s"
backend/server/auditlog.py:        log_debug(2, "Logged method call %s to the AuditLog server" % message)
```

**Comment by juliogonzalez** [comment]
Who can take care of the python part, if it's what I pasted?

**Comment by moio** [comment]
Working on it as part of the PR review

originally posted to devopsreactions

**Comment by moio** [comment]
@juliogonzalez please merge https://github.com/juliogonzalez/uyuni/pull/3 with more patches, Python part should be good as far as my knowledge goes

**Comment by juliogonzalez** [comment]
- Changelog entries added
- Adding @meaksh for the python part review
- Waiting for the tests to run

**Comment by juliogonzalez** [comment]
We have test failures for `java_pgsql_tests`. Ping @lucidd / @moio (don't see them for the branch job, so it has to be something from this PR).

**Comment by juliogonzalez** [comment]
Ok, tests are passing but -of course- as I tagged we now get conflicts.

I will fix them when Uyuni is out and this is ready to merge.

**Comment by juliogonzalez** [comment]
Will merge on Monday. For this weekend I prefer to have the testsuite available for @Bischoff without introducing more possible problems.

**Comment by juliogonzalez** [comment]
Changelog conflicts fixed. Merging.

**Pull request merged**
