### PR TITLE
Fix deploy of SLE Micro CA Certificate (bsc#1200276)

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Currently the deploy of SLE Micro CA Certificate is not working, because `update-ca-certificates` is never executed.
```
update-ca-certificates:
  cmd.run:
    - name: /usr/sbin/update-ca-certificates
    - runas: root
    - onchanges:
      - file: mgr_ca_cert
{%- if grains['saltversioninfo'][0] >= 3002 %} # Workaround for bsc#1188641
    - unless:
      - fun: service.status
        args:
          - ca-certificates.path
{%- endif %}
```
This happens because SLE Micro has a false positive when checking `service.status` . To workaround the issue, we would check if an ca-certificates update is already running by checking `/var/lib/ca-certificates/ca-bundle.pem.tmp` file. 

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [x] **DONE**

## Test coverage

- [ ] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/18093

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — COMMENTED** [review]
I am not sure if this also end up in a race condition and can fail. I leave this up to Pablo.

**Review by meaksh — CHANGES_REQUESTED** [review]
As @mcalmer mentioned, this can still create the race condition and fail. What I would suggest here is to "retry" the execution of `update-ca-certificate` few times in case that it fails.

This can be done by Salt with something like this:

```yaml
update-ca-certificates:
  cmd.run:
    - name: /usr/sbin/update-ca-certificates
    ...
    - retry:
        attempts: 5
        interval: 5
        until: True
```
More documentation at: https://docs.saltproject.io/en/latest/ref/states/requisites.html#retrying-states

Note: The Salt state retry mechanism is available since 2017.7.0

**Review by meaksh — APPROVED** [review]
LGTM :+1:

**Comment by mbussolotto** [comment]
CI tests: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1446/

**Pull request merged**
