### PR TITLE
Debian11 product sync data

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Add Debain 11 amd64 product to sync data.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **handled on epic**

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17107
Tracks https://github.com/SUSE/spacewalk/pull/17363

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@juliogonzalez I hope the URLs are correct and complete.

**Review by juliogonzalez — COMMENTED** [review]
I am not sure about security.

The official line for Debian11 security is is:
```
deb http://security.debian.org/debian-security bullseye-security main
```
`security-cdn` seems to be working and OK, but I have no idea from where we took that.

**Comment by mcalmer** [comment]
I copied this from debian 10 definition.
@lucidd do you know where do you got the URL from the security updates for debian from?

**Comment by lucidd** [comment]
was debian 10 in common channels before? if so i probably took if from there.

**Comment by mcalmer** [comment]
I will change the url to security.debian.org. Seems in the past security redirected to security-cdn. But we better use what is in the official pages.

**Comment by mcalmer** [comment]
New product tree pushed to SCC.

**Pull request merged**
