### PR TITLE
Update ivy configuration for new salt-netapi-client version

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Update ivy configuration for new salt-netapi-client version (0.15.1)

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: Changes for development env

- [x] **DONE**

## Test coverage

- No tests:  Changes for development env

- [x] **DONE**

## Links

https://github.com/SUSE/salt-netapi-client/releases/tag/v0.15.1

- [x] **DONE**

### CODE REVIEW

**Comment by juliogonzalez** [comment]
gitarro no changelog needed !!!

**Comment by juliogonzalez** [comment]
Failed `java_pgsql_tests` is not related to this PR.

**Comment by juliogonzalez** [comment]
Good. Let's wait for the branch to be available again.

**Comment by renner** [comment]
Closing this one in favor of #587.

**Pull request closed without merging**
