### PR TITLE
proxy-systemd-services: Adapted to build on Enterprise Linux

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

Adapted to build on Enterprise Linux

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by sbluhm** [comment]
@cbosdo  , can you please merge this one? Thank you.

**Comment by cbosdo** [comment]
@sbluhm looks like there are conflicts... I don't have the merge button activated

**Comment by sbluhm** [comment]
Hmm, the  java_pgsql_tests ist failing. As this is not java related, any chance to ovewrite it? (I don't know how).
Apart from that, no conflicts.

**Comment by cbosdo** [comment]
> Hmm, the java_pgsql_tests ist failing. As this is not java related, any chance to ovewrite it? (I don't know how). Apart from that, no conflicts.

don't worry about this one: it's a temporary issue with OBS. I'll try to manually rebase on master and merge

**Comment by cbosdo** [comment]
Looks like your first commit already landed in master. Could you please rebase on your machine and force push? It should fix it

**Comment by sbluhm** [comment]
done.
So if I rebase locally, I ALWAYS have to force push? As in, it is normal to force push after a rebase?

**Comment by cbosdo** [comment]
yes it is normal since that changes the history

**Pull request merged**
