### PR TITLE
Enable parallel building of `susemanager-nodejs-sdk-devel` and `spacewalk-web`

### PR DESCRIPTION
**Pull request by Etheryte**
## What does this PR change?

As far as I can see, the `yarn install` step needs to be serial, however the rest of the process should be possible in parallel. The below demo works on my local system but I haven't tested it with the container solution.  

Instead of using `yarn remove` to manage the packages we don't want to include in `susemanager-nodejs-sdk-devel`, I moved those to `optionalDependencies`. Technically not completely correct terminology-wise, but it allows us to run our builds without modifying the package after the initial install is done.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: only internal and user invisible changes

- [x] **DONE**

## Links

Part of https://github.com/SUSE/spacewalk/issues/14762

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
This takes 6 minutes and 53 seconds ... which is GREAT!!! Well done!

**Comment by jordimassaguerpla** [comment]
> This takes 6 minutes and 53 seconds ... which is GREAT!!! Well done!

it used to take 20 minutes or more ... so it is a great improvement

**Comment by jordimassaguerpla** [comment]
Sadly, 34 cucumber (acceptance) tests failed https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/235/ .
23 were failing in master https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-dev-acceptance-tests-NUE/1551/ , so I would say 11 additional tests failed with this. This needs investigation.

**Comment by jordimassaguerpla** [comment]
Given tests are being fixed in master ... I would say, let's hold this until master is green and then rerun the tests.

**Comment by Etheryte** [comment]
Sounds good, that way it will be easier to figure out what's wrong too since there won't be false positives. Thanks for taking the time to check on this.

**Comment by jordimassaguerpla** [comment]
Acceptance tests passed!:
* Core tests
* Initialization of clients
* Sanity checks

I think this is ready to be merged.

**Review by jordimassaguerpla — APPROVED** [review]

**Comment by Etheryte** [comment]
Nice! Thank you very much for all the help and time you've put into this Jordi, I appreciate it greatly.

**Pull request merged**
