### PR TITLE
Containers configuration scripts: python logging and configure log level

### PR DESCRIPTION
**Pull request by ncounter**
## What does this PR change?

https://github.com/SUSE/spacewalk/issues/17378

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- No tests

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17378
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by ncounter** [comment]
> Looks ok to me, just two nitpicks:
> 
>     1. `logging.<level>()` supports lazily building strings (https://docs.python.org/3.8/howto/logging.html#logging-variable-data). For this small of a script and the expected sizes of the variable data that's logged, this is a non-issue. Once we enable a linter it might complain though.
> 
>     2. I counted three ways that strings are build in log message: `{}.format`, f-string, and old-style formatting with `%s`. For consistency, it would be nice to only use a single style.

@agraul thanks for the hints. I took the chance to standardize the code now that it is still small, better than doing it later. This commit should address your points https://github.com/uyuni-project/uyuni/pull/5649/commits/6a10a10939a766ce9440b3f5f07376387c2e4c66 , doesn't it?

**Review by agraul — APPROVED** [review]
Thank you for taking the time to clean it up, looks great!

**Review by cbosdo — COMMENTED** [review]
Looks like you miss a changelog entry for the SSH container

**Review by cbosdo — APPROVED** [review]
LGTM

**Pull request merged**
