### PR TITLE
Add link for the HTTPS certificate for Leap15.3

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Add link for the HTTPS certificate for Leap15.3. Without this, the proxy fails to deploy, and the clients do not trust the SSL certificate for the server.

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: bugfix

- [x] **DONE**

## Test coverage
- No tests: Covered by BV.

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/15081
Requires backport to Manager-4.1

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by lkotek — APPROVED** [review]
Thanks for fix!

**Review by ncounter — APPROVED** [review]
:1st_place_medal: Thanks for the quick finding and fix @juliogonzalez

**Comment by juliogonzalez** [comment]
Fix confirmed by QA. Merging.

**Comment by juliogonzalez** [comment]
Seems still didn't fix the problem with the proxy, either that or the packages for ci#view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/309/ were not right. But the problem with onboarding Leap 15.3 is fixed.

**Pull request merged**
