### PR TITLE
Parametrize info in init image

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Parametrize info in init image, in this way `push-packages-to-obs.sh` can set the correct values for IBS.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- No tests

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by deneb-alpha** [comment]
@mbussolotto LGTM  but...

1. do you want to have this change  included in the current Uyuni 2023.10? 
2. you  didn't provide  a .changes but you didn't tick the  `No changelog needed` :P

**Comment by mbussolotto** [comment]
No changelog ticked, thanks for checking it. About 2023.10, as you prefer: it's not strictly required, since users should not used `init-image` (it's something more for developer), but if it merge it would be better.

**Review by deneb-alpha — APPROVED** [review]
LGTM

**Comment by deneb-alpha** [comment]
> @deneb-alpha No changelog ticked, thanks for checking it. About 2023.10, as you prefer: it's not strictly required, since users should not used `init-image` (it's something more for developer), but if it merge it would be better.

I'm fine with merging this, but, do you also  want to have the review  from @aaannz ?

**Review by aaannz — APPROVED** [review]
LGTM. Maybe later we can parametrize also version number?

**Pull request merged**
