### PR TITLE
Do not route anymore for private network

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

Do not route anymore on the proxy to the private network.

## Links

Fixes SUSE/spacewalk#16486

Requires SUSE/salt-formulas#160

Followup of #4566

Replacement of #4590

Ports:
* 4.1: TBD
* 4.2: TBD

## Changelogs

- [x] No changelog needed

### CODE REVIEW

**Review by mcalmer — CHANGES_REQUESTED** [review]
will not work. there is a default on this value and prefilled with an IP

**Comment by mcalmer** [comment]
@Bischoff 
I am currently running the testsuite for [PR 4488](https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1052) in which has this [commit](https://github.com/uyuni-project/uyuni/pull/4488/commits/5a14a73f013d8325b3f3dfd353c282b2a518e321)

The client is not yet bootstrapped but after proxy got setup, ubuntu has "no" default route anymore:

```
root@suma-pr1-min-ubuntu2004:~# ip r s
10.84.220.0/23 dev ens3 proto kernel scope link src 10.84.221.8 
192.168.101.0/24 dev ens4 proto kernel scope link src 192.168.101.129 

root@suma-pr1-min-ubuntu2004:~# cat /etc/netplan/
01-netcfg.yaml      50-cloud-init.yaml  
root@suma-pr1-min-ubuntu2004:~# cat /etc/netplan/01-netcfg.yaml 
# Ubuntu netplan configuration for the testsuite
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: yes
      dhcp4-overrides:
        use-dns: no
        use-routes: no
    ens4:
      dhcp4: yes
```
I think this will also not work. But let's wait until init_clients is finished.

**Comment by Bischoff** [comment]
> will not work. there is a default on this value and prefilled with an IP

Right.

```
IP address for ens4: 192.168.5.129

root@ebi5-ubuntu:~# ip r s
default via 192.168.1.1 dev ens4 proto dhcp src 192.168.5.129 metric 100 
```

Somehow it "works", because default value `192.168.1.1` does not match the branch server's address `192.168.5.254` ... but that's pure chance!

**Comment by Bischoff** [comment]
> @Bischoff I am currently running the testsuite for [PR 4488](https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1052) in which has this [commit](https://github.com/uyuni-project/uyuni/pull/4488/commits/5a14a73f013d8325b3f3dfd353c282b2a518e321)

That will probably not work either, as "Remove" button is greyed out.
 
> The client is not yet bootstrapped but after proxy got setup, ubuntu has "no" default route anymore:

That's not normal, it should have normal defaut route on `ens3`.

**Comment by aaannz** [comment]
> > @Bischoff I am currently running the testsuite for [PR 4488](https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1052) in which has this [commit](https://github.com/uyuni-project/uyuni/pull/4488/commits/5a14a73f013d8325b3f3dfd353c282b2a518e321)
> 
> That will probably not work either, as "Remove" button is greyed out.
> 

It is no longer disabled, https://github.com/SUSE/salt-formulas/pull/160 removes limitation to always have at least one router specified.

**Comment by Bischoff** [comment]
> > > @Bischoff I am currently running the testsuite for [PR 4488](https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1052) in which has this [commit](https://github.com/uyuni-project/uyuni/pull/4488/commits/5a14a73f013d8325b3f3dfd353c282b2a518e321)
> > 
> > 
> > That will probably not work either, as "Remove" button is greyed out.
> 
> It is no longer disabled, [SUSE/salt-formulas#160](https://github.com/SUSE/salt-formulas/pull/160) removes limitation to always have at least one router specified.

Thanks. I will change this PR to use https://github.com/uyuni-project/uyuni/pull/4488/commits/5a14a73f013d8325b3f3dfd353c282b2a518e321  .

We have also another problem, the default route to `ens3` disappears. I am on it.

**Review by mcalmer — APPROVED** [review]

**Comment by Bischoff** [comment]
Finished testing locally, it works (including stopping the forwarding on the proxy , and keeping the default route --> merging).

Now we have to port to 4.1 and 4.2.

**Pull request merged**
