### PR TITLE
Update users's role check process

### PR DESCRIPTION
**Pull request by admd**
## What does this PR change?
Listing of channels was slow because in `rhn_channel.user_role_check_debug` function, which had several N+1 query problems in a number of function it calls.

This PR refactors code removing that function and synthesizing all combinations of its inputs and outputs in the new `suseChannelUserRoleView`, which is much more efficiently optimized by the query planner than (sometimes even repeated) calls to `rhn_channel.user_role_check_debug`.

Computing the user role check is significantly faster, especially when done across sets of channel/user combinations. In my setup, against Daimler's database dump:

|  |  `rhn_channel.user_role_check_debug` |  `suseChannelUserRoleView` |  Speedup |
|-------------------------|--------------------------------------|----------------------------|----------|
|  1 channel, all users | 586ms | 14ms | **~42x** |
|  1 user, all channels | 24.2s | 362ms | **~67x** |
| all users, all channels | 2h |  1'39s | **~73x** |

Computing the `rhnUserChannel` view, which is central to the performance of the API endpoint that triggered the bug report, got **~96x faster** (254ms instead of 24.5s in my setup, limited to 1 user).

I tested all the patched queries manually against Daimler's database dump and saw improvements across the board (not all as wide as the ones presented above - ranging from **~1.5x** to **~100x** faster).

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **Just some performance improvement**

- [x] **DONE**

## Test coverage
- No tests: **Existings tests should be enough**

- [x] **DONE**

## Links

Fixes #
https://github.com/SUSE/spacewalk/issues/6289
https://bugzilla.suse.com/show_bug.cgi?id=1114877
 Downstream PR: https://github.com/SUSE/spacewalk/pull/6317

- [ ] **DONE**

### CODE REVIEW

**Comment by admd** [comment]
@moio @mcalmer I would appreciate if you guy can have a a quick look here as well.

**Comment by admd** [comment]
@moio 
> 1. were there any merge conflicts? What commit ids conflicted?

Yes, these 2 https://github.com/SUSE/spacewalk/pull/6317/commits/95308ddd36141e2c692b724dc5d69022f8308ed8 and https://github.com/SUSE/spacewalk/pull/6317/commits/12b6c4db441de061f9f91001a69155f23e593e7c

**Comment by moio** [comment]
> Yes, these 2 SUSE/spacewalk@95308dd and SUSE/spacewalk@12b6c4d

Both look good.

> I will create a seprate PR to remove that reference so it can be ported to both branches.

What I meant was, 3.2 is already `user_role_check`-free at least on the Java part, while Uyuni has this additional reference. I do not think we need a new PR, this one can just be amended!

**Comment by admd** [comment]
> What I meant was, 3.2 is already `user_role_check`-free at least on the Java part, while Uyuni has this additional reference. I do not think we need a new PR, this one can just be amended!

Hmm not really. https://github.com/SUSE/spacewalk/blob/Manager-3.2/java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml#L986
https://github.com/SUSE/spacewalk/blob/Manager-3.2/java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml#L1037

**Comment by moio** [comment]
Maybe I need some extra sleep!

You are right, I am wrong and this simply, somehow, slipped. Apologies for the need of a double fix now :cry:

**Comment by admd** [comment]
@juliogonzalez can you please have a look at the last commit.

**Comment by juliogonzalez** [comment]
@admd I think what @mcalmer means is having 3.2.X-to-4.0.0 migration paths. Am I right, @mcalmer?

BTW, there's an easier way, instead of .gitignore, add an empty file `.gitkeep` as in https://github.com/uyuni-project/uyuni/blob/dc15705970c3cd803b7cf1cc2a7ce51c916bcd7f/schema/spacewalk/upgrade/susemanager-schema-3.2.5-to-susemanager-schema-3.2.6/.gitkeep

**Comment by mcalmer** [comment]
@admd @juliogonzalez - no, this is not what I mean. I really mean the migrations you added in the 3.2 PR please copy them also to uyuni branch in the same 3.2.X-to-3.2.Y directories as in the 3.2 branch.

If you upgrade from susemanager-schema-3.2.X package to susemanager-4.0.Y package you should only get additional schema migration. You should not loose some of them.

**Comment by juliogonzalez** [comment]
gitarro rererun java_pgsql_tests  !!!

**Comment by mcalmer** [comment]
@juliogonzalez - approved as you wanted to add the schema migrations in a separate PR.

**Comment by juliogonzalez** [comment]
@moio, can you review and fix the conflicts?

**Pull request merged**
