### PR TITLE
Testsuite - updated kiwi profiles

### PR DESCRIPTION
**Pull request by lkotek**
## What does this PR change?

PR updates currently used kiwi profiles for SLE12 to SP5.

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by srbarrios** [comment]
```
    <repository type="rpm-md">  <!-- 4.0 development client tools -->
        <source path="http://download.suse.de/ibs/Devel:/Galaxy:/Manager:/4.0:/SLE12-SUSE-Manager-Tools/SLE_12/"/>
    </repository>
``` 
Reference to 4.0 still valid?

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
LGTM.
Just a note, we might soon need a different profile for 4.1, so Head becomes 4.2

**Comment by lkotek** [comment]
> LGTM.
> Just a note, we might soon need a different profile for 4.1, so Head becomes 4.2
> Or we might even want to keep 4.0 as it was, and only upgrade the version in a new 4.1 profile

This PR is actually not that important, but you're right we will need to switch to SLE15SP3 (from SP2) when it is ready. But no worries, situation is very similar to this one. So only minor or no changes should be necessary. (When I have a moment I will try to build SLE15SP3 image.)

**Comment by Bischoff** [comment]
thanks Lukas!

**Pull request merged**
