### PR TITLE
Move srv_organization_credentials to reposync features

### PR DESCRIPTION
**Pull request by calancha**
## What does this PR change?
Ensure the test suite uses the SCC credentials passed in the .tf file.
See https://github.com/SUSE/spacewalk/issues/12007

- testsuite/features/reposync/srv_organization_credentials.feature;
Move it here from testsuite/features/secondary.

- testsuite/run_sets/secondary_parallelizable.yml
- testsuite/run_sets/reposync.yml:
Amend lists of feature files after the moved file.

### Ports
- Manager-3.2: https://github.com/SUSE/spacewalk/pull/12528
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12529
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12530

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

### CODE REVIEW

**Comment by Bischoff** [comment]
This PR looks nice, but I don't understand how it works.

It seems somehow magic that just moving a feature solves the issue SUSE/spacewalk#12007 ...

@srbarrios what was the technical problem and how was it solved by just moving the feature there?

**Comment by srbarrios** [comment]
@Bischoff is not clear enough in the description of https://github.com/SUSE/spacewalk/issues/12007 ?

**Review by srbarrios — APPROVED** [review]
LGTM. Please, be sure that the expected behavior is good now.
So, passing the scc_credentials, it applies our scc credentials instead of the ones coming from sumaform.

**Comment by calancha** [comment]
I have just confirmed that the patch does what it must do.

**Pull request merged**
