### PR TITLE
Fix regexp that changes ubuntu's repositories

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

This fixes PR #2554

There was an error in the regular expression for ubuntu : probably a byproduct of factorizing too much :smile_cat: .

Thanks to @juliogonzalez and @mbologna for the long debugging session and finding the issue :clap: .

## Links

Ports:
* 3.2: not affected
* 4.0: SUSE/spacewalk#12415
* 4.1: SUSE/spacewalk#12414

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

### CODE REVIEW

**Review by calancha — APPROVED** [review]
That was hard to catch one!

**Review by ktsamis — APPROVED** [review]
LGTM

**Comment by Bischoff** [comment]
I'll merge it only at 4.0 for now, just in case I'm introducing another issue in that thing :trollface:

**Review by mbologna — APPROVED** [review]
OK, not sure why RuboCop is failing?

**Review by lkotek — APPROVED** [review]

**Comment by Bischoff** [comment]
> OK, not sure why RuboCop is failing?

weird indeed

**Pull request merged**
