### PR TITLE
Cleanup spec tree

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

remove all packages which are not submitted from this git to OBS.
Some of these packages are really unused, others are maintained directly in OBS or in the Distribution.

The cleanup happens to avoid confusion about what is used from this git repo and what not.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **removed unused code**

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@sbluhm please review this as well. I do not want to remove anything what you need for your CentOS port.

**Comment by sbluhm** [comment]
ok, this will take me some time. From the commit texts it looks ok at first glance.

**Comment by mcalmer** [comment]
@sbluhm take your time. I do not plan to merge it this year ;-)

**Review by sbluhm — APPROVED** [review]
I don't think we need any of them for CentOS. The ones we need are in OBS.

**Review by moio — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
