### PR TITLE
Spacewalk cherry pick 20180929

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Get important changes from spacewalk to uyuni

### CODE REVIEW

**Comment by mcalmer** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by mcalmer** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by mcalmer** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by mcalmer** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by juliogonzalez** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by juliogonzalez** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by juliogonzalez** [comment]
gitarro rerun java_pgsql_tests !!!

**Comment by juliogonzalez** [comment]
Changelog test seems to be a bug at the script.

**Comment by juliogonzalez** [comment]
Ping @MalloZup, please review https://github.com/SUSE/susemanager-ci/pull/24

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by juliogonzalez** [comment]
gitarro rerun changelog_test !!!

**Comment by juliogonzalez** [comment]
gitarro rerun backend_unittests_pgsql !!!

Let's rerun pgsql backend unit tests, just in case:

**Pull request merged**
