### PR TITLE
TEST

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
test https://github.com/SUSE/spacewalk/issues/20676

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
I remember this problem! We can't use sle_minion but then, when I tried to use something else like sleminion, sle_minion was the expected hostname in other tests ... @srbarrios : How this works when we run the tests for master?

**Comment by jordimassaguerpla** [comment]
Trying to use sleminionone , instead of sle_minion ...

**Comment by jordimassaguerpla** [comment]
it won't work because the test restarts the salt-minion service and the minion has not been started with systemd.

**Comment by srbarrios** [comment]
> I remember this problem! We can't use sle_minion but then, when I tried to use something else like sleminion, sle_minion was the expected hostname in other tests ... @srbarrios : How this works when we run the tests for master?

we must use the fqdn there, as the server don't understand our test framework internal keys, but... I'm not sure what's the fqdn in the case of that GitHub environment.

The best way to discover it, is to run `hostname -f` on that minion machine.

**Pull request closed without merging**
