### PR TITLE
spacewalk-java: fix apidoc jasper2 build

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Fix spacewalk-java package build on HEAD.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: build fix

- [X] **DONE**

## Test coverage
- No tests: build fix

- [X] **DONE**

## Links

- [X] **DONE**

### CODE REVIEW

**Comment by cbosdo** [comment]
gitarro no changelog needed !!!

**Comment by mcalmer** [comment]
Why it was building before?

**Comment by cbosdo** [comment]
@mcalmer Honestly I tried to understand why it is now looking for `/apidoc/apidoc/*.jsp` instead of `/apidoc/*.jsp` and could find it. I'ld probably need to dive into tomcat 9 sources to see if there is a bug or change in jasper.

**Comment by cbosdo** [comment]
tomcat has been updated to 9.0.14 in SLE 15 SP1 two days ago, while Leap 15 has 9.0.12. Looks like the bug lies down in tomcat's code.

**Pull request merged**
