### PR TITLE
Remove snaposhot and export tools

### PR DESCRIPTION
**Pull request by rjmateus**
## What does this PR change?

Install the spacewalk-extra-utils since it still contains some utility tools. Several of those tools needs to be migrated, but until that, we must install the package.

Partially reverts: https://github.com/uyuni-project/uyuni/pull/9251

## GUI diff

No difference.

## Documentation
- No documentation needed. I didn't removed it in the old documentation. Also, those tools where not documented.

- [ ] **DONE**

## Test coverage

- No tests: old toos, so no tests.

- [ ] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni/issues/9403
Port(s): Needs to be ported to 5.0

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by mcalmer — CHANGES_REQUESTED** [review]
No, we do not want these tools. They are not supported.
I need to check all of them, but from my point of view there is a reason why they are in an unsupported extra package

**Comment by rjmateus** [comment]
@mcalmer I was following what was discussed with  @admd in this confluence page: https://confluence.suse.com/display/~RDiasMateus/SUMA+cmd+tools

I would love to completely remove the remaining tools from this package (tasktop is already moved to the regular package, so that can be kept). But to remove all I would need @admd agreement, and I'm not sure if we must first document that those are deprecated. 
Also, what should we do to these tools on 5.0 and 5.1?

**Comment by rjmateus** [comment]
Maybe I can split the PR in 2, one to remove the tools we know we can remove, and another one to see if we want to install the extras package in the container

**Comment by rjmateus** [comment]
@juliogonzalez had the idea of moving it to the contrib repository. And looking with more attention to the confluence page, I think that was what @admd and I had discussed for the majority of the tool.
Let's talk next week, but maybe I can move must of the scripts to the contrib repo, and the one or two we want to support, move to the spacewalk-utils package instead the extra, like we did with tasktop.

**Comment by admd** [comment]
@rjmateus I just saw the description of spacewalk-utils-extra package that states

`Extra utilities that may be run against a SUSE Manager server (unsupported) or an Uyuni server`

I didn’t know about this before. So, @mcalmer is correct—we can safely remove the entire package. The only regularly used component is taskotop, and if I understand correctly, it’s already covered.

**Comment by rjmateus** [comment]
Ok, that makes sense. 
Taskotop was moved to the package spacewalk-utils, so it means it is supported.
I will then change the PR to not install the extras on the image, and remove the other tools and extras package. At same time I will move some of the tools to the contrib repo (according to the document in confluence).
@mcalmer @admd makes sense for you?

**Comment by juliogonzalez** [comment]
>  I will then change the PR to not install the extras on the image, and remove the other tools and extras package. At same time I will move some of the tools to the contrib repo (according to the document in confluence).

Should we comment it at the release notes, at least for Uyuni?

**Comment by rjmateus** [comment]
@mcalmer I will keep this PR like it's now, just removing the dead tools. I will open a new one with the other tools, and then it can be announced to uyuni release notes.
Could you review it? Thank you

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
