### PR TITLE
Use the new apache2-mod_wsgi package name

### PR DESCRIPTION
**Pull request by deneb-alpha**
## What does this PR change?

**Use the new apache2-mod_wsgi package name**

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **no test added but built locally on OBS**

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/22574

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mcalmer — APPROVED** [review]

**Comment by mcalmer** [comment]
@deneb-alpha merge or close?

**Comment by deneb-alpha** [comment]
> @deneb-alpha merge or close?

...my bad. I missed to merge this :(
Can't check if everything looks fine now, but this should be merged too. 
I'll take care of it when back on Monday. But just in case, let me add a review also for @raulillo82

**Review by raulillo82 — APPROVED** [review]
LGTM

**Review by juliogonzalez — COMMENTED** [review]
If releng approved, it should be good to go. Ping @mcalmer so it doesn't get stale again :)

**Comment by mcalmer** [comment]
If nobody wants to press the merge button, I do it

**Pull request merged**
