### PR TITLE
Add a list of handled routes as a sitemap and a generator script

### PR DESCRIPTION
**Pull request by ncounter**
## What does this PR change?

Add a sitemap with all handled routes and a script to generate it by extracting them from the codebase.

PS:
- a nice visual tester for `regex` can be found [here](https://www.debuggex.com/)
- simple text tester for `regex` [here](https://regexr.com/)

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: 

- [x] **DONE**

## Test coverage
- No tests:

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"      
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@ncounter what this is about? Is this only for testing? Should it get merged?

**Comment by ncounter** [comment]
@juliogonzalez no, nothing urgent. It generates a list of all *digested* URLs the product is capable to serve some content to. I'll merge after the current release.

@cbbayburt @juliogonzalez  do you know/can you point me to a proper place where I can let the script be executed during the process? I am not an expert of the complete cycle :)

**Comment by juliogonzalez** [comment]
Well, we don't have nothing that makes commits to the GitHub repository, and this thing is not part of a package that we can build at OBS.

So... when and how are we going to use this? If it is going to be used only by developers, I'd exclude the `sitemap.xml` from the PR so they can generate it when needed.

Can you provide more details?

**Comment by ncounter** [comment]
@juliogonzalez yeah, I kind of agree. Of course it would be nice to keep it up to date instead of "remember to re-generate first", and we always forget to do it, but maybe it is fine to just have the script in the codebase, and generate the `sitemap.txt` from time to time. It is useful only for developers so far, let's do not do the *overengineering* part before the need. I'd like to keep the `sitemap.txt` in the PR anyway, and we will keep it up-to-date manually for now. Fine by you @juliogonzalez and @cbbayburt ?

**Pull request merged**
