### PR TITLE
Manager bsc1135659

### PR DESCRIPTION
**Pull request by mantel**
## What does this PR change?

An echo command in the bootstrap script is missing the closing quotation mark which breaks the complete script. This PR fixes it.

### CODE REVIEW

**Comment by mcalmer** [comment]
@mantel - we need to check if it must be fixed for RC1. In this case we need to push to a different branch.

**Comment by mcalmer** [comment]
@juliogonzalez As this is an isolated package it would make sense to re-submit it with this fix for RC1.
What do you think ?

**Comment by juliogonzalez** [comment]
@mantel, please switch the branch to 4.0-rc1, so I can tag and submit the package with the fix.

I will then port the change to master.

**Comment by mantel** [comment]
> Please change target branch to `4.0-rc1` and fix possible conflicts.
> 
> Other than that, this LGTM!

https://github.com/uyuni-project/uyuni/pull/1003

**Comment by juliogonzalez** [comment]
@mantel it would be easier clicking "Edit" next to the PR title and then changing the target branch there.

But since you created #1003, I am closing this one. I will do the port to master after #1003 is merged.

**Comment by mantel** [comment]
> @mantel it would be easier clicking "Edit" next to the PR title and then changing the target branch there.
> 
> But since you created #1003, I am closing this one. I will do the port to master after #1003 is merged.

Seems I'm too stupid to edit the target branch for an existing PR. It only allows me to edit the description... :/

**Comment by juliogonzalez** [comment]
@mantel that's weird. I was not aware only admins can do that. I should review permissions :\

**Pull request closed without merging**
