### PR TITLE
Prettify our JSON files

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Prettify our JSON files, so using grep to look for something on the code does not return a lot of "trash" ;-)

I basically ran:
```
cat <FILE> | python3 -m json.tool > /tmp/file.tmp; cp /tmp/file.tmp <FILE>
```
For all affected files, and then fixed the differences detected by @agraul because of some backticks

Tests should still pass, as the data was not changed.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed:  Just a format change for the test data.

- [x] **DONE**

## Test coverage
- No tests: Just a format change for the test data.

- [x] **DONE**

## Links

Nothing.

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by agraul** [comment]
As far as I can tell, some characters got changed (using `jq` to pretty-print as a comparison):
```
diff -b <(git show master:java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | jq) java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | tail  
---
>                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
297433c297433
<                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business’ needs.",
---
>                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
298522c298522
<                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business’ needs.",
---
>                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
```
I passed `-b` to `diff` to ignore white space changes, `jq` uses 2 spaces for indentation instead of 4.

BTW, I really recommend [`jq`](https://stedolan.github.io/jq/tutorial/) for searching json structures. It understands the structure and let's you select which elements to look in

**Comment by juliogonzalez** [comment]
> As far as I can tell, some characters got changed (using `jq` to pretty-print as a comparison):
> 
> ```
> diff -b <(git show master:java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | jq) java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | tail  
> ---
> >                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
> 297433c297433
> <                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business’ needs.",
> ---
> >                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
> 298522c298522
> <                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business’ needs.",
> ---
> >                                 "description": "SUSE Linux High Availability Extension provides mature, industry-leading open-source high-availability clustering technologies that are easy to set up and use. It can be deployed in physical and/or virtual environments, and can cluster physical servers, virtual servers, or any combination of the two to suit your business\u2019 needs.",
> ```
> 
> I passed `-b` to `diff` to ignore white space changes, `jq` uses 2 spaces for indentation instead of 4.

I can't see what characters are changing? What's the difference? (Maybe it's because I am Friday and I am already blind :-D)

> BTW, I really recommend [`jq`](https://stedolan.github.io/jq/tutorial/) for searching json structures. It understands the structure and let's you select which elements to look in

Sure, but that's not the point of the PR. Problem is that if you are grepping the whole source code for some keywords, the JSON in one line cause a big mess, and you need to start excluding them.

**Comment by juliogonzalez** [comment]
> Saw it now, sorry ;-)
> 
> `\u201` vs `'`
> 
> I will need to have a look next week

@agraul, but even with that, the tests are passing, so I am wondering if changing that is not OK? :-)

**Comment by juliogonzalez** [comment]
Diff is now clean:

```
$ diff -b <(git show master:java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | jq) java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json | tail  
$ 
```
```
$ diff -b <(git show master:java/code/src/com/suse/manager/reactor/utils/test/productdata/repositories.json | jq) java/code/src/com/suse/manager/reactor/utils/test/productdata/repositories.json | tail  
$ 
```

**Review by agraul — APPROVED** [review]
LGTM!

**Comment by juliogonzalez** [comment]
Thanks for the review. I will merge this when the branch is unlocked.

**Pull request merged**
