### PR TITLE
port schema_idempotency_test to python3

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Port script to python 3

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql" (Test skipped, there are no changes to test)
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
@mackdk @cbosdo This make the script work, but it find problems with already existing scripts from you. Need to talk about it

**Review by mackdk — APPROVED** [review]

**Comment by cbosdo** [comment]
LGTM but do you have more details on the issues you see before this is merged?

**Comment by mackdk** [comment]
> LGTM but do you have more details on the issues you see before this is merged?

@cbosdo It's a small issue with two sql update scripts. Mine was having an issue that for some reason did not pop up earlier. One of yours is not idempotent if you start the upgrade from schema version >= 4.3.0. I'm fixing both problems.

**Comment by cbosdo** [comment]
> > LGTM but do you have more details on the issues you see before this is merged?
> 
> @cbosdo It's a small issue with two sql update scripts. Mine was having an issue that for some reason did not pop up earlier. One of yours is not idempotent if you start the upgrade from schema version >= 4.3.0. I'm fixing both problems.

Thanks for the explanation and the fix. The PR is good for me too then

**Review by cbosdo — APPROVED** [review]

**Pull request merged**
