### PR TITLE
Notify users when updates are available to the Uyuni server

### PR DESCRIPTION
**Pull request by renner**
## What does this PR change?

This patch contains code to check in the background for updates or critical security patches available from the official Uyuni channels on a daily basis (via the `daily summary` taskomatic job). Users are then notified in the UI with a reference to the latest release notes accordingly. The notification shown is currently rather generic and the patch relies on the repo names in order to work (), so this could be further improved in a number of ways. For example we could:

- Identify official channels via the URL instead of the repo name (to make it work even if an admin renamed the channels)
- Send email notifications or show a more prominent popup right after login
- Make the notification message more specific and show more details, for example distinguishing between security patch and new Uyuni version

## GUI diff

image

## Documentation

- No documentation needed, the feature is self-explanatory, at least in the current state.

## Test coverage

- Unit tests were added

## Links

Downstream Issue: https://github.com/SUSE/spacewalk/issues/17919
Downstream PR (originally created by @mseidl): https://github.com/SUSE/spacewalk/pull/21922

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository.

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below).

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by deneb-alpha — APPROVED** [review]
LGTM, changes approved already in https://github.com/SUSE/spacewalk/pull/21922

**Review by raulillo82 — APPROVED** [review]
LGTM (compared with https://github.com/SUSE/spacewalk/pull/21922/files)

**Review by mackdk — APPROVED** [review]

**Comment by deneb-alpha** [comment]
do not merge until @jordimassaguerpla will give the OK

**Review by jordimassaguerpla — APPROVED** [review]
You can merge now

**Pull request merged**
