### PR TITLE
WIP: add Multi-Arch header for Debian packages

### LINKED ISSUE #1030: Support additional headers for deb packages
According to @rpasche's mail to uyuni-devel:

> Several metadata headers are missing for Debian packages, that causes
> major issues on Debian / Ubuntu systems.
> 
> One header is the "Multi-Arch" header, that is missing. This missing
> header causes packages to be installable over and over again. "apt" does
> not correctly "get it", that this package is already the newest
> installed and suggests these packages when searching for updates all the
> time.

My initial impression is that we have to extend `spacewalk-repo-sync` to take additional headers into account when syncing each package.
Some changes to the database might also be needed in order to store these additional packages fields.

### PR DESCRIPTION
**Pull request by rpasche**
## What does this PR change?

**This is WIP It's a first attempt to add the ```Multi-Arch``` header to Debian packages**

## GUI diff

No difference.

Before:

After:

- [X] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- [doc-susemanager](https://github.com/SUSE/doc-susemanager) PR or issue was created (GitHub automatic link expected below)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #1030 (it might fix it)
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"

### CODE REVIEW

**Comment by rpasche** [comment]
@mateiw 

This is just my kind attempt to fix the ```Multi-Arch``` header problem within Debian packages. The code is completely untestet, as I am missing some major things.

- If I read correct, there is a ```repomdgenerator_package_elab``` function that elaborates all packages. But how (and where) is the ```PackageDto``` data generated? So how does the data from the query used to create a ```PackageDto``` object?

- I would just like to add a ```multi_arch``` filed into the ```rhnPackage``` table. That should be enough.

- Package import: I also don't get it, how (and where) I have to change code to also insert the ```multi_arch``` field while importing the packages?

In case the ```PackageDto``` object would contain the ```multi_arch``` data, I think the ```DebPackageWriter.java``` should be ok.

Any help will be appreciated.

Thanks.

**Comment by rpasche** [comment]
Import of ```Multi-Arch``` value is working.

**Comment by rpasche** [comment]
I still need help with the first point.... How the data from a query is transferred (elaborated) into a ```PackageDto``` object?

Points 2 and 3 (part of importing the header is already working). Now I want to test, if the data gets correctly written to the Packages.gz file.

**Comment by mcalmer** [comment]
@rpasche - sorry if currently nobody is stepping in to help here. We are short before a release and everybody needs to work on this first. But that will change soon and this issue is on top of our list as well.

Currently I see two things missing:

1. a DB schema change and here we need to discuss if it is just this one field of if more will come? Maybe a new table to hold these extra metadata would be usefull?
2. If we need to parse metadata we need to trust them. I think we should implement GPG check for debian metadata. We have it for repomd using yum. But AFAIK this is not yet implemented for deb format.

**Comment by rpasche** [comment]
@mcalmer: I fully understand the situation right before the release. No problem.

Yes...a DB scheme change is needed. In my simple test, I just added the field to the ```rhnPackage``` table and until now, it "seems" no other Debian header - that is currently missing - is as important as the 'Multi-Arch' header. Also I'm not a DB expert and don't know, how many queries would have to be changed to possibly support "all" Debian headers. Therefore, the "easy" (possibly not the right) solution.

rpasche

⁣sent from my mobile device​


-------- Originale Nachricht --------
Von: Michael Calmer <notifications@github.com>
Gesendet: Mon Jun 10 13:51:21 GMT+02:00 2019
An: uyuni-project/uyuni <uyuni@noreply.github.com>
Cc: Robert Paschedag <robert.paschedag@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [uyuni-project/uyuni] WIP: add Multi-Arch header for Debian packages (#1072)

@rpasche - sorry if currently nobody is stepping in to help here. We are short before a release and everybody needs to work on this first. But that will change soon and this issue is on top of our list as well.

Currently I see two things missing:

1. a DB schema change and here we need to discuss if it is just this one field of if more will come? Maybe a new table to hold these extra metadata would be usefull?
2. If we need to parse metadata we need to trust them. I think we should implement GPG check for debian metadata. We have it for repomd using yum. But AFAIK this is not yet implemented for deb format.

**Comment by rpasche** [comment]
@mateiw, @mcalmer 

I know....you're infront of a release. I finally got it working (in the easiest form). Only thing that's missing in the code (because I don't know, where and how I should put that) is the DB schema change.

What I did on my test system is

```
ALTER TABLE rhnPackage ADD multi_arch character varying(16);
```
to support (in the first place) only the ```Multi-Arch``` header.

**Comment by mateiw** [comment]
@rpasche I think on the long run it would be better to support all headers and do it in a secure way. I've started an [RFC](https://github.com/uyuni-project/uyuni-rfc/pull/7) to discuss a more comprehensive approach. 
Feel free to take a look. Your feedback is highly appreciated.

**Comment by cbbayburt** [comment]
Hi @rpasche!

I've tested your code (also adding the DB column manually) and it works for me. Thanks!

However, `Multi-Arch` is not the only missing column and we should keep in mind especially when doing schema changes.

As @mateiw commented, there's an RFC open for discussion at the moment (https://github.com/uyuni-project/uyuni-rfc/pull/7).

As soon as the RFC is finalized, you can update your PR to comply with it and we can go ahead and merge. Please feel free to contribute to the RFC process itself.

Meanwhile, here's the wiki link to the instructions on modifying the DB: [Database Schema & Migration](https://github.com/uyuni-project/uyuni/wiki/Database-Schema-and-Migration)

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by rpasche** [comment]
This has already been implemented.

**Pull request closed without merging**
