### PR TITLE
Unit test for reportdb doc

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Reportdb documentation is codebase, we need to ensure that the information for generating documentation are aligned with the current schema

## GUI diff

- [x] **DONE**

## Documentation
- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17651

- [x]  **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql" (Test skipped, there are no changes to test)
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mbussolotto** [comment]
https://github.com/SUSE/spacewalk/issues/17651

**Comment by mackdk** [comment]
@mbussolotto Whoops, I did not mean to close this, sorry! I did not consider this side effect when I merged my PR :man_facepalming: Please reopen the PR on top of hub-reporting-rc1

**Comment by mcalmer** [comment]
@mackdk according to github, you closed this PR :-)
Maybe it close automatically when the target is closed/merged?

**Comment by mbussolotto** [comment]
I think yes, and currently I m not able to repopen it. Anyway my bad, I mean to open it againsts `hub-reporting-rc1`. I will create a new PR

**Comment by mbussolotto** [comment]
new PR https://github.com/uyuni-project/uyuni/pull/5306

**Pull request closed without merging**
