### PR TITLE
Support containerized peripheral server

### PR DESCRIPTION
**Pull request by nadvornik**
## What does this PR change?

This PR enables registration of containerized peripheral server.
It adds new "Peripheral Server" entitlement that can be used with foreign or minion base entitlement.

Then it adds API calls

system.registerPeripheralServer for registration of foreign peripheral server
system.updatePeripheralServerInfo to add/update report db info

## GUI diff

After: Peripheral Server entitlement is shown in Add-On System Types on Properties tab.

- [ ] **DONE**

## Documentation
- TBD

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/22498

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]
LGTM

**Review by rjmateus — COMMENTED** [review]
Two questions from my side:
- We should call the system list refresh for this system otherwise it will take to much time for the system to show up on the systems list page.
- Do we still need the method in [1] and the grains associated to it? It was used in the previous method when the rpm base server was running on the machine and it would collect the report DB connection information. Should we clean it?

[1] https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/manager/system/SystemManager.java#L3892

**Comment by rjmateus** [comment]
One more note, you are also missing the translation string for "peripheral_server"
image

**Review by rjmateus — APPROVED** [review]
LGTM

**Review by cbbayburt — APPROVED** [review]
Reviewed the API endpoints on behalf of 'frontend'. LGTM :+1:

**Pull request merged**
