### PR TITLE
Master - eos icons

### PR DESCRIPTION
**Pull request by ncounter**
## What does this PR change?

Introducing `eos-icons` set [see here](https://icons.eosdesignsystem.com/cheatsheet)

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by ncounter** [comment]
Update: still a Draft as it requires more effort and more changes. I will revisit but not in the next few days.

**Comment by juliogonzalez** [comment]
Dear developer:

A branch for SUSE Manager 4.1 is now created on the internal repository, and all package SPEC files in the master branch of this repository are now updated to be '4.2.0' version.

All developers, regardless of being SUSE employee or not, need to keep the following things in mind:

1. Please rebase this PR against `master`branch and fix any conflicts.
2. If this PR includes schema upgrades, change the directory for the migration scripts to the **correct one**. At this precise moment it is `schema/spacewalk/upgrade/susemanager-schema-4.2.0-to-susemanager-schema-4.2.1` but it could be a different one if this PR is still open after Uyuni 2020.08 is released.

SUSE employees must also keep in mind:

1. If you merge the PR here, you most likely want to backport it to the new `Manager-4.1` branch.
2. You will need to **adapt** the PR when backporting for at least the changelogs and schema migrations (if there are on your PR).

**Comment by ncounter** [comment]
This is still in Draft mode, nothing changed so far. I hope I will be able to plan to work in this soon (some weeks).

**Comment by ncounter** [comment]
Closing for now, resurrecting it later.

**Pull request closed without merging**
