### PR TITLE
Adapt Cobbler power management functionality to use new power_system API call (bsc#1128919)

### PR DESCRIPTION
**Pull request by mateiw**
## What does this PR change?

Adapt Cobbler power management functionality to use [new power_system API call](https://github.com/cobbler/cobbler/pull/2050) (bsc#1128919)

## GUI diff

No difference.

## Documentation
- No documentation needed

## Test coverage
- No tests: cucumber tests already exist.

## Links

Fixes https://github.com/SUSE/spacewalk/issues/7273

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"

### CODE REVIEW

**Comment by mateiw** [comment]
CC: @juliogonzalez

**Comment by juliogonzalez** [comment]
LGTM. WTFB and merging.

**Comment by juliogonzalez** [comment]
@mateiw, there are conflicts for spacewalk-java.changes.

**Comment by juliogonzalez** [comment]
Merging.

**Pull request merged**
