### PR TITLE
QA: Upgrade test framework dependencies

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

Upgrade test framework dependencies

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed

- [x] **DONE**

## Test coverage
- Cucumber tests were added

- [x] **DONE**

## Links

Ports:
- Manager-4.1

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by srbarrios** [comment]
I tested locally and the tests pass perfectly fine.
But we need to assure that the report works well too.

**Comment by Bischoff** [comment]
Some needed changes are in #4078 .

**Review by Bischoff — APPROVED** [review]
lgtm

see also pr #4078

**Comment by srbarrios** [comment]
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1065/console

**Comment by srbarrios** [comment]
https://ci.suse.de/blue/organizations/jenkins/uyuni-prs-ci-tests/detail/uyuni-prs-ci-tests/1132/pipeline

**Pull request merged**
