### PR TITLE
Switching bootstrapping packages to python3 for Ubuntu 18.04

### PR DESCRIPTION
**Pull request by brejoc**
## What does this PR change?

Switching bootstrapping packages to python3 for Ubuntu 18.04. Since Python3 is the default for 18.04, we should also switch with the update to Salt 3000.

## GUI diff

No difference.
## Documentation
- No documentation needed: I don't think there is anything to document.

## Test coverage
- No tests: All of this should already be covered by tests.

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by brejoc** [comment]
Those packages are missing and need to be checked:

* python3-ipaddress
* python3-enum34
* python3-concurrent.futures
* python3-backports-abc

**Comment by juliogonzalez** [comment]
@brejoc when this gets merged **PING** me, as I will need to adjust the Ubuntu 18.04 salt links at Head and Uyuni:Master!!!!!

**Comment by brejoc** [comment]
@juliogonzalez The hard part here is that some of them might be soft dependencies that are needed by some modules. So it's hard to see if they are really needed or not.

**Comment by juliogonzalez** [comment]
@brejoc what do you mean? that maybe some dependencies are missing at the bootstrap repo now?

If so, it's easy:

1. Install a clean Ubuntu 18.04, minimal setup.
2. Disable all repos
3. Add the bootstrap repo.
4. `apt-get install salt-minion`.
5. If something is missing add it to the bootstrap repo
6. Continue until `salt-minion` is able to install.

**Comment by brejoc** [comment]
@juliogonzalez No, the opposite. There might be dependencies that we don't really need. But this is hard to check, since we don't have hard dependencies on those from the salt package.

**Comment by juliogonzalez** [comment]
Ah, got it now.

Well, not that hard to check... but takes time.

You could start from an bootstrap repo with `salt-minion` and `salt-common` at step 3, and then add packages until `salt-minion` is instalable.

But not urgent anyway.

**Pull request merged**
