### PR TITLE
Fix errata email subject header (sanitize newlines)

### PR DESCRIPTION
**Pull request by santeri3700**
## What does this PR change?

Fix errata email subject header when patch advisory or synopsis has newlines.

Before this fix, errata emails can be malformed when a patch advisory or synopsis contains a newline. \
This can cause some headers (e.g. `X-RHN-Info`) and parts of the subject to leak into the body of the email.

The advisory and synopsis fields in the Web UI are single line text inputs (not sanitized for newlines), but it is possible to add new lines via other methods (API etc).

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: Only affects errata emails

- [X] **DONE**

## Test coverage
- Added a newline to the existing test errata's synopsis

- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by santeri3700** [comment]
This is what a malformed errata email looks like (in Thunderbird) with some of the headers leaking into the body of the email.

uyuni-errata-email-malformed

**Comment by cbosdo** [comment]
Thanks a lot for the pull request. You can get rid of the sonarcloud failure by rebasing on latest master.

However the pgsql unit test failure is a real one. Since the results are not public (infra issues) I debugged it for you: you need to add the `\n` in https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/domain/action/test/ActionFormatterTest.java#L105 too.

**Review by cbosdo — CHANGES_REQUESTED** [review]
Missing `\n` failing `ActionFormatterTest.testErrataFormatter()` unit test

**Comment by santeri3700** [comment]
Thanks for the tip! I'm not too familiar with Uyuni's Java code and the unit tests. Hopefully I did it correctly in the latest commit :) \
PS: I'm not sure about the rebasing and Sonarcloud failures. As far as I can see, I'm up-to-date with the master branch?

**Comment by cbosdo** [comment]
> ~PS: I'm not sure about the rebasing and Sonarcloud failures. As far as I can see, I'm up-to-date with the master branch?~ EDIT: Never mind, I'm pulling from the wrong origin. EDIT2: Sorry for the mess :P, should I revert that or keep it like it is? Looks like I have to study more about git and rebasing.


For the rebase you need to figure out which origin is the `uyuni-project/uyuni` remote. You may not have it yet if you `git clone`-d your fork so you would need to add it.
I have it as the `upstream` remote in all my clones. You can add it with:

```
git remote add upstream https://github.com/uyuni-project/uyuni
```

Then for the rebase you need to fetch the most recent changes in the upstream repo and rebase on them. You can do it with commands like this:

```
git fetch upstream
git rebase upstream/master
```

After this `git log` should only show your commit after the `upstream/master` reference and you can push to your remote branch to update the PR

**Comment by mcalmer** [comment]
Seems that a bigger merge problem happened. If there is no progress, I think we should close the PR.

**Comment by mcalmer** [comment]
no reaction - closing

**Pull request closed without merging**
