### PR TITLE
select packages with correct architecture in tests

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Some of our test packages exists in 2 architectures (i586 and x86_64).
All of our tests run with x86_64 clients. At least on SLES, i586 packages cannot be installed.
But our tests try to install the first match in the table which is always i586.

Add a step definition which match on 2 column texts to select correct architecture

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **internal**

- [x] **DONE**

## Test coverage
- No tests: **already covered**

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/10714

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"		 
- [ ] Re-run test "java_pgsql_tests"		 
- [ ] Re-run test "ruby_rubocop"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"		 
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"		 
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by Bischoff** [comment]
As discussed in person, I'm not too happy to specify the architecture in the step itself, for the future case we will want to run the test suite on other architectures.

But of course I'm happy it fixes a problem. Only thing is, I don't remember seeing this problem.

**Comment by srbarrios** [comment]
Do you tested and it is working?
I would need to review but I think I solved it differently in qam, filtering using the textfield above for that purpose. (I might be wrong, I will check on Monday ;))

**Comment by mcalmer** [comment]
Testsuite is currently running this branch (in TEST environment ). We will see if it works

**Comment by mcalmer** [comment]
I adapted the tests a bit and select the arch of the client. I saw that you have already some tables as constants in the code.
I had to do some small bugfix, but I hope it is now good to merge.
Another test is running now.

https://ci.nue.suse.com/view/Manager/view/Manager-Test/job/manager-TEST-cucumber-pipeline/411/

**Comment by Bischoff** [comment]
> I adapted the tests a bit and select the arch of the client. I saw that you have already some tables as constants in the code.

Aaah, now I prefer it a lot. Thanks! :smile_cat: 

If tests okay, for me LGTM

**Pull request merged**
