### PR TITLE
 Changed Apache users to dynamic users

### PR DESCRIPTION
**Pull request by sbluhm**
## What does this PR change?

Replaced static Apache Webserver users with central config.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by ycedres — COMMENTED** [review]
Thank you for the PR!
Do `CFG.httpd_user` and `CFG.httpd_group` have default values? Do you have custom values for them in your system configuration? I ask this because I tried to get them in my Uyuni instance but I got `AttributeError: httpd_user`.

**Comment by sbluhm** [comment]
Hello @ycedres 

> Do `CFG.httpd_user` and `CFG.httpd_group` have default values?

these should be set in rhn.conf. I am wondering actually what sets it on updates. Will check it out.

Out of curiosity, how would I set default values?

**Comment by mcalmer** [comment]
> > Do `CFG.httpd_user` and `CFG.httpd_group` have default values?
> Out of curiosity, how would I set default values?

With the files in /usr/share/rhn/config-defaults/

**Comment by sbluhm** [comment]
`spacewalk.backend-server`provides the default config file: `%{rhnconfigdefaults}/rhn.conf`.
From my understanding, this file should be replaced with a new one containing the httpd values.
https://github.com/uyuni-project/uyuni/blob/5b145745974aa96541082d9ad4a0982595ebd040/python/spacewalk/spacewalk-backend.spec#LL408C1-L408C62

**Comment by mcalmer** [comment]
Right, python/spacewalk/rhn-conf/rhn.conf defines these config values already and via macro hopefully the right user and group name is filled in during building.
@ycedres can you check, if in your test system /usr/share/rhn/config-defaults/rhn.conf has these config defaults defined?

**Comment by ycedres** [comment]
It was my fault, sorry. I upgraded my Uyuni VM and I got the proper config defaults. Thanks for the improvement @sbluhm!

**Review by ycedres — APPROVED** [review]

**Pull request merged**
