### PR TITLE
weblate Master

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Translation update

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by mackdk — COMMENTED** [review]
Not sure if this is needed, since master is locked. When I did it two weeks ago, I skipped 4.3 because it was locked.

**Comment by mbussolotto** [comment]
cc @juliogonzalez . Not sure if it was required since master is locked :)

**Review by parlt91 — APPROVED** [review]

**Review by juliogonzalez — CHANGES_REQUESTED** [review]
Please add a changelog entry, as I need to tag.

**Comment by mbussolotto** [comment]
> Please add a changelog entry, as I need to tag.

added

**Review by Etheryte — APPROVED** [review]

**Pull request merged**
