### PR TITLE
Ci refactor

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## What does this PR change?

CI: refactor to ease maintenance. Put the files in expected folders, use a more descriptive name for the tests, etc.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed
- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links

Fixes #https://github.com/SUSE/spacewalk/issues/21363 

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
Looks good to me.
But I would rename the Cucumber features that have container_ prepended.
Otherwise, maybe we need to agree on that different format in documentation/guidelines.md

**Review by Bischoff — CHANGES_REQUESTED** [review]
please see Oscar's remark about features naming, it's important we stick to the guidelines

**Comment by jordimassaguerpla** [comment]
> please see Oscar's remark about features naming, it's important we stick to the guidelines

Done.

**Review by srbarrios — APPROVED** [review]

**Review by vandabarata — CHANGES_REQUESTED** [review]
If we're changing the name of core features, we should also update the `run-testsuite essential` script with those, I would wager. 

eidt: unless I've got it wrong and this isn't part of the usual `core`

**Review by vandabarata — APPROVED** [review]
ignore me, just noticed it isn't the usual core :sweat_smile:

**Pull request merged**
