### PR TITLE
Do not trigger extra "cobbler sync" when changing kickstart data (bsc#1208536)

### PR DESCRIPTION
**Pull request by meaksh**
## What does this PR change?

This PR prevents Java to trigger an extra execution of `cobbler sync` when doing changes or creating Autoinstallation profiles.

Before this PR, these are the calls to Cobbler done by Java at the time of creating a new Autoinstallation profile (notice the 2 "cobbler sync" calls triggered):

```console
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'new_profile', None, None, 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'name', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'distro', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, None, 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'autoinstall_meta', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_bridge', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_cpus', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_ram', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_file_size', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'autoinstall', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, None, 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'distro', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'redhat_management_key', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'autoinstall_meta', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_type', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'enable_menu', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, None, 1]
!!! HERE ---> 2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'sync', None, None, 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'distro', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'kernel_options', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'kernel_options_post', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'redhat_management_key', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'autoinstall_meta', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'virt_type', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, 'enable_menu', 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, None, 1]
!!! HERE ---> 2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'sync', None, None, 1]
2023-03-08T17:06:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f8388772668>, None, 1]
```

Same when modifying Autoinstallation profiles:

```console
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'distro', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'redhat_management_key', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'autoinstall_meta', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'virt_type', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'enable_menu', 1] 
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, None, 1]
!!! HERE --->  2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'sync', None, None, 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'distro', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'kernel_options', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'kernel_options_post', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'redhat_management_key', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'autoinstall_meta', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'virt_type', 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, 'enable_menu', 1] 
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, None, 1]
!!! HERE ---> 2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'sync', None, None, 1]
2023-03-08T16:22:53 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f838a406278>, None, 1]
```

After this PR, we only trigger a single `cobbler sync` execution:

```console
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'new_profile', None, None, 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'name', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'distro', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, None, 1] 
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'autoinstall_meta', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_bridge', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_cpus', 1] 
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_ram', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_file_size', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'autoinstall', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, None, 1] 
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'distro', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'redhat_management_key', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'autoinstall_meta', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_type', 1] 
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'enable_menu', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, None, 1] 
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'distro', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'kernel_options', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'kernel_options_post', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'redhat_management_key', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'autoinstall_meta', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'virt_type', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'modify_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, 'enable_menu', 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, None, 1]
!!! HERE ---> 2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'sync', None, None, 1]
2023-03-08T17:20:31 - DEBUG | authorize; ['admin', 'save_profile', <cobbler.items.profile.Profile object at 0x7f48765e4be0>, None, 1]
```

Additionally, this PR is also fixing an issue that can cause failures during Tasktomatic `cobbler-sync-bunch` execution, due `NullPointerException`, as the former Cobbler collection `kickstart` attribute has been renamed to `autoinstall` in latest Cobbler 3.3.3:

```console
2023-03-08 14:00:47,972 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - Executing a task threw an exception: java.lang.NullPointerException
2023-03-08 14:00:47,972 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - Message: null
2023-03-08 14:00:47,972 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - Cause: {}
2023-03-08 14:00:47,973 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - Stack trace:java.lang.NullPointerException
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerProfileSyncCommand.syncProfileToSpacewalk(CobblerProfileSyncCommand.java:154)
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerProfileSyncCommand.store(CobblerProfileSyncCommand.java:109)
        at com.redhat.rhn.taskomatic.task.CobblerSyncTask.execute(CobblerSyncTask.java:130)
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:105)
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:155)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

```

UPDATE: This is also fixing a NPE happening when clicking on "Provising -> "Create PXE installation configuration" button more than once:

```console
Caused by: java.lang.NullPointerException
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerXMLRPCHelper.getConnection(CobblerXMLRPCHelper.java:84) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerCommand.lookupExisting(CobblerCommand.java:203) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerSystemCreateCommand.store(CobblerSystemCreateCommand.java:249) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerSystemCreateCommand.store(CobblerSystemCreateCommand.java:236) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.action.kickstart.ScheduleKickstartWizardAction.runFourth(ScheduleKickstartWizardAction.java:792) ~[rhn.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.redhat.rhn.frontend.struts.wizard.WizardStep.invoke(WizardStep.java:115) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.struts.wizard.RhnWizardAction.dispatch(RhnWizardAction.java:103) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.struts.wizard.RhnWizardAction.execute(RhnWizardAction.java:89) ~[rhn.jar:?]
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431) ~[struts-1.2.9.jar:1.2.9]
        ... 50 more
```

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/20558

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by meaksh** [comment]
CI execution: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/2231/

**Review by SchoolGuy — COMMENTED** [review]
At first glance, this PR looks very promising. I believe that the same approach for Cobbler Systems & Images would be good.

**Comment by meaksh** [comment]
@SchoolGuy for "systems" and "images" there is no explicit "cobbler sync" execution, but any change done for "systems" or "images" will make taskomatic `CobblerSyncTask` task to trigger a `cobbler sync` execution on the next run:

- Systems:

```console
[Thread-9220] 2023-03-09T14:40:26 - DEBUG | authorize; ['admin', 'new_system', None, None, 1]
[Thread-9221] 2023-03-09T14:40:26 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, 'name', 1]
[Thread-9222] 2023-03-09T14:40:26 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, 'image', 1]
[Thread-9223] 2023-03-09T14:40:26 - DEBUG | authorize; ['admin', 'save_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, None, 1]
[Thread-9227] 2023-03-09T14:40:31 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, 'netboot_enabled', 1]
[Thread-9229] 2023-03-09T14:40:31 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, 'power_type', 1]
[Thread-9231] 2023-03-09T14:40:31 - DEBUG | authorize; ['admin', 'save_system', <cobbler.items.system.System object at 0x7f4876f0cc88>, None, 1]
!!! HERE --> [Thread-9248] 2023-03-09T14:41:00 - DEBUG | authorize; ['taskomatic_user', 'sync', None, None, 1]
```

- Images:

```console
[Thread-9117] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'new_image', None, None, 1]
[Thread-9118] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'modify_image', <cobbler.items.image.Image object at 0x7f4875d4f898>, 'name', 1]
[Thread-9119] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'modify_image', <cobbler.items.image.Image object at 0x7f4875d4f898>, 'image_type', 1]
[Thread-9120] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'modify_image', <cobbler.items.image.Image object at 0x7f4875d4f898>, 'file', 1]
[Thread-9121] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'save_image', <cobbler.items.image.Image object at 0x7f4875d4f898>, None, 1]
[Thread-9125] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'save_image', <cobbler.items.image.Image object at 0x7f4875d4f898>, None, 1]
[Thread-9126] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'new_system', None, None, 1]
[Thread-9127] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876d96278>, 'name', 1]
[Thread-9128] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876d96278>, 'image', 1]
[Thread-9129] 2023-03-09T14:30:11 - DEBUG | authorize; ['admin', 'save_system', <cobbler.items.system.System object at 0x7f4876d96278>, None, 1]
[Thread-9133] 2023-03-09T14:30:16 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876d96278>, 'netboot_enabled', 1]
[Thread-9135] 2023-03-09T14:30:16 - DEBUG | authorize; ['admin', 'modify_system', <cobbler.items.system.System object at 0x7f4876d96278>, 'power_type', 1]
[Thread-9137] 2023-03-09T14:30:16 - DEBUG | authorize; ['admin', 'save_system', <cobbler.items.system.System object at 0x7f4876d96278>, None, 1]
!!! HERE --> [Thread-9154] 2023-03-09T14:31:00 - DEBUG | authorize; ['taskomatic_user', 'sync', None, None, 1]
```

**Comment by SchoolGuy** [comment]
@meaksh Well then we should maybe remove the `cobbler sync` task from taskomatic? Or is that too drastic for this PR?

**Comment by meaksh** [comment]
> @meaksh Well then we should maybe remove the `cobbler sync` task from taskomatic? Or is that too drastic for this PR?

IMHO that is definetly too drastic change to make it in the context of this bugfix. That would be something to plan more carefully maybe as feature request.

There are currently certain operations in the UI that are not directly triggering a `cobbler sync` execution. Then, it is the `CobblerSyncTask` from taskomatic the one triggers the `cobbler sync` call on those situation. Keep in mind that `CobblerSyncTask`, that runs every minute, is NOT always trigger `cobbler sync` execution, only when it is needed.

Also the `CobblerSyncTask` from tasktomatic takes care of fixing possible inconsistencies on the Cobbler DB from what is is expected from the Uyuni DB.

**Comment by meaksh** [comment]
@SchoolGuy the errors you see were caused because I ran the testsuite only for certain scopes and this messed the environment. I manually triggere the cobbler features manually on the same environment and everything was green.

I'm running a FULL execution on the testsuite now, which should hopefully prevent those previous errors. I'll add the link here shortly.

**Comment by meaksh** [comment]
New CI (full) execution: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2247/

**Review by SchoolGuy — APPROVED** [review]
CI errors are gone. The code is looking like a good improvement to me. This should help reduce the load on the disk by a fair bit.

**Pull request merged**
