### PR TITLE
add BuildRequires to tomcat to know about tomcat owned directories

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Fix build in IBS for SUSE distro

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by mcalmer** [comment]
CC @sbluhm JFYI

**Comment by mcalmer** [comment]
> @mcalmer seems I missed out on that. Can you please put it outside the if statement? I think this should also apply to any other OS.

:+1:  Done

**Comment by deneb-alpha** [comment]
@sbluhm now change looks good to me. please, let me know if there's anything that is needed or if this PR can be merged

**Comment by sbluhm** [comment]
> @sbluhm now change looks good to me. please, let me know if there's anything that is needed or if this PR can be merged

Looking good. Feel free to merge.

**Review by deneb-alpha — APPROVED** [review]
LGTM

**Pull request merged**
