### PR TITLE
QE: Remove old cloud tests in BV

### PR DESCRIPTION
**Pull request by nodeg**
## What does this PR change?

This will remove the old cloud tests for SLES 15 SP2 and SP3 and align the code with what we already have in 4.3. See https://github.com/SUSE/spacewalk/pull/23592.
`contsants.rb` do not need to be adjusted, the entries are not present there.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes
- [x] **DONE**

## Test coverage
- Cucumber tests were edited
- [x] **DONE**

## Links

Issue(s): #
Ports(s): # not needed. The change is already present in 4.3

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by Bischoff — APPROVED** [review]
ok but shouldn't it be Maxime to approve?

**Comment by nodeg** [comment]
He could also approve. However, he already did the same PR in 4.3. See https://github.com/SUSE/spacewalk/pull/23592.

**Review by srbarrios — APPROVED** [review]
Thanks for the missing port.

**Review by NamelessOne91 — APPROVED** [review]
Thanks Dominik

**Review by ktsamis — APPROVED** [review]

**Pull request merged**
