### PR TITLE
Add expand/collapse all button and search box for Formulas

### PR DESCRIPTION
**Pull request by parlt91**
## What does this PR change?

Add buttons to expand/collapse all formula sections.
And provide a search box in the Formulas context. **Note:** the search box is capable to filter in/out by the section name whether the section is a `group` or an `edit group` type **only**.

## GUI diff

See: https://github.com/parlt91/uyuni/pull/2

- [x] **DONE**

## Documentation

- No documentation needed: 

- [x] **DONE**

## Test coverage

- No tests: 

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/13404

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@parlt91 @jordimassaguerpla was this tested with acceptance on PR? Are we sure we don't need any testsuite changes?

**Comment by parlt91** [comment]
Acceptance tests are currently running. Will post an update once they look good

**Comment by juliogonzalez** [comment]
@parlt91 seems some tests failed, so I won't merge this for now.

**Comment by juliogonzalez** [comment]
Removing label for now. Feel free to add it later if the PR is ready and master is still blocked.

**Pull request merged**
